apps/ui/src/helpers/constants.ts
This is just so we can see dollar value for Ethereum treasuries like here:
https://snapshotx.xyz/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c/treasury
=> chore: add Ethereum network for CoinGecko API

apps/ui/src/composables/useBalances.ts
Currently request to get assets price with Coingecko API failing when there is more than 10 contract address, this is the limit from the free API. Because of this we can't see assets value beside ETH here: https://snapshotx.xyz/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c/treasury
This PR add a limit of 10 so the request don't fail. This is a temporary fix, I'll get a paid account for the API that will increase the limit.
=> fix: use allowed limit Coingecko API

apps/ui/src/components/FormStrategies.vue, apps/ui/src/components/StrategiesConfigurator.vue, apps/ui/src/networks/evm/constants.ts, apps/ui/src/views/Create.vue
Currently execution strategy controller is set to space controller, but we should be able to configure it if needed.
With this change we also add `defaultParams` to StrategiesConfigurator so we can add defaults - in this case `controller` defaults to space controller.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/19
1. Go to http://localhost:8080/#/explore
2. Sign in
3. Select EVM network.
4. When selecting execution strategy you can input controller (it defaults to space controller).
=> feat: add controller input for execution strategies

.changeset/slow-stingrays-smash.md, apps/ui/.env, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/starknet/index.ts, packages/sx.js/src/strategies/starknet/evmSlotValue.ts, packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts, packages/sx.js/src/strategies/starknet/utils.ts
Predefined mapping was used initially, but as each networkConfig will have each own ethUrl we can use it as well (Starknet Goerli will be mapped to Ethereum goerli etc.).
1. Update `VITE_INFURA_API_KEY`.
2. Go to http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/proposals
3. See that it uses updated API key for Infura calls.
=> refactor: use clientConfig ethUrl for evmSlotValue and ozVotesStorageProof

apps/mana/src/stark/herodotus.ts
Handling some errors we are seeing in the wild and preventing retries on non-recoverable ones to avoid DoSing Herodotus APIs.
1. I tested it by connecting to prod DB can do the same if new case shows up.
2. Otherwise create sn-sep space with this address for EVM slot value: address `0xe8e4dcd310f157f3a8a71464d84cf5f3999066d` and slotIndex `0`
3. Run local sx-api pointing to local mana.
4. Create proposal.
5. It will try to process this proposal, `invalid herodotus batch` will show up once.
=> feat(mana): do not retry herodotus batch when failed on some errors

apps/api/package.json, apps/api/tsconfig.build.json, apps/mana/package.json, apps/mana/src/eth/dependencies.ts, apps/mana/src/eth/index.ts, apps/mana/src/eth/rpc.ts, apps/mana/src/knex.ts, apps/mana/src/stark/dependencies.ts, apps/mana/src/stark/herodotus.ts, apps/mana/src/stark/index.ts, apps/mana/src/stark/networks.ts, apps/mana/src/stark/rpc.ts, apps/mana/src/utils.ts, apps/mana/tsconfig.json, tsconfig.json, yarn.lock
Our types have plenty of holes in it, due to disabled `noImplicitAny`
and not using `noUncheckedIndexedAccess`.
This PR creates base config which all repos should eventually use
and migrates mana to start using it.
Changes on mana side:
- use zod for validating request shape
- use Map instead of objects when it makes more sense
- remove implicit any in params
1. Run `yarn dev:full` and vote or propose on Starknet sepolia space.
=> refactor: improve typing on mana repo

apps/ui/src/views/Space/Proposals.vue
Show the "Create new proposals" button for offchain spaces, in the proposals page
1. Go to an offchain spaces, then proposals page (e.g. http://localhost:8080/#/s-tn:wan-test.eth/proposals)
2. The "Create proposal" button should appear on page top right, next to the voting power 
Final result should look like
=> fix: enable create proposal button for offchain spaces

apps/ui/src/composables/useActions.ts
We can just use wrapPromise for all actions as it can detect if envelope format is used or not.
Omitted createSpace/deployDependency actions as they use different flow (no pending transaction) for now, we will see what we will need in the future.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/89
1. Go to space you control.
2. Modify profile.
3. Modify settings.
=> refactor: use wrapPromise for every non-deploy action

apps/api/src/ipfs.ts, apps/api/src/schema.gql, apps/subgraph-api/schema.graphql, apps/subgraph-api/src/ipfs.ts, apps/subgraph-api/src/mapping.ts, apps/ui/src/components/App/Nav.vue, apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/FormProfile.vue, apps/ui/src/components/Modal/EditSpace.vue, apps/ui/src/components/Modal/TreasuryConfig.vue, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/composables/useTreasury.ts, apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/networks/common/graphqlApi/types.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Create.vue, apps/ui/src/views/Editor.vue, apps/ui/src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/18
Decisions:
1. We have two sources of truth for treasuries - executions and user configured treasuries on metadata, with this PR treasuries configured in metadata are used as a "whitelist" of executors that should be displayed on UI (in both treasury as well in proposal creation). You can also add treasuries that are not linked to executor to create read only treasury (can't be used in execution).
2. We had to index additional properties on backend to be able to link executors to treasuries.
UI is temporary as design were not confirmed to be final.
1. Run `VITE_ENABLED_NETWORKS=sep yarn dev:full`. (it can take some time for subgraph to be in sync).
2. Interact with this space as a user (check treasury, try creating proposals): …
=> feat: configure and store multiple treasuries

apps/ui/src/helpers/validation.ts
With draft v7 we don't have a way to define non-homogenous without breaking strict mode, so for now we will just disable it to avoid warnings.
In the future we could go to newer draft version, but v7 is recommended due to its speed.
1. Go to editor http://localhost:8080/#/s-tn:weth.testsnap.eth/create
2. Start typing.
3. No errors in console.
=> chore: disable strictTuples

apps/ui/src/components/Modal/VotingPower.vue, apps/ui/src/helpers/link.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/types.ts
Add an external link "Buy" that redirect to Uniswap swap page on voting power modal for compatible strategies
You can test it here: http://localhost:8080/#/s:ens.eth/proposals
Or here: http://localhost:8080/#/s:stgdao.eth/proposals
Later we could improve that and integrate swap directly in our UI.
=> feat: add swap link for strategies

apps/ui/src/components/Modal/SendToken.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/103
1. Go there http://localhost:8080/#/sep:0x8b08aa6cdaf0bc92bb9cc6844459b2fed94249af/treasury
2. Click on modal to send token, only crypto asset input is visible.
3. Apply diff from below.
4. Repeat steps 1-2, you see input for USD value.
```diff
diff --git a/apps/ui/src/components/Modal/SendToken.vue b/apps/ui/src/components/Modal/SendToken.vue
index 5380a701..b75b1230 100644
--- a/apps/ui/src/components/Modal/SendToken.vue
+++ b/apps/ui/src/components/Modal/SendToken.vue
@@ -153,7 +153,7 @@ async function handleSubmit() {
}
onMounted(() => {
-  loadBalances(props.address, props.network);
+  loadBalances('0x556B14CbdA79A36dC33FcD461a04A5BCb5dC2A70', 1);
});
watch(
```
=> feat: hide USD value input if price is 0

.changeset/tasty-pets-battle.md, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/offchain/helpers.ts, packages/sx.js/src/clients/offchain/types.ts, packages/sx.js/src/strategies/index.ts, packages/sx.js/src/strategies/offchain/index.ts, packages/sx.js/src/strategies/offchain/only-members.ts, packages/sx.js/src/strategies/offchain/remote-validate.ts, packages/sx.js/src/strategies/offchain/remote-vp.ts, packages/sx.js/src/strategies/offchain/utils.ts
This is still a bit hacky as we have to work within constrains of some assumptions from SX (per-strategy validation, multiple proposal validation strategies), so I tried to make it "fit".
As strategies are handled at Score API, sx.js's strategies are abstract wrappers to different types of validations, for example:
1. remote-vp: validates VP using get_vp call for all enabled strategies
2. remote-validate: validates proposal using validate call
3. only-members: not really abstract, performs validation offline
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/60
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/74
1. VP is visible there: http://localhost:8080/#/s-tn:weth.testsnap.eth/proposals
2. Proposal validation passes when trying to propose.
=> feat: move offchain space VP computation to sx.js

apps/api/src/writer.ts, apps/ui/src/composables/useWeb3.ts, apps/ui/src/helpers/stamp.ts, apps/ui/src/helpers/utils.ts
Ethereum checksummed addresses and Starknet padded addresses will be used across app.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/67
Not sure if I caught all cases - if there are places where we do not shorten addresses it won't be updated, but I don't recall such places.
1. Check across apps, there are no non-checksummed or non-padded addresses.
=> feat: format addresses to common format across app

apps/subgraph-api/abis/AxiomExecutionStrategy.json, apps/subgraph-api/package.json, apps/subgraph-api/src/mapping.ts, apps/subgraph-api/subgraph.yaml
With this change axiom strategies will be now indexed.
1. Create space with latest axiom strategy (`0xE59405D7d40df064E85FD02a4F2F2C527172a9c1`).
2. Propose, vote, execute.
3. It should show up as executed.
=> feat: index Axiom execution

apps/ui/src/components/Modal/Account.vue
Modal title is still "Connect wallet" - not sure if we want to update it too.
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/142
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/37
1. Connect wallet.
2. Click your address - "Change account" is displayed in modal.
=> feat: change test to Change wallet if already signed in

apps/ui/src/components/FormProfile.vue
It's usually it's set to space address but when creating new space we don't have space ID yet. Before it was passed as undefined, which worked (ignoring Vue warning), but now it fails as we try to format address.
This PR replaces undefined with valid address.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/144
1. Go to http://localhost:8080/#/create
2. Avatar is visible, no warnings in console.
=> fix: pass default stamp space avatar address

apps/api/src/schema.gql, apps/api/src/utils.ts, apps/api/src/writer.ts, apps/subgraph-api/schema.graphql, apps/subgraph-api/src/mapping.ts
This PR adds new `Leaderboard` entity as well as `proposer_count` and `voter_count` to space entity.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/48
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/157
1. Run `yarn dev:full`. Wait for subgraph/checkpoint to fetch some data.
2. Run this queries and it should make sense:
```gql
{
spaces {
id
vote_count
voter_count
proposal_count
proposer_count
}
leaderboards {
id
user {
id
}
space {
id
}
vote_count
proposal_count
}
}
```
=> feat: index Leaderboard and proposer/voter counts

.changeset/fifty-cats-wait.md, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/types.ts, apps/ui/src/views/Editor.vue, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Space/Proposals.vue, packages/sx.js/src/clients/offchain/types.ts, packages/sx.js/src/strategies/offchain/only-members.ts, packages/sx.js/src/strategies/offchain/remote-validate.ts, packages/sx.js/src/strategies/offchain/remote-vp.ts
Add new `space` params to `getVotingPower()`, used by offchain strategies
Closes: #147
1. To to an offchain space proposals page (e.g. http://localhost:8080/#/s-tn:wan-test.eth/proposals)
2. Open the web dev network tools
3. Inspect the query to https://score.snapshot.org/
4. In the POST payload, it should set the space params to the current space (before, it was just an empty string)
e.g
Repeat the same steps, but for an offchain proposal (e.g. http://localhost:8080/#/s-tn:wan-test.eth/proposal/0x819d95f7e00efa19ec3cc1794ca63d651241d4f82ccf813da24996e4e4ed3d95)
=> feat: add space param to offchain voting power strategies

.changeset/five-gifts-rest.md, apps/ui/src/networks/offchain/actions.ts, packages/sx.js/src/strategies/offchain/remote-vp.ts
Fix voting power parsing issue, when voting power returned by score-api for offchain space is a decimal number
Closes: #146
1. Connect to account with https://guest.so/#/shot.eth
2. Go to http://localhost:8080/#/s:safe.eth/proposal/0x1d65ca5270b4aa1efaa7b7ca4e17976a99b802efcf678ac2909eb836b1662a29
3. It should show the account voting power (2.5M) (Before, it was failing)
=> fix: fix invalid decimal voting power

apps/ui/package.json, apps/ui/src/components/Ui/Tooltip.vue, apps/ui/src/main.ts, apps/ui/src/style.scss, yarn.lock
Following #148 , this PR is migrating the Ui/Tooltip component from @floating-ui to vueTippy
1. Go to an element with tooltip
2. Hover on to
3. It should show the tooltip on hover
Style should be the same, only library has been changed
Before/After comparison
The UI/Tooltip component seems empty for now, will take more options as we add auto url later
=> refactor: move tooltip library to vueTippy

apps/api/package.json, yarn.lock
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/80
This is not something that can really be tested, but once we merge this and server syncs up we should no longer see duplicate writes (causing issues with unique constraints or settings getting out of sync).
=> fix: bump @checkpoint-labs/checkpoint to prevent duplicate writes

apps/ui/src/networks/offchain/api/index.ts
This PR updates the way we process offchain spaces treasuries so they show up in the UI.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/163
**There is limitation with Alchemy API rate limit and sometimes treasuries do not fully load still.**
1. Go to http://localhost:8080/#/s:balancer.eth
2. You can click through treasuries.
=> feat: display offchain spaces treasuries

apps/ui/src/components/SpaceTreasury.vue
This PR adds percentage change in total treasury value in 24 hours.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/167
1. Go there: http://localhost:8080/#/sep:0xeb8ea538c90d2e009460ed69add7025560e18481/treasury
2. % change is visible (unless it's really close to 0).
=> feat: display total treasury % change

apps/ui/src/composables/useEditor.ts
Fix issue where empty proposals were saved in the drafts, which was probably introduced when adding support for more voting type.
This PR add an additional check when detecting "empty" proposals, by taking into account the voting type and choices properties.
This PR also fix the current issue where it'll adda new draft instead of deleting it, when clicking on the "DELETE" icon in the drafts list
Closes: #183 
1. Go to an offchain proposals (http://localhost:8080/#/s-tn:wan-test.eth/create/ys2ab)
2. Fill some fields / change the voting type + fill in some choices
3. It should save the draft (confirm in the draft list)
4. Empty the form
5. The draft should disappear from the drafts list
NOTE: A draft is NOT empty only when:
- some of the string input are filled
- voting type is not basic …
=> fix(ux): do not save empty proposals in draft

apps/ui/src/components/ProposalResults.vue
After https://github.com/snapshot-labs/sx-monorepo/pull/166 there is an issue with displaying results bar:
Before:
After:
1. Vote on this space: https://testnet.snapshotx.xyz/#/sep:0xeb8ea538c90d2e009460ed69add7025560e18481
2. Results bar is properly aligned.
3. UI there wasn't impacted:
- [before](https://snapshotx.xyz/#/s:test.wa0x6e.eth/proposal/0x9623af39201332732f38227e75deced57fa4cc53f6bbb5380d0bdce40172d0e0) - [after](http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x9623af39201332732f38227e75deced57fa4cc53f6bbb5380d0bdce40172d0e0)
- [before](https://snapshotx.xyz/#/s:test.wa0x6e.eth/proposal/0x5ddbe81f1870a5154bd7b120bdc2c1755315157e7b230d38c74544ddd1ac62ef) - [after](http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x5ddbe81f1870a5154bd7b120bdc2c1755315157e7b230d38c74544ddd1a …
=> fix: center align results bar on proposal list

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/networks/starknet/actions.ts
You can now delegate Starknet tokens from UI.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/153
1. Go to space with Starknet delegation: http://localhost:8080/#/sep:0x8b08aa6cdaf0bc92bb9cc6844459b2fed94249af/delegates
2. OR set up your own (contract network Starknet, address `0x0782f0ddca11d9950bc3220e35ac82cf868778edb67a5e58b39838544bc4cd0f`, API URL: https://starknet-delegates.checkpoint.fyi/)
3. Get vSTRK (check linked issue for instructions).
4. Try delegating.
=> feat: support Starknet delegation from UI

apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/Modal/SendNft.vue, apps/ui/src/components/Modal/SendToken.vue, apps/ui/src/components/Modal/Transaction.vue, apps/ui/src/components/PickerContact.vue, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/helpers/stamp.ts, apps/ui/src/views/Editor.vue, apps/ui/src/views/Space/Treasury.vue
This PR adds space treasuries in address pickers when creating execution
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/164
1. Go to treasury: http://localhost:8080/#/sep:0x8b08aa6cdaf0bc92bb9cc6844459b2fed94249af/treasury
2. Start Send token or Send NFT modal.
3. Pick address, treasuries are listed.
4. Go to editor http://localhost:8080/#/sep:0x8b08aa6cdaf0bc92bb9cc6844459b2fed94249af/create
5. Pick execution strategy, open Send token, Send NFT, Send transaction modal.
6. Pick address, treasuries are listed.
=> feat: populate contacts from space treasuries

apps/ui/src/helpers/stamp.ts
Fix issue where ENS domain cache is being overwritten, and always return undefined for previously resolved domains
Closes: #197
1. Go to http://localhost:8080/#/s:aave.eth
2. The ENS domain should resolve for one of the proposals' author
3. Navigate to the space's proposals page from the sidebar
4. The same proposal's author with its ENS domain being resolved should also resolve on this page (previously, it only show address instead of resolving)
=> fix: fix ENS domain resolver cache being overwritten

apps/ui/src/components/FormProfile.vue, apps/ui/src/components/SpaceCover.vue, apps/ui/src/components/SpacesListItem.vue, apps/ui/src/components/Ui/InputStampCover.vue, apps/ui/src/views/Space/Overview.vue
Add a space fallback cover image, generated from the space avatar (using CSS)
Closes: #184 
NOTE: not using the `scale(1.5)` as suggested in the issue, since the blur is overflowing, and using a additional div to hide the overflow is messing up the position absolute on the explore page.
1. Go to a space without cover image
2. It should show a cover image generated from the space avatar, and looks like this
The explore page should look like this
=> fear(ui): add fallback space cover from space avatar

apps/subgraph-api/.gitignore, apps/subgraph-api/package.json, apps/subgraph-api/src/helpers.ts, apps/subgraph-api/tests/helpers.test.ts, package.json, yarn.lock
This also adds toChecksumAddress checksum as test subject, but this will be actually used in other PR to checksum all addresses in API.
1. Tests pass
=> test: add subgraph tests via matchstick-as

apps/subgraph-api/.gitignore, apps/subgraph-api/package.json, apps/subgraph-api/src/helpers.ts, apps/subgraph-api/src/mapping.ts, apps/subgraph-api/tests/helpers.test.ts, package.json, yarn.lock
Depends on https://github.com/snapshot-labs/sx-monorepo/pull/203
This PR changes how we store addresses at API to always use checksummed addresses which matches SX/hub.
Subgraph queries are case sensitive so we should use common format everywhere.
1. Run `yarn dev:full` (you might be getting rate limited).
2. Go to sepolia space you already voted on.
3. It shows you already voted.
=> refactor: format addresses with checksum

apps/ui/src/App.vue, apps/ui/src/composables/useAccount.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/types.ts, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Space.vue
Before all user votes were loaded for all enabled spaces. Now only single space votes will be loaded as needed.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/162
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/204
1. If you need to test EVM you need to run `yarn dev:full` as we need to format addresses on API.
1. Go to app, check networks - no votes are loaded unless on space/proposal page.
2. Go to proposal you voted on - you don't see button to vote.
3. Disconnect from Web3 wallet - buttons to vote show up again.
=> feat: only load votes per-space

apps/ui/src/components/ProposalResults.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/211
1. Not visible there: http://localhost:8080/#/s:shutterdao0x36.eth
2. Visible there: http://localhost:8080/#/s:shutterdao0x36.eth/proposal/0xfbd94f8b30df1581b0b7a8790ecb55cf13e260b075bb6a1d06c73aa22cbe768a
=> fix: hide shutter badge on on results page

apps/ui/src/composables/useWeb3.ts
Currently it's not formatted. If it ends up with odd number of digits it will fail to fetch spaces from subgraph.
Long term we probably shouldn't try to fetch EVM spaces with Starknet accounts, but for now let's keep addresess consistent while fixing the issue.
1. Sign in with Starknet account.
2. Go to http://localhost:8080/#/settings
3. Spaces you controll will be displayed.
=> fix: format web3 account address

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Proposal/Overview.vue, apps/ui/src/views/Proposal/Votes.vue, apps/ui/src/views/Space/Delegates.vue, apps/ui/src/views/Space/Treasury.vue
Here are the changes of the PR:
- Move percent background to left:
- Make delegates and treasury select bar scrollable:
Can try here: http://localhost:8080/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c/treasury
And here: http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/delegates
- Remove zap icon for voting power on proposal page
- Open new tab for delegate links
- Improve summary display:
Also fix an issue with AI summary where SX proposal are not visible
=> style: minor style improvements

apps/ui/src/helpers/utils.ts
Shorten proposal ID when it's not only an eth address, but also IPFS hashes
Closes: #205
1. Go to http://localhost:8080/#/s:ens.eth/proposals
2. Scroll to the oldest proposals
3. All IDs should be shortened
=> fix: shorten proposals ID with IPFS hash format

apps/ui/src/components/ProposalResults.vue
Closes: #227
Sort proposals results by weight, ~~when type !== basic~~ for all voting type
1. Go to http://localhost:8080/#/s:ens.eth/proposal/0x6ba81cd2997288cc49ae1b95921ec8f107e8ffb9733321d53d488e2b30710b86
2. It should show results in same order as https://snapshot.org/#/ens.eth/proposal/0x6ba81cd2997288cc49ae1b95921ec8f107e8ffb9733321d53d488e2b30710b86
3. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x46a984c60c16af8214d8a50dc964cdabfbb39fd57a5d1f9ad5ff62dca4e2f856
4. It should show results in for, against, abstain order
=> feat(ux): sort proposals results by weight

apps/ui/src/components/ProposalResults.vue
Closes: #222
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposals
2. Active basic proposals with shutter enabled will not show the shutter message anymore
=> fix(ui): fix shutter message appearing in proposals list

apps/ui/src/views/Proposal.vue
Moving voting power indicator within the "Cast your vote" section, to make sidebar more compact, also adding icons for both "Cast your vote" and "Results" sections.
**Before**
**After**
=> style: move voting power in cast your vote section

.changeset/calm-pens-leave.md, .changeset/sixty-otters-judge.md, apps/api/src/overrrides.ts, apps/mana/src/stark/herodotus.ts, apps/ui/src/views/Proposal.vue, packages/sx.js/src/clients/starknet/herodotus/index.ts, packages/sx.js/src/strategies/starknet/evmSlotValue.ts, packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts, packages/sx.js/src/strategies/starknet/utils.ts, packages/sx.js/src/utils/errors.ts, packages/sx.js/src/utils/index.ts
This PR updates Herodotus to use new indexer API and display message if Herodotus is not processed yet.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/154
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/207
**Note: Currently new indexer has CORS issue so all requests fail showing this message, waiting for fix from Herodotus.**
1. Run `yarn dev:full` (might be good idea not to run subgraph and set Sepolia start block later to prevent rate limits).
2. Create space with ozvotes/evmslotvalue strategy (can you this token: `0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4`, slot index 0 for EVM slot value, 8 for OZ Votes).
3. Create proposal.
4. It shows this message until confirmed.
Newer design:
New design:
Previous design:
=> feat: show info message if Herodotus voting power is not available yet on a proposal

apps/ui/src/components/TransactionsListItem.vue
Before it was only updated on initial render, so if you changed values in your transaction (for example value) it wouldn't be updated in the list.
1. Add send token execution there: http://localhost:8080/#/sep:0x8b08AA6CdAF0Bc92bb9cc6844459B2FED94249Af/create
2. Try editing it by updating value - preview updates with new value.
=> fix: make transaction item title computable

apps/subgraph-api/package.json, apps/subgraph-api/schema.graphql, apps/subgraph-api/src/ipfs.ts, apps/subgraph-api/src/mapping.ts
This is needed because in recent change of some values being checksummed and some not it ended up breaking execution selection.
This was already deployed, currently syncing.
1. Try creating proposal with execution, it should work.
=> fix: store all addresses in string fields to retain checksum

apps/ui/src/helpers/intercom.ts, apps/ui/src/views/Proposal.vue
Fixes suggested in https://github.com/snapshot-labs/sx-monorepo/pull/264#issuecomment-2043090206
- Sidebar to have padding-bottom of 88px
- Default padding on small devices
- Hide intercom messenger if screen width is less than `768` (same as `md`) - Because most of the proposal components are responsive with `md` 
- Go to http://localhost:8080/#/s:uniswapgovernance.eth/proposal/0xe7274e00eb2a084cdc3b7510a8b40aa303ac2d7944e9706ad090c974c76e71bf
| Before    | After |
| -------- | ------- |
| <img width="335" alt="Untitled 3" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/73752879-bcfb-41d1-ac59-095abad41b59"> | <img width="341" alt="Untitled 2" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/44938cb4-3f0e-43c3-9119-8476f6aecda0"> |
- Go to …
=> fix: Messenger overlap on proposal

apps/ui/src/components/Ui/Markdown.vue
Closes: #272
Add title bar to markdown code block to show language if available, and copy button
Copy button will now transform to check icon for 1s on click, instead of triggering flash notification
1. Go to any proposal with code block, e.g. http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0xf56083e1fcbdc5c9ad15d9e91f67a72b817bdf83f1589af8db20e27385db95e1
=> fix: better markdown code block UI

apps/ui/package.json, apps/ui/src/components/App/Sidebar.vue, apps/ui/src/components/Ui/Tooltip.vue
Unless recognizable avatar is used it's hard to tell which space is which on the sidebar without visting it manually.
This PR adds tooltips with space names.
1. Add space to favorites.
2. When hovering it in sidebar you see space name.
=> feat: add tooltips with space names on sidebar

apps/ui/src/components/ProposalExecutionActions.vue, apps/ui/src/composables/useExecutionActions.ts
There is too much logic in ProposalExecutionActions right now as we need to handle some non-standard actions (veto and queued proposals for Timelock, finalize for Axiom). This will get more complex with Starknet L1 execution as well.
It's not really ideal to create separate components for each execution type (at least now), so extracting that logic to composable is good first step.
1. Create proposal with execution (for example timelock and Axiom execution).
2. Entire flow works the same as it used to.
=> refactor: move execution actions to useExecutionActions

apps/ui/src/components/ProposalResults.vue, apps/ui/src/components/ProposalsListItem.vue, apps/ui/src/helpers/quorum.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts
Closes: #279 
Show quorum progress below proposal results, and in proposalListItem
On quorum of reject, the result progress bar only show progress of the rejection choice
NOTE: on active shutter proposals, the progress of all proposals using quorum of rejection will always be 0%, as choices are hidden until proposal is closed.
1. You can see some tests proposals with default and rejection quorum on http://localhost:8080/#/s:test.wa0x6e.eth
2. You can also create some proposals with default and rejection quorum, and see the progress after voting
=> feat: show quorum progress

apps/ui/src/components/EditorExecution.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/303
1. Go to space where you can create execution.
2. Create some execution and simulate it.
3. Edit it.
4. You can simulate it again.
=> fix: reset simulation state when execution is edited

apps/ui/src/App.vue, apps/ui/src/components/App/Topnav.vue
This PR fixes display of app nav on settings page.
Before:
After:
1. Go to http://localhost:8080/#/settings
2. Make window smaller
3. Open app nav via hamburger menu
4. Background is properly shifted.
=> fix: handle app nav on settings page

apps/ui/src/components/Ui/InputDuration.vue, apps/ui/src/views/Space/Settings.vue
Closes: #267
Fix an error where the space min voting period form always show a validation error when a max voting period is set
1. Go to a space settings
2. Set a max voting period and save
3. Try to edit the min voting period
4. It should show an error only if min voting period is greater than max voting period
=> fix: fix invalid voting period comparison

.changeset/fuzzy-onions-destroy.md, packages/sx.js/src/clients/starknet/starknet-tx/index.ts
It looks like fees are floating too much so two step estimation is likely to get outdated.
https://www.starknetjs.com/docs/guides/estimate_fees/#fee-limitation
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/304
1. Should be able to propose/vote on Starknet with local mana.
=> fix: overestimate fee when using nonce

packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts, packages/sx.js/src/strategies/starknet/utils.ts
Previously we just called getVotes on the contract, but if strategy was misconfigured (wrong slot index was specified) this wouldn't get caught.
With this change current voting power is computed from storage directly.
As a note, this uses 224 trace instead of 208 from OZ, as this is the what contracts support:
https://github.com/snapshot-labs/sx-starknet/blob/fe3c99f0e8e6210bfc1c2e423f9f0feb97a3a450/starknet/src/voting_strategies/oz_votes_storage_proof.cairo#L131-L134
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/301
1. VP gets computed on proposals list (as long as correct storage is used by OZ token).
=> feat: use real storage value to compute VP for ozVotesStorageProof

apps/ui/src/components/App/Nav.vue, apps/ui/src/components/Modal/Votes.vue, apps/ui/src/components/ProposalsListItem.vue, apps/ui/src/stores/users.ts, apps/ui/src/views/Proposal/Overview.vue, apps/ui/src/views/Proposal/Votes.vue, apps/ui/src/views/User.vue
Closes: #291 and #292
User profile should not be scoped by network
1. Visit any user profiles, such as  http://localhost:8080/#/profile/0xf9551c66995eD3Ff9bb05C9Fd7ff148Bd75dc99a
2. The user profile link should not include the network ID prefix anymore
3. User profile `proposal_count` and `vote_count` should be the sum of all counters on all enabled networks (offchain spaces still not returning this data, so always `0` for now)
4. User domain should be shown instead of address when available
5. Add links to /settings and /profile/CURRENT_USER in the My sidebar
=> feat: network agnostic user profile

apps/api/package.json, apps/api/src/writer.ts, yarn.lock
This enables faster initial sync via targetted preload.
1. Start Starknet API, should sync in around 6 minutes (Sepolia).
=> chore: bump @checkpoint-labs/checkpoint to 0.1.0-beta.34

apps/ui/src/components/IndicatorVotingPower.vue, apps/ui/src/components/Modal/VotingPower.vue, apps/ui/src/helpers/utils.ts
Closes: #309 
1. Go to http://localhost:8080/#/sn-sep:0x019fe8e10c15ced8c06a1052ab9632d6e4cfb0b447525a6779906b081d31f5d3/proposals 
2. connect wallet `0xeF8305E140ac520225DAf050e2f71d5fBcC543e7`
3. You should see voting power `~0`
4. Try clicking on voting power, you should see `~0` as voting power
Here are the screenshots to explain how it works on different proposals:
| Screenshots |
| -----------  |
| ![image](https://github.com/snapshot-labs/sx-monorepo/assets/15967809/8a814480-5b03-49ff-881c-f427bf1f12fc) |
| ![image](https://github.com/snapshot-labs/sx-monorepo/assets/15967809/4527562a-d0b3-44ac-98e5-956110572d22) |
| ![image](https://github.com/snapshot-labs/sx-monorepo/assets/15967809/da8da5c7-b50c-4c99-ad46-0648ced7c3ab) |
| …
=> fix: Max 2 decimals for voting power

apps/ui/src/views/Proposal/Votes.vue
Closes: #316
1. Go to http://localhost:8080/#/s:pistachiodao.eth/proposal/0xf93f1ac80e22cc930b1eef1d20bd34671ccc33b88b04695479c9de364451d77f/votes
2. Hover some vote choice
3. The tooltip should always be centered on the text, and matching the text length, instead of centered on the table cell
=> fix(ui): fix tooltip position not matching content length

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/views/Proposal/Votes.vue, apps/ui/src/views/Space/Leaderboard.vue
Closes: #326
Fix an issue affecting all placeholder message inside TABLE element.
1. Go to a proposal without votes
2. Go to votes table
3. The placeholder message should take the full width 
Do the same for space delegates and leaderboard page
=> fix(ui): fix wrong placeholder style

apps/ui/src/App.vue, apps/ui/src/style.scss
Closes: #329 
- Fix sliding when there is no content
- Remove unwanted style on `app`
- Go to http://localhost:8080/#/s:opcollective.eth/leaderboard
- Try to slide on where there is no content (below: "This space does not have any activities yet.") refer to video [here](https://github.com/snapshot-labs/sx-monorepo/issues/329) 
- Slider should open irrespective of where you slide
- Everything should work same as before
=> fix: Sidebar doesn't work where there is no content

.changeset/selfish-brooms-jog.md, apps/mana/src/stark/herodotus.ts, apps/mana/src/stark/networks.ts, packages/sx.js/src/clients/starknet/herodotus/index.ts, packages/sx.js/src/clients/starknet/starknet-tx/index.ts, packages/sx.js/src/starknetNetworks.ts, packages/sx.js/src/types/networkConfig.ts, packages/sx.js/src/utils/fees.ts
This PR adds `VITE_FEE_ESTIMATE_OVERRIDE` that can be used to override fees in `starknet-tx` and `herodotus` clients.
The fees are pretty high on Sepolia right now, over $4 to just propose on Sepolia. We could hardcode it to 10000000000000000 to be safe.
1. Uncomment mana filter from `yarn dev` script.
2. Run `STARKNET_SEPOLIA_FEE_ESTIMATE_OVERRIDE=10000000000000000 VITE_MANA_URL=http://localhost:3001 yarn dev`
3. You can propose/vote on Starknet spaces with EthSig/StarkSig.
4. Max fee is hardcoded in transaction.
=> feat: add STARKNET_FEE_ESTIMATE_OVERRIDE env to hardcode fee

apps/ui/src/components/IndicatorVotingPower.vue
Closes: #334 
Fix "Your voting power" tooltip persisting, after opening the voting power modal on mobile.
This is a know issue, and only way to fix this is to disable the tooltip for mobile device, like for the sidebar tooltip
1. Go to space overview on mobile
2. Tap on the voting power
3. It should not show the tooltip anymore
=> fix(ui): fix stuck tooltip after modal open on mobile

apps/ui/src/views/Landing.vue
Changes discord link in footer, refer to https://discord.com/channels/955773041898573854/1182427601046884352/1239002513873702933
1. go to landing page and click on discord link
=> fix: Change discord link in footer

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/views/Proposal/Votes.vue, apps/ui/src/views/Space/Leaderboard.vue
Closes: #339 #330 #145
Migrate tables to div for pages:
- votes 
- delegates
- leaderboard
Migrating to div will fix a few issues with table
1. Go to a proposal votes page
2. It should display data as before
3. The voting power background should display correctly on webkit engine (https://github.com/snapshot-labs/sx-monorepo/issues/145)
4. Go to the delegates and leaderboard page
5. It should display data as before
6. The 1px gap described in https://github.com/snapshot-labs/sx-monorepo/issues/330 should be fixed
=> refactor(ui): migrate table to div

apps/ui/src/helpers/connectors.ts
Closes: #345 
Fix an issue where connecting with Uniswap via WalletConnect result in "unsupported chains" error
This is due to WalletConnect connector still including Goerli chainID in its chain list, removing it fix the issue
1. Go to http://localhost:8080/#/
2. Connect via WalletConnect
3. Scan the QR code with your uniswap mobile application
4. It should prompt you to validate the signature, instead of showing the error message
=> fix: remove goerli from walletconnect chains list

apps/ui/src/components/SpaceTreasury.vue
Closes: #325
Fix an issue where execution strategy is not detected properly, due to different addresses casing
1. Go to [#/sep:0xbFF55fd2A671288316956A0Cae8f1d24BA7E5C9B/treasury](http://localhost:8080/#/sep:0xbFF55fd2A671288316956A0Cae8f1d24BA7E5C9B/treasury)
2. Send a NFT from the treasury
3. On proposal editor, the strategy should be selected by default in the execution section
=> fix: fix address comparison being case sensitive

apps/ui/src/composables/useAccount.ts, apps/ui/src/stores/followedSpaces.ts, apps/ui/src/views/My/Home.vue
This PR add support for loading voted indicator in timeline from all networks
1. Go to http://localhost:8080/#/home
2. It should list a mix of onchain and offchain proposals
3. It should show the voted indicator next to proposal title, when voted, for onchain and offchain proposals
=> fix: add missing voted indicator in timeline proposals feed

apps/ui/src/views/My/Home.vue
Closes: #353 
Fix `watch` action not being triggered on internal page navigation
1. Go to /explore
2. Navigate to /home via the Nav sidebar
3. It should load the home page content
=> fix: fix fetching not triggered on internal page navigation

apps/ui/src/views/My/Home.vue
Fix issue pointed out here https://github.com/snapshot-labs/sx-monorepo/pull/317#pullrequestreview-2068818017
where the "No proposals" message was being showed briefly on page load
1. Go to http://localhost:8080/#/home
2. You should see the LOADING icon until the proposals list are loaded and shown, without seeing the "No proposals" message
=> fix: fix "no data" message flashing on /home page load

apps/subgraph-api/package.json, yarn.lock
This seems to fix issue with running matchstick-as tests multiple times.
Before (at least on M1 mac) it would have failed if ran two times.
- Run `yarn test --force` multiple times.
- All pass.
=> chore: upgrade graph libraries

apps/subgraph-api/package.json, apps/subgraph-api/schema.graphql
When adding L1 execution for Starknet I forgot to add this field to subgraph API so it's breaking when querying proposals.
Subgraphs are already deploying with this change.
=> fix: add missing execution_destination field to subgraph

apps/api/src/ipfs.ts
We should handle execution_destination being missing properly, checking if it's undefined (and not properties).
=> fix: handle missing execution_destinations

apps/ui/src/App.vue
Closes: #361 
This PR fix the UI issue where the page scroll back to the top when opening a modal
1. Go to any page with a scroll and modal
2. Open the modal
3. Page should not scroll to the top
4. Any sticky element should stay visible
=> fix: fix scroll to top on modal open

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/stores/notifications.ts
This PR fix an issue where the `end_gte` filter passed to `loadProposals` is not universal for all chains, and only valid for offchain spaces, as onchain spaces uses `max_end` and `min_end` variant
This PR will use `max|min_end` everywhere variant inside the UI, and will do the "translation" only inside the networks not supporting it.
=> fix: fix invalid proposal end filter name

apps/ui/src/networks/offchain/api/index.ts
filters can be undefined so we need to handle it, otherwise requests without
filters will fail (for example loading on space).
1. Go to https://localhost:8080/#/s:0cf5e
2. Proposals load.
=> fix: handle missing filters

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/types.ts
This PR fix an issue where the list of followed spaces loaded from the offchain network API was always returned with networkID `s` (or `sn`).
This was the correct behavior until we refactored sequencer to also support onchain spaces.
With this PR, list of spaces from `loadFollows` will have the correct networkID
1. Follow an onchain space
2. Refresh the page
3. Before the fix: onchain space does not appear in the sidebar, after the fix, it should appear in the sidebar
Having the offchain network returning a mix list of onchain and offchain spaces is not optimal, and confusing. This solution is temporary, until we implement https://github.com/snapshot-labs/sx-monorepo/issues/359
=> fix: fix followed space list not returning correct space network

apps/ui/src/stores/followedSpaces.ts
Closes: #375
Load sidebar followed spaces only once all are available
1. Connect to your account, and go to space page you're following
2. Refresh the page
3. On page load, it should show the all the spaces at once (and not the space you are on first)
4. On account switch and login, it should do the same
=> fix: load sidebar spaces once all are available

apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts
This PR fixes calling `clone` on `undefined`, resulting on an uncaught error
This PR edit the `loadProposals` signature, to explicitly state that `filter` can be `undefined`, and add fallback when cloning it
1. Go to http://localhost:8080/#/s:ens.eth
2. Proposals should load
=> fix: fix cloning of `undefined`

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts
Closes: #366 #373
This PR revert back the offchain spaces loading to use the `Space` endpoint, instead of  `Ranking`, due to them not being swappable, causing all `loadSpaces` from offchain to always load the top X spaces, and not honoring the `id_in` filter.
This was causing:
- the follow list to load only spaces if they're in the top 20
- the "My Spaces" (http://localhost:8080/#/settings) to always list the top 20 spaces, and not the user's own space
This PR will use the `ranking` graphql endpoint only when no `id_in` filter is passed to `loadSpaces`, and used as extra, and not replacement
1. Your follow list should list all 25 spaces
2. The explore page should load space sorted by popularity
=> fix: fix offchain spaces loading using wrong graphql queries

apps/ui/src/composables/useSpaces.ts
Closes: #378
This PR fix the issue where the list of spaces in the Explore page is not reset on mount, leading to spaces repeated n times
1. Go to http://localhost:8080/#/explore
2. Navigate away from this page
3. Navigate back to the explore page
4. The list of spaces should be back to only the first 20 spaces, and do not have duplicates
=> fix: fix duplicates spaces while loading explore page on internal navigation

apps/ui/src/components/ProposalResults.vue
If more than 6 results are there "Others" button will be visible to summarise options that you can expand.
_There is special case if there are 7 results - last option won't be collapsed into "Others" because it would basically hide single choice and add extra friction to see it._
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/233
1. Go to http://localhost:8080/#/s:cvx.eth/proposal/0xc8666fbf22c09c9eb0e21ab961814f43ee99aaff14a96b23351c633ce9fae8e7
2. You see "Others" summary.
3. You can expand votes on click.
=> feat: collapse results into "Others" if more than 6 are there

apps/ui/src/helpers/connectors.ts
Same changes as in https://github.com/snapshot-labs/snapshot/pull/4700
- chains = [] to support all networks while connecting using Wallet-connect
- move `eth_signTypedData_v4` method to optional
Closes: #
1. Vote/Create proposals with Safe on other networks than mainnet (using wallet connect) 
Before the fix: it should throw invalid network error
After the fix: should be able to vote/create proposals
=> fix: Walletconnect support for multichain wallets

apps/ui/src/components/App/Topnav.vue, apps/ui/src/composables/useSpaces.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/types.ts, apps/ui/src/views/My/Explore.vue
Closes: #389 
This PR add the ability to search for a space
- The search input should be pre-populated on page load with the query string from the url (`q=xxx`) if available
- Use different placeholder for space and proposal search
- Explore page now have a message when no spaces results
- Move explore page protocol to query string in the url (`?p=snapshot|snapshotx`)
- Using the topnav searchbar from the "My" pages should redirect to the explore page, and show a list of spaces matching the search results
1. Go to http://localhost:8080/#/home
2. Search for a space using the top searchbar
3. It should show your results in the /explore page
4. You can switch protocol, without to search for the keyword again
5. The URL should reflect your search filters, reloading the page will keep the same …
=> feat: add support for spaces search

apps/ui/src/components/ProposalResults.vue
Closes: #398
This PR hides the results progress bar on active proposals which you have voted, and with shutter and quorum enabled
1. Create a proposal on a space with shutter and quorum
2. Vote on the proposal
3. In the space proposals page, the proposal should appear without the progress bar
=> fix: hide result progress bar on ongoing shutter proposal

apps/ui/src/components/SpaceCover.vue, apps/ui/src/components/SpacesListItem.vue, apps/ui/src/components/Ui/InputStampCover.vue, apps/ui/src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/stamp/issues/172
Only 1 change: increasing the fetched image height.
The other changes are just CSS cleaning and DRY-ing 
1. Go to the /explore page, and a onchain space with cover image (ens, nostra)
2. The space cover dimension should be better
=> fix(ui): improve space cover dimensions

apps/ui/src/components/Ui/Loading.vue
SVG animations should work on Safari, but it doesn't for some reason on our Loading SVG, CSS animations will be more reliable.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/408
1. Open http://localhost:8080/#/sn-sep:0x01c63c00ce530de98ff6469bef06271231bc8a82ffc4122f9ec3ada7de23d68a on Safari.
2. Loading icons work as they should.
=> refactor: use CSS animations instead of SVG animations

apps/ui/src/components/IndicatorVotingPower.vue, apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/views/Proposal/Votes.vue
This one is used for VP specifically using predefined rules of formatting. It will use maximium of 3 decimal digits (for numbers < 1000) or 1 otherwise.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/405
1. Go to http://localhost:8080/#/s:aave.eth/proposal/0x364de11d3a298f2c76721a8926cb32823cc29d0a95eadecbc0a98c628a38194b/votes
2. Big VP values have maximum of 1 decimal digit.
=> feat: add special _vp formatter

apps/ui/src/style.scss
Closes: #411
1. Go to a form with textarea
2. Trigger an error on the textarea
3. It should have 1px red border, and red label text
=> fix: fix error style on textarea

apps/ui/src/networks/starknet/index.ts
Previously any failure in fetching receipt would result in waitForTransaction failing after 20 attempts. This means non-related errors (like rate limits) would cause it to fail, even though transaction has completed.
This PR changes this behavior, it will only fail if:
1. Transaction was missing for 60 attempts (2 minutes).
2. It was reverted.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/409
1. Create Starknet space.
=> feat: only fail waitForTransaction if it's missing or reverted

apps/ui/src/components/ButtonFollow.vue, apps/ui/src/stores/followedSpaces.ts, apps/ui/src/views/User.vue
This PR disable features not supported by starknet wallet (due to sequencer not supporting starknet addresses yet):
- Hide all follow/unfollow space button
- Hide the edit user profile button for starknet user
- Skip loading follow list
1. Log in with a starknet wallet
2. Go to your user profile page
3. The "EDIT" button should not appear
4. Go to any spaces or /explore page
5. The "FOLLOW" button should not appear
=> fix: disable features not supported on starknet wallet

apps/ui/src/stores/users.ts, apps/ui/src/types.ts
- Get ENS names even if user doesn't exist on hub
- Load default object in such case
Closes: #429 
1. Go to home page using env `VITE_ENABLED_NETWORKS=s-tn,sep,sn-sep` 
2. Login with a wallet that doesn't have a profile on snapshot testnet 
3. After the fix, you should see ENS name 
4. <img width="264" alt="Untitled 2" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/f4648cdd-c689-4c67-a1c1-0fb309ca5b9d">
=> fix: Get ENS names even if user doesn't exist on hub

apps/ui/src/helpers/utils.ts, apps/ui/src/views/Space/Overview.vue
- Don't show the edit profile button if wallet is not connected
Closes: #428 
1. Go to any space without connecting wallet, you should not see edit profile button after the fix
=> fix: Don't show edit profile button if wallet is not connected

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/stores/users.ts
- Fetching names is already handled at https://github.com/snapshot-labs/sx-monorepo/blob/2041534372a4393b0858bee74daae928851c2998/apps/ui/src/stores/users.ts#L45 so we can remove this duplicate call
Closes: #432 
1. Go to https://snapshot.box/#/
2. Connect with `0xeF8305E140ac520225DAf050e2f71d5fBcC543e7` 
3. Open network tab in browser console. notice that we are calling stamp twice to get same address 
4. <img width="712" alt="Untitled 6" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/ffbc47b7-a6ed-4359-a905-dc2c05f9d0da">
5. If the user is already having a profile on hub, use `VITE_ENABLED_NETWORKS=s-tn`
=> fix: Remove duplicate calls to stamp

apps/api/src/writer.ts
Fix wrong ids in leaderboard and votes table
Closes: #437 
1. Clone to local, Index again
2. you should not see [Object] anymore
=> fix: Wrong ids in leaderboard and votes

apps/api/src/ipfs.ts, apps/api/src/schema.gql, apps/api/src/writer.ts, apps/subgraph-api/package.json, apps/subgraph-api/schema.graphql, apps/subgraph-api/src/ipfs.ts, apps/subgraph-api/src/mapping.ts, apps/subgraph-api/subgraph.yaml
This PR adds indexing for vote reason on both EVM and Starknet APIs.
1. Run `yarn dev:full`.
2. Wait for everything to get indexed (you can check _meta block on APIs to see progress or logs for Checkpoint).
3. Run query below on both [Checkpoint](http://localhost:3000/) and [Subgraph](http://localhost:8000/subgraphs/name/snapshot-labs/sx-subgraph/graphql).
4. Some votes should have reason.
```gql
{
votes {
metadata {
reason
}
}
}
```
=> feat: index Vote reason

apps/api/src/schema.gql, apps/api/src/utils.ts, apps/api/src/writer.ts
Int is not big enough to store all our values.
1. Run `yarn dev:full`.
2. Run following query at [sx-api](http://localhost:3000/).
3. Values are returned as strings.
```gql
{
spaces {
proposal_threshold
}
}
```
=> feat: store proposal_threshold as BigDecimal

apps/ui/src/components/Modal/VotingPower.vue
This PR fix an issue where all the strategy name inside the voting power modal are shortened, when not a valid onchain startegy.
This leads to shortening of all offchain strategies name.
This PR will shorten the strategy name only if it's an address, and truncate it if not fitting on same line
1. Go to http://localhost:8080/#/sn:0x071977084d73002fed430d99108da39d241b900099ccc2a4cdcb7d5041d851d2/proposals
2. Open the voting power modal
3. It should shorten the second strategy name
4. Go to http://localhost:8080/#/s:apecoin.eth/proposals
5. Open the voting power modal
6. It should not shorten the strategies name
=> fix: shorten the strategy name only if it's an address

packages/sx.js/src/starknetNetworks.ts, packages/sx.js/src/strategies/starknet/evmSlotValue.ts, packages/sx.js/src/strategies/starknet/index.ts, packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts, packages/sx.js/src/strategies/starknet/utils.ts, packages/sx.js/src/types/networkConfig.ts, packages/sx.js/test/unit/strategies/starknet/ozVotesStorageProof.test.ts
This PR solves issue with `Timestamp not cached` being thrown when waiting for EVMSlotValue/OZVotesStorage strategies.
Previously we used Herodotus API to read block number for given timestamp. This is not ideal because it doesn't actually mean that this mapping is already available on the network (because mana needs time to process it and create transaction out of it).
This commit removes dependency on Herodotus API on UI. Now mapping timestamp to block number is done on strategy contract directly. If it resolves it means that it will also be available for contract when casting a vote or computing VP. If it's not available we are marking it as NOT_READY_YET so UI displays appropriate message.
1. Create new proposal that uses EVMSlotValue/OZVotesStorage.
2. Message tells you that you have …
=> fix: use contract to map timestamp to block number

apps/ui/src/views/Settings/Spaces.vue
Closes: #390
This PR fix an issue where the "There are no spaces here." message is flashing briefly on http://localhost:8080/#/settings page load, due to the user being empty on page load.
Also adda fix to refresh the space list on account change
1. Connect to your account
2. Go to http://localhost:8080/#/settings
3. You should not see the message "There are no spaces here." on page load
=> fix: do not flash "No spaces" message while loading spaces

apps/api/src/overrrides.ts, apps/api/src/writer.ts, apps/ui/src/stores/proposals.ts, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Proposal/Overview.vue
This PR adds three changes related to handling ERC20Votes strategies
- When proposal is pending `snapshot` won't be passed to `getVotingValue` - instead live value will be computed (this would cause VP fail to load, due to timestamp in the future).
- Proposals now have `created` timestamp derived from proposal metadata meaning that it will have accurate timestamp (eliminating possibility of proposal starting before it's created) (https://github.com/snapshot-labs/sx-monorepo/issues/413)
- Proposals that use erc20votes strategies will have minimum of 10 minutes of voting delay applied to prevent voting on proposals in the same block it was created. This is only UI enforced limitation, if someone tries to vote at contract level it will fail.
Closes: …
=> feat: add erc20votes related workarounds

apps/ui/src/components/App/Nav.vue
This PR removes the leaderboard link from offchain spaces sidebar navigation; offchain leaderboard is not ready yet on the API side, and is always showing nothing
1. Go to an offchain space
2. The leaderboard link should be gone from the sidebar menu
3. Go to an onchain space
4. The leaderboard link should still be there
=> fix: hide leaderboard link from offchain space menu

apps/ui/src/composables/useWeb3.ts
Closes: #450
This PR fix the issue where the Account button on the page top right is stuck on the `loading` state after cancelling a wallet change action.
1. Connect to your wallet
2. Open the account modal, then click on the "Change wallet"
3. Choose WalletConnect or starknet
4. When the walletConnect modal open, close it
5. The Account button should not have loading state
This fix does not work on Coinbase wallet, as its modal is buggy, and can not be closed
=> fix: reset the account button loading state on wallet change cancel

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/composables/useDelegates.ts
Closes: #455 
Use percentage format similar to the leaderboard and user profile
1. Go to http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/delegates
2. You should see the difference in the percentage format
| Before    | After |
| -------- | ------- |
| <img width="746" alt="Untitled 2" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/b7b0aab0-22c0-40c0-a5c6-a181b907e65b">  | <img width="742" alt="Untitled 5" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/a3301ff4-b441-4a4c-a528-3e31194de078">  |
| <img width="771" alt="Untitled 4" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/35b6f125-655e-4e6e-8e2a-35611c2ab235">| <img width="769" alt="Untitled 5" …
=> fix: format percentage values in delegates page

apps/ui/src/components/Modal/VotingPower.vue, apps/ui/src/networks/starknet/constants.ts, apps/ui/src/networks/types.ts
Closes: #434
Fix an issue where the explorer url for a voting power strategy is on the wrong network
1. Go to http://localhost:8080/#/sn-sep:0x0141464688e48ae5b7c83045edb10ecc242ce0e1ad4ff44aca3402f7f47c1ab9/proposals or http://localhost:8080/#/sn:0x071977084d73002fed430d99108da39d241b900099ccc2a4cdcb7d5041d851d2/proposals
2. Open the voting power modal
3. All links to the explorer should use the same network (etherscan/starkscan) as the space, but storage proof strategies (which will always use etherscan)
=> fix: fix wrong network explorer url for strategies

apps/mana/src/stark/herodotus.ts
We should use snapshot specific mainnet APIs that are frozen.
=> chore: update Herodotus mainnet API urls

apps/ui/src/components/TransactionsListItem.vue, apps/ui/src/helpers/__snapshots__/osnap.test.ts.snap, apps/ui/src/helpers/osnap.test.ts, apps/ui/src/helpers/osnap.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/networks/offchain/index.ts, apps/ui/src/types.ts, apps/ui/src/views/Proposal/Overview.vue
This PR adds display of oSnap execution in the proposal.
oSnap proposals can have multiple executions (each for different proposal), but for now this PR merges all of those together, just adding necessary conversion to UI-native format.
Those would be separated once https://github.com/snapshot-labs/sx-monorepo/issues/138 is being worked on.
1. Run `VITE_ENABLED_NETWORKS=s-tn yarn dev`.
2. Check this proposal: http://localhost:8080/#/s-tn:0cf5e.eth/proposal/0x006df59eed550a3daa6078cb41c0f584a1fd6bcc517a2e608fb1ff57d34e0a12
=> feat: display oSnap execution in proposal

apps/ui/src/views/Network.vue
- Replace Twitter images with IPFS
- Remove scroll on networks images section (similar to http//:snapshot.org/#/network)
1. go to `/#/network` 
2. it should now use new ipfs URLs
3. on mobile, it should not add a scroll horizontally
=> fix: Replace with IPFS images

apps/ui/src/components/SpaceTreasury.vue
On the all spaces' treasury page, the `loadBalance()` call is triggered 3 times, with exactly the same arguments, since in addition to the main treasury page, it's also called in the sendToken and stakeToken modal.
This quick fix removes the unnecessary duplicates calls, by avoiding mounting the stakeToken and SendToken modal when not relevant.
Note: This is just a quick fix, we will still have duplicated calls when all modals are mounted, a better long term solution would be to have a global variable on the `useBalance` composable.
This will hopefully solve the 429 issue we have on https://github.com/snapshot-labs/sx-monorepo/issues/258
1. Go to any tresuries, like http://localhost:8080/#/s:balancer.eth/treasury
2. In the network tab of the dev console, you should only see one call to …
=> fix: load treasury asset balance only when necessary

apps/ui/src/components/SpaceTreasury.vue
Closes: #468 
This PR will show the "Stake with Lido" button only on Ethereum and Sepolia treasuries.
1. Go to http://localhost:8080/#/oeth:0x2EF7E7CF469f5296011664682D58b57D38a3c83f/treasury
2. It should not show the "Stake with Lido" button next to the ETH asset
3. Go to an space with Ethereum treasury
4. It should show the "Stake with Lido" button next to the ETH asset
=> fix: disable lido staking on non-eth network

apps/ui/src/composables/useWeb3.ts
loadProvider call is important for app functionality. It shouldn't be interrupted by fetching user (due to bugs or just network issues).
=> fix: catch fetchUser failures in loadProvider call

.changeset/large-snails-exercise.md
We are currently only bumping patch version to stay at 0.1.x
=> chore: only bump sx.js as patch

apps/ui/src/networks/common/graphqlApi/index.ts
If execution has no transactions executions array should be empty. Right now every proposal has empty execution.
1. Go to proposal without execution on SX: http://localhost:8080/#/sn-sep:0x012f384aacce933c2a346ade9a6c2918ece850b04db54efbf716c1a9fcb344da/proposal/5
2. It has no execution.
3. Proposals with executions still do (you need to enable `s-tn` network): http://localhost:8080/#/s-tn:0cf5e.eth/proposal/0x18b4c85fb3dba579b2714a3fcdba5ea96088f9f0a51f02002e81cc39a589d674
Before:
After:
=> fix: hide empty execution for SX proposals

apps/ui/src/style.scss
Closes: #493 
This PR removes the extra margin on textarea, inside the composer editor
1. Go to a proposal creation page
2. There should be not extra space between the textarea and the editor toolbar
3. There should be a gradient on top, when scrolling overflowing textarea
4. Go to any other textarea like the space creation
5. The textarea should remain the same
=> fix(ui): fix extra margin on textarea top inside editor

apps/ui/src/networks/evm/index.ts
For 3 weeks we couldn't deploy our subgraph on sepolia due to some issue on TheGraph. This means we are lacking some updated (reason is not indexed). This PR replaces official TheGraph's studio subgraph with our own `graph-node` deployed one. 
1. Can access Sepolia spaces (http://localhost:8080/#/sep:0x5559e6c038fD0494277ac85ab6576843A6d0187b)
2. API supports reason for votes: https://subgraph.snapshot.org/subgraphs/name/snapshot-labs/sx-subgraph/graphql?query=%7B%0A++votes%28where%3A+%7Bmetadata_%3A+%7B%7D%7D%29+%7B%0A++++id%0A++++metadata+%7B%0A++++++reason%0A++++%7D%0A++%7D%0A%7D
=> feat: use self-hosted subgraph for sepolia

apps/ui/src/composables/useAccount.ts
When re-loading the connected users' votes again for the same space, the `votes` object will be cleared before the API requeste, then re-populated again with the results.
This creates some flashing on the UI, where the state of an item where the user has already voted will flash briefly to "Not voted" state while the API request is fetching.
This PR will clear the local votes object only for guest user, connected user votes will just overwrite the existing one (removed the object concatenation, as we're just loading and saving in the memory votes from a single space)
=> fix: avoid user votes flashing on load

apps/ui/src/components/Modal/VoteReason.vue, apps/ui/src/components/Modal/Votes.vue, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Proposal/Votes.vue
This PR fetch the vote reason from the API, and show it on the proposals' vote page, following the figma here https://www.figma.com/design/hmHTau1Y1KYzrBBKLQr5QV/%23design?node-id=1243-10592&t=zNyM96TSGyLdmPjt-0
- Votes page column order change, to have the choice column just after the voter
- Choice column is the widest one now
- Reason is shown below the choice, if available
- Basic vote choice UI has changed for smaller icon+text
- Clicking on the choice will open the vote reason modal when reason exists
- Various UX/UI fixes on the votes pages and votes modal
1. Go to a basic choice proposal: http://localhost:8080/#/s:apecoin.eth/proposal/0xf0ccdfb38ea5bee47e5f3f5ac83d5d9ecbeb605e328001c0ab4c6df7e91557e3/votes
2. It should show the basic choice with the new UI, as well as reason
3. …
=> fix: show vote reason

apps/ui/src/components/App/Sidebar.vue, apps/ui/src/components/IndicatorVotingPower.vue, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/components/Ui/Tooltip.vue
Closes: #487 
Disable tooltip on mobile globally, instead of case by case
1. Navigate the site with a mobile devices
2. Click on button such as follow space, create new proposal, etc ... will not open the tooltip anymore
=> fix(ux): disable tooltips on touch devices

apps/ui/src/components/ButtonFollow.vue, apps/ui/src/views/Proposal/Overview.vue
Use the `loading` prop from the `UiButton` for the button's loading state
1. Go to a space
2. follow a space
3. the button should show a loading indicator while switching state
4. Go to a proposal
5. Click on the AI summary icon
6. Button should switch to the loading state while loading the summary
=> fix(ui): use loading props from UiButton for the loading state

apps/ui/src/helpers/utils.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/views/Proposal/Overview.vue
closes #527 
- Remove `math.floor` on https://github.com/snapshot-labs/sx-monorepo/blob/master/apps/ui/src/networks/offchain/api/index.ts#L194-L195  which is ignoring decimal values coming from off-chain proposals (for example values like `0.23` or `10.23`
- On proposal page we should still handle `BigInt` https://github.com/snapshot-labs/sx-monorepo/blob/master/apps/ui/src/views/Proposal/Overview.vue#L388-L389 so I have a create a new function `toBigIntOrNumber` which can both bigInt and decimals
1. You should be able to see results on http://localhost:8080/#/s:fabien.eth/proposal/0x476a51fa0bdd939649ce8208bf976b7057836836d9a4aeefa4ed2e466c0055a2
2. You should be able to see executable actions on proposals with executions same as before
=> fix: Results percentage for offchain proposals

apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/types.ts
Our types are broken and those are actually strings. We need to fix those, but it will require quite a bit of refactoring. https://github.com/snapshot-labs/sx-monorepo/pull/529/files#r1691071502
1. This proposal is passed http://localhost:8080/#/sn:0x05ea5ef0c54c84dc7382629684c6e536c0b06246b3b0981c426b42372e3ef263/proposal/3
=> fix: use BigInt to compute proposal state

apps/ui/src/views/Proposal/Overview.vue
Remove extra `<Loading>` indicator inserted probably by an improper merge conflict resolution
=> fix(ui): remove extra loading icon

apps/ui/src/views/Proposal/Votes.vue
Closes: #528
Fix the votes filter dropdown being hidden
1. Go to https://snapshot.box/#/sn:0x05ea5ef0c54c84dc7382629684c6e536c0b06246b3b0981c426b42372e3ef263/proposal/3/votes
2. The choice filter dropdown should appear on click
=> fix(ui): fix the votes filter dropdown being hidden

apps/ui/src/components/ProposalResults.vue
Closes: #515
- Add voting power beside each choice
1. Go to different proposals, and you should see total voting power on each choice of result
2. http://localhost:8080/#/s:safe.eth/proposal/0x8d97075eabfdf3fb9f43f3b490e8e5a7326d77bee919b78543621e36e5b2d233
3. http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50/proposal/1/
4. http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50/proposal/1/
=> feat: show total choice voting power in proposal results

apps/ui/src/components/Ui/InputStampCover.vue
Regression from: https://github.com/snapshot-labs/sx-monorepo/pull/531
1. Go to http://localhost:8080/#/create
2. Avatar is shown at the bottom edge of cover (previously it was in the center).
=> fix: make StampCover button block

apps/ui/src/composables/useWeb3.ts
Closes: #541
This PR adds and removes events to auth provider properly:
- add events to same provider only once
- remove events on logout
1. Add some `console.log()` to useWeb3 newly added functions
2. Log in, change account, log out
3. the events should be attached only once, and not again when changing account
4. the events should be cleared on logout
=> fix: add and remove events to provider properly

apps/ui/src/components/Modal/VoteReason.vue
Closes: #533 
Enable links in the modal reason
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0xa07fcb08c8f7623819cf432d8f6b13e6427147e6a36657fbf7e79ee2442a5eb8/votes
2. Open the reason modal 
3. the url should be clickable
=> fix(ux): enable link in the reason modal

apps/ui/src/components/PickerContact.vue, apps/ui/src/components/PickerToken.vue
After converting elements to button tokens lost full-width property and alignment.
1. Go there: http://localhost:8080/#/sn-sep:0x04d43d2fcc5dc1e0172c8fab38a2142d55336edac22a97f5503a72d37e18e252/treasury
2. Click on Send Token button -> open token list.
3. It looks good.
4. Try contact picker as well.
After:
Before:
=> fix: make picker items full-width and start-aligned

apps/ui/src/components/Ui/Markdown.vue
It was unscoped because it would have not been applied on children. But this can be enforced by usage of :deep() selector.
1. Go to some proposal: http://localhost:8080/#/s:uniswapgovernance.eth/proposal/0xc2eed288ba61241dd86928eff15b7c8c9622168fc4b435657f58dda8ce285d13
2. It looks like it used to.
3. Would be good to test it on some proposal that has super complex formatting, but I couldn't find anything.
=> chore: scope markdown-body CSS class

apps/ui/src/components/SpaceTreasury.vue
Closes: #564
Fix the missing `.value` when reading the computed `isReadOnly` variable.
Also applied some DRY, so we centralize the decision to enable the "Stake with lido" button or not with the `hasStakeableAssets` property.
1. Go to http://localhost:8080/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/treasury
2. The stake with lido button should appear
3. Clicking on the button should open the modal
4. Go to a space with a readonly ETH treasury
5. The button should not appear
6. Go to a space eth space with a trasury with an ETH token, not on the eth network (such as optimism)
7. The button should not appear
=> fix: fix readOnly state not being read as reference

apps/ui/src/composables/useDelegates.ts
Closes: #563 
Fix an issue where the delegates grapqhl query is failing when requesting https://api.studio.thegraph.com/proxy/23545/delegates/version/latest , due to the schema expecting user as `Byte` type, instead of `String`.
`user` filter will be reinstated when the schema will be fixed, by accepting the String type for user.
1. Go to http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/delegates
2. It should show delegates from both Starknet and Ethereum
=> fix: remove user in delegates query

.changeset/ninety-dolphins-behave.md, packages/sx.js/src/clients/offchain/ethereum-sig/types.ts
Closes: #555 
This PR adds support for user space statement edition from a starknet account.
This change was missed from the previous PR as the user statement and starknet support PRs were opened in parallel.
1. Connect with a starknet account
2. Go to a your profile on a space (e.g. http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/profile/YOUR-ADDRESS)
3. Edit and save the statement
4. It should ask to sign the create alias message if not already exist
5. It should save and show the edited statement
=> feat: support editing statement from a starknet account

apps/ui/package.json, yarn.lock
This is continuation of #538
Instead of fixing the issue from sx side, we fixed the issue on the lock package
- Follow the same steps described in https://github.com/snapshot-labs/lock/pull/114
TLDR: instead of seeing an invalid connected state, it should just show the "Connect button" as if you're unlogged when metamask is locked on subsequent page refresh.
=> chore: update lock package

packages/sx.js/src/strategies/evm/merkleWhitelist.ts, packages/sx.js/src/strategies/starknet/merkleWhitelist.ts
Because of incorrect types we were actually returning strings instead of bigints. This became an issue when adding those values together as instead of adding VPs we were concatenating them.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/492
1. Apply following patch to mock address and show VP in the UI on closed proposal.
2. Go to http://localhost:8080/#/sn:0x071977084d73002fed430d99108da39d241b900099ccc2a4cdcb7d5041d851d2/proposal/15
3. You should see 110.4 VP (instead of 1.1k).
```diff
diff --git a/apps/ui/src/views/Proposal.vue b/apps/ui/src/views/Proposal.vue
index baac6cce..eea11109 100644
--- a/apps/ui/src/views/Proposal.vue
+++ b/apps/ui/src/views/Proposal.vue
@@ -78,7 +78,7 @@ async function getVotingPower() {
proposal.value.strategies, …
```
=> fix: return merkleWhitelist VP as bigint

apps/ui/src/style.scss
textarea gradient is currently overlapping with the border. 
It is not obvious due to border color, but it is when the textarea is errored
1. Go to any textarea, like your profile
2. Fill the textarea to trigger an error
3. You should not see the gradient overlapping the border
=> fix(ui): do not overlap the gradient with border

apps/ui/src/assets/icons/stake.svg, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/components/TransactionsListItem.vue
Closes: #576 
- Adjust the given image to be visible on both themes
- Change the icon on the treasury page and transactions page
| Before    | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/df369739-b83f-4c79-b050-bbcc0b724b36)  | ![image](https://github.com/user-attachments/assets/778fa0c9-f6a8-4440-96d4-b14333019151)   |
| ![image](https://github.com/user-attachments/assets/3b4470b4-d61d-48ef-a6b6-011d8c04dd2e) | ![image](https://github.com/user-attachments/assets/98a5187b-7db6-4ec2-8db5-1ec35bc86473) |
In light theme:
1. Go to http://localhost:8080/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/treasury
2. You should see new icon
3. Click stake button and enter a random value
4. It should redirect to new proposal page and in the bottom you should …
=> fix: Change staking icon

apps/ui/src/components/App/Topnav.vue, apps/ui/src/components/Breadcrumb.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/568
1. Go to any space page http://localhost:8080/#/sn:0x05ea5ef0c54c84dc7382629684c6e536c0b06246b3b0981c426b42372e3ef263
2. you should see space logo
3. <img width="787" alt="Untitled 4" src="https://github.com/user-attachments/assets/50a6127c-0922-4f1a-a020-ad8919152ef9">
4. The proposal should still show logo without search bar
5. <img width="769" alt="Untitled 5" src="https://github.com/user-attachments/assets/eb8715fd-ce1f-4e69-b2a6-59f16a289547">
6. Landing page should still show snapshot logo
7.  <img width="656" alt="Untitled 6" src="https://github.com/user-attachments/assets/c60e2b2c-0699-415c-8a23-9691ab06161d">
8. settings page should still show logo like before
9. <img width="786" alt="Untitled 7" …
=> style: add space breadcrumb on space pages

apps/ui/src/views/Editor.vue
Currently our redirect is not stable (it just goes back), so you might end up at treasury page, overview, proposals page, previous draft etc.
This will make it always redirect to proposals page.
1. Create proposal.
2. You get redirected to proposals page.
=> feat: always redirect editor to proposals page

apps/ui/src/App.vue
We reset WalletConnect transaction when modal is closed, right now handleTransactionAccept is async so it would be reset before createDraft returns. Because of this spaceKey.value was already reset when we tried to navigate to it.
Regression from https://github.com/snapshot-labs/sx-monorepo/pull/512
1. Go to space with treasury configured (has to be on-chain currently: http://localhost:8080/#/sep:0xfa463A2Bdd8d27f1b0eA99270c3c4Bb3A7B2ADeF/treasury)
2. Connect via WalletConnect (in treasury section) and connect to UniSwap.
3. Initiate transaction on UniSwap (for example swap ETH to WETH).
4. Accept transaction on SX-UI.
5. Proposal opens and execution is visible.
=> fix: cache spaceKey before calling createDraft

apps/ui/src/components/Modal/SendToken.vue, apps/ui/src/components/Modal/StakeToken.vue, apps/ui/src/components/Ui/InputAmount.vue, apps/ui/src/helpers/validation.test.ts, apps/ui/src/helpers/validation.ts
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/583
This PR adds new `UiInputAmount` that can be used to input numeric amounts, but without drawbacks of using number input for it:
- Because it's no longer number it doesn't get converted to exponential form (for example in StakeToken modal output value would be displayed as `1e-7`).
- Similarly when entering small value like `0.000000000000001` and triggering re-render, for example by going to contact picker and back it would be turned to exponential form.
- `UiInputAmount` value has consistent type (always string), where `UiInputNumber` could have either `string` (when input is empty) or `number`.
This PR also adds decimals validation so we can validate the form (SendToken and StakeToken).
1. Go there: …
=> feat: add UiInputAmount and decimals validation

apps/ui/src/App.vue, apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/composables/useActions.ts, apps/ui/src/composables/useEditor.ts, apps/ui/src/composables/useTreasuries.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Editor.vue, apps/ui/src/views/Proposal/Overview.vue
This PR adds support for configuring execution with multiple treasuries 
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/138
1. Get two spaces to test with (one on offchain with oSnap enabled and multiple treasuries configured and another onchain with execution and treasury configured).
2. Try creating proposals on both.
3. Everything works as expected: on offchain you can select multiple treasuries at once, onchain should be limited to one at the time.
4. You can open drafts with execution.
5. You can open editor with execution from treasury page by clicking Send token or Send NFT button.
=> feat: add multiple treasuries support in editor

apps/ui/src/composables/useEditor.ts
After #579 we convert old executions into new format, but it had two issues that caused crash or unexpected behaviour:
- drafts that didn't have execution at all (executionStrategy was null) would cause a crash
- drafts with execution in legacy format would keep reverting to that legacy execution even though if it was changed later
1. Start by deleting your local storage `ui.proposals`.
2. Go back to commit before introduction of new format `git checkout 3792f72be6992a41f9fb46228c6326b23482f4ee`.
3. Enter editor and create draft without execution (insert just title/body) http://localhost:8080/#/s:0cf5e.eth/create
4. Switch back to this branch and reload app, no crashes.
5. In your old draft add some execution.
6. Refresh page again, new execution is visible.
=> fix: verify if legacy execution is non-null

.github/workflows/deploy.yml, scripts/deploy-api-prod.sh
With new script deployment to DO app will be decided based on the URL that api.snapshot.box currently points to.
We use 3dns.box's authoritative nameserver to get latest records.
If it's currently pointing to APP_1 we will deploy to APP_2, if it's currently pointing to APP_2 we will deploy to APP_1.
=> ci: deploy to staging mainnet API app

apps/api/package.json, yarn.lock
This will fix issue with indexing continuing when there was an error during processing.
=> chore: bump @checkpoint-labs/checkpoint to 0.1.0-beta.39

apps/ui/src/views/Space/Overview.vue, apps/ui/src/views/SpaceUser.vue, apps/ui/src/views/User.vue
Fix words in profile's about not breaking, causing the following visual bug
This PR will force all words to break, when reaching the max width, on:
- Space overview
- User profile
- Space user profile
1. Visit http://localhost:8080/#/s:test.wa0x6e.eth , http://localhost:8080/#/s:test.wa0x6e.eth/profile/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3 , http://localhost:8080/#/profile/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3
2. The about content should not overflow, and should look like this
=> fix(ui): break long words in profile's about

apps/ui/src/components/Modal/Vote.vue
Closes: #607
In the vote modal, the reason textarea should be prefilled with the existing vote reason if available, when editing a vote
1. Vote on an offchain proposal with a reason
2. Go back to edit your vote
3. The reason textarea should be prefilled with your previous reason
4. Change the connected account (via your injected wallet)
5. The reason should be refreshed to reflect the vote associated to your account
=> fix(ux): prefill vote reason on edition

apps/ui/src/components/ProposalsList.vue, apps/ui/src/components/ProposalsListItem.vue, apps/ui/src/views/SpaceUser.vue, apps/ui/src/views/SpaceUser/Proposals.vue
Closes: https://github.com/snapshot-labs/workflow/issues/164
1. Go to a any space proposals list
2. Click on any user to go to his space profile
3. There should be a new "PROPOSAL" tab, next to "STATEMENT" in the navigation tab bar
4. The proposals counter should be the same count as the one under this name
5. Navigating to this tab should show all proposals created by this user, for this specific space
Not following figma 100%, as the proposals list component is not formatted like the figma: current list do not have fixed column for title and results
=> feat: space user proposals page

apps/ui/src/views/Proposal.vue
Currently we watch both networkId + spaceAddress and id. But those values are not updated in-sync (id) is synchronous and networkId + spaceAddress are resolved async.
This means that if URL changes from one proposal to another we will call:
1. fetchProposal(oldNetwork, oldSpaceAddress, newProposalId)
2. fetchProposal(newNetwork, newSpaceAddress, newProposalId)
First call is invalid and it shouldn't happen.
This commit changes our watcher to only call fetchProposal when async properties change and id is read from current state.
1. Go to http://localhost:8080/#/s:0cf5e.eth/proposal/0xb4f7cecf8cad2adbbe705730213dcbd4309585a66f14314dd1881901a8db2e81
2. Open console
3. Replace URL to http://localhost:8080/#/matic:0xcD4c00cAB0A86C182519e91a8b01b080B484C49B/proposal/1
4. No errors in the console
=> fix: prevent fetching proposal on wrong network

apps/api/package.json, apps/api/src/utils.ts, apps/mana/package.json, apps/ui/package.json, apps/ui/src/networks/starknet/index.ts, packages/sx.js/package.json, packages/sx.js/src/clients/starknet/constants.ts, packages/sx.js/src/clients/starknet/ethereum-tx/index.ts, packages/sx.js/src/clients/starknet/starknet-sig/index.ts, packages/sx.js/src/types/index.ts, packages/sx.js/src/utils/fees.ts, packages/sx.js/test/integration/starknet/index.test.ts, packages/sx.js/test/integration/starknet/utils.ts, yarn.lock
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/310
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/304
Upgrading to latest starknet version mitigates issues with:
- fee estimation (https://github.com/snapshot-labs/sx-monorepo/issues/304)
- caching timestamps (https://github.com/snapshot-labs/sx-monorepo/issues/310)
However it requires RPC 0.7 which is currently in RC stage and not supported by Infura.
You would need to test it with other provider: https://starknet-sepolia.public.blastapi.io/rpc/v0_7
1. Update URL for mana to use RPC v0.7
2. Try proposing
=> refactor: migrate to starknet@6

apps/ui/src/components/Modal/Vote.vue, apps/ui/src/views/Proposal.vue
Closes: #604
We currently emit a `voted` event from the vote modal on vote submission, then let the calling component handle the necessary post-vote actions.
This lead to duplicated code since multiple component can listen to the `voted` event (Proposal view + ProposalListItem)
Moving these post-vote actions next to the API vote() action is more logical, and all calling components will benefit without code duplication.
1. Vote on a basic offchain proposal from the proposal page
2. After vote submission, modal should close, and the vote form should reflect your current vote (with edit button), and the proposal results should be refreshed with your vote (should already be the current behavior, even before this PR, just confirming that it's not breaking)
3. Vote on a basic offchain proposal …
=> fix(ux): move post-vote actions to the vote modal

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts
The `avatar` property for all offchain spaces is always an empty string;
This PR fetch and set the space's avatar property from offchain hub properly
1. Go to the /explore page 
2. Open the web dev tools and inspect the space's avatar
3. Before this PR, none of the stamp's avatar have a `?cb=` query params
4. After this PR, all the avatar now have a `?cb=` query params
=> fix: fetch avatar for offchain space

apps/ui/src/views/Proposal.vue
Because space data and proposal ID are resolved in different stages we have to avoid fetching new proposal if we have mismatched data (proposalId from new space, space data from new space).
Previously I changed it so we only watch space data and read proposalId on demand, but it introduced a bug that if only proposalId changes it wouldn't be triggered at all.
Now we watch both space data and proposalId, but only act when we know that space data was resolved.
1. Go to http://localhost:8080/#/s:0cf5e.eth/proposal/0xb4f7cecf8cad2adbbe705730213dcbd4309585a66f14314dd1881901a8db2e81
2. Open console
3. Replace URL to http://localhost:8080/#/sn-sep:0x03ced313394107c43a2f36b63262c00a6422231ac229dc4cedd0d9928d8c3c5f/proposal/8
4. No errors in the console
5. Replace URL to …
=> fix: watch proposal id, but ignore if space is unresolved

apps/ui/src/views/Proposal/Votes.vue
This PR follows the trend with the last few PRs, and refresh the votes list in the proposal's votes page, on proposal change.
Until now, we already watch for proposal ID change, but just `reset()` the list without loading the new proposal votes.
This PR will reload the votes on proposal ID change.
1. Go to a proposal's vote page: http://localhost:8080/#/s:safe.eth/proposal/0x8d97075eabfdf3fb9f43f3b490e8e5a7326d77bee919b78543621e36e5b2d233/votes
2. Change the proposal ID manually with `0xdcd7f8cb197c7132296d802e538df2a565fbe4f8af400f1afbed06b54a808060`
3. It should refresh the votes list
4. Going back and forward with the browser navigation back/forward should refresh the list on proposal change
=> fix(ux): reload votes after proposal changes

apps/ui/src/networks/offchain/actions.ts
Currently if you don't select any execution there will be empty oSnap section in plugins.
We should not add it if it's empty.
=> fix: only add oSnap plugin if there are safes defined

apps/ui/src/views/SpaceUser.vue, apps/ui/src/views/SpaceUser/Statement.vue
When navigating from the space user /proposals page to /statement page, the page title is not updated
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/profile/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3/proposals
2. Navigate to the STATEMENT tab
3. The page title should be updated (before, it was just showing `Snapshot`)
=> fix: update space user statement page title

apps/ui/src/components/Modal/SendToken.vue
Closes: #173
When DIV is empty, do not show so adjacent div can take full width
1. Visit http://localhost:8080/#/sn-sep:0x060018768b13a610cd7393d844d8c53960b28f48126a97850f82f933961b894b/treasury
2. Open the "Send token" modal
3. the "Amount" input should take full width
=> fix: do not show empty div

apps/ui/src/components/SpaceDelegates.vue
This PR fix an issue where the ID is show instead of the address, for a delegate address
1. Go to https://snapshot.box/#/matic:0x80D0Ffd8739eABF16436074fF64DC081c60C833A/delegates
2. All addresses should be correct now under the username
=> fix: fix wrong delegate address

apps/ui/src/components/App/Topnav.vue
This PR truncates the user name in the topnav menu account, to avoid having 2 lines on small screen
Before fix: 
After fix:
1. Set a 32 character profile name
2. It should be truncated when too long
=> fix: truncate long user name

apps/ui/src/components/EditorStatement.vue, apps/ui/src/helpers/utils.ts, apps/ui/src/views/SpaceUser/Statement.vue
Some delegates statement may contain HTML tags, specially when imported from third party services.
This PR will strip all html tags, before showing the statement
Before fix:
After fix 
1. Edit your delegate statement to include some html tags
2. It should show the statement without html tags in the profile
3. It should show the original statement with html tags in the edit textarea
=> fix: strip HTML tags from delegate statement

apps/ui/src/App.vue, apps/ui/src/components/Ui/ScrollerHorizontal.vue, apps/ui/src/views/Network.vue, apps/ui/src/views/Space/Delegates.vue, apps/ui/src/views/Space/Treasury.vue, apps/ui/src/views/SpaceUser.vue
Closes: #630 
Extracted the duplicate logic inside #617 and #618 
This PR extract the extra special handling of horizontally scrollable content in a component, to avoid duplication and adds more option like:
- add left and right gradient on demand via props
- disable the uiSidebar menu opening on small screen, when swiping right
Also convert more horizontall scrollable content to use this new component
1. Go to http://localhost:8080/#/matic:0x80D0Ffd8739eABF16436074fF64DC081c60C833A/treasury
2. The TIMELOCK|DAOWALLET menu in the top should be horizontally scrollable on small screen, without triggering the uisidebar opening when swipping, and have a left and right gradient
3. Same for the STATEMENT|PROPOSALS menu in http://localhost:8080/#/s:test.wa0x6e.eth/profile/0xab54624A67E8c018a06B176 …
=> feat: add horizontal scroller component to handle x scroll logic

apps/ui/src/composables/useWeb3.ts
Closes: #651
This PR fixes the issue where the `login()` function is called without an argument, even though we're targeting a specific provider, making this function always being called on the default injected wallet (which will trigger the unlock prompt on metamask if locked, even if you're not connected via metamask)
1. Lock metamask wallet
2. Connect using your argent x wallet
3. Change the account in the argent X wallet
4. the connected account should change, and be reflected on the UI (before, metamask will also asked to be unlocked)
=> fix(ux): missing provider name when calling login()

apps/ui/src/composables/useWeb3.ts
This PR will logout the when the user lock the wallet while connected on the site (=> connected account change to empty value)
This adds more logic in the UX:
- if user locks the wallet => he don't want to connect => log him out
- will avoid the wallet unlock prompt on page refresh
This behavior is used more widely:
- from MM test app: https://metamask.github.io/test-dapp/
- from uniswap: https://app.uniswap.org/
1. Log in with your metamask/argent X wallet
2. Lock the wallet
3. It should log you out
4. Refresh the page
5. You should stay logged out, and there's no wallet unlock prompt anymore
We're detecting and reacting to the wallet locking event in this PR, and will not handle the case where the wallet was already locked before user landed on the page, which will be fixed in another …
=> fix(ux): logout user on wallet lock

apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts
Closes: #631 
This PR fix the extra hours added when using `_d()` to format a duration greater than one month.
The issue come from how the daysjs library compute the number of months (30.x days), which leads to some extra hours.
Since we're not showing the number of months/year at all, this PR will use simple math to show the number of days/hours/minutes/seconds instead of using daysjs. 
1. Wait for #610 merge (as currently, there's no way to exit edit mode on the Editable component without submitting the tx)
2. Go to a space settings VOTING tab
3. Edit the voting delay (or any of the other 2 durations), and put something over one month (like 45 days)
4. Validate the change to exit edit mode
5. It should show the correct number of days, without extra hours
=> fix: fix imprecise duration when greater than one month

apps/ui/src/helpers/utils.ts
This PR addresses an issue where the `getChoiceText()` function will return a choice without text (empty string) as "Invalid choice", instead of just ... an empty string.
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0xb06ef1cd8455e66a3bc064d3f1ec644c2dfed5aaaf33f2cd021b8612da7dd610
2. Select the choice without text and vote
3. In the vote modal, the "Choice" should be shown as an empty string, instead of showing "Invalid string"
=> fix: do not show empty choice text as invalid

apps/ui/src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/workflow/issues/178
1. Go to http://localhost:8080/#/matic:0xcD4c00cAB0A86C182519e91a8b01b080B484C49B/settings
2. Click Executions
3. There is gap between executions.
=
=> fix: add gap between executions in settings

apps/ui/src/components/TopicsListItem.vue, apps/ui/src/helpers/discourse.ts, apps/ui/src/views/Space/Discussions.vue
Add users avatar on the discussions page
Also fix an issue with text overflow when topic title is long.
=> feat: add user avatars on topic list item

apps/api/src/index.ts
This will allow us to merge PRs without long downtime on API.
Ideally we would call it, but because changing domains on DigitalOcean causes a redeploy we will call it on fully-synced instances.
This will work until we merge PR that needs to update past entities - that would require reset.
=> chore: remove reset from API startup

apps/api/src/overrrides.ts
Mainnet doesn't have `OZVotesTrace208StorageProof` so we need to remove it before calling `validateAndParseAddress`
=> fix: remove empty strategies from overrides

apps/api/src/utils.ts, apps/api/test/unit/utils.test.ts
Ethereum addresses can be unpadded in events and ethers getAddress fails if address is not padded. This commit makes sure we pad address before calling getAddress.
Closes: https://github.com/snapshot-labs/workflow/issues/175
1. Tests pass.
=> fix: pad Ethereum addresses on API

scripts/deploy-api-prod.sh
https://discord.com/channels/955773041898573854/1031838169282392144/1278289389461442621
App deployment is failing because of the wrong domain
If we run this:
```bash
dig -t CNAME +short api.snapshot.box @ns1.3dns.box
```
It will return `sx-api-mainnet-2-fmlg8.ondigitalocean.app.` which has a `.` at the end
=> fix: App 2 domain should end with a dot

apps/ui/src/components/Modal/LinkWalletConnect.vue, apps/ui/src/helpers/etherscan.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/helpers/validation.ts
We have predefined list of Etherscan APIs (they have special URLs, can't be generated automatically) and before we only had mainnet and sepolia there, this PR adds all EVM networks we support there.
Also changes bold weight to medium as requested.
Closes: https://github.com/snapshot-labs/workflow/issues/181
1. Connect there: http://localhost:8080/#/s:fabien.eth/treasury on uniswap.
2. Create execution.
=> fix: add more network to WalletConnect support

apps/ui/src/components/App/Topnav.vue
Fix gap above sticky navigation
=> fix: fix wrong topnav height

apps/ui/src/components/SpaceDelegates.vue
This PR fix an issue on the space delegate page, where the gap between column in the content is missing
1. Go to http://localhost:8080/#/matic:0x80D0Ffd8739eABF16436074fF64DC081c60C833A/delegates
2. There should be a 16px gap between all columns
=> fix(ui): fix missing gap between column

apps/ui/src/views/SpaceUser/Statement.vue
Closes: #680 
Fix an issue where the "no statement" message was always showing, even when a statement exist
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/profile/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3
2. It should show the statement, and at the bottom, there shouldn't be a "no statement" message
=> fix: fix no statement message always showing

apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/components/TransactionsListItem.vue
This PR adds expandable section for Transactions with more details (Call info, parameters, value, data).
Data is shown or hidden depending on context (for example data is only shown for raw transactions as others have parsed information available).
Closes: https://github.com/snapshot-labs/workflow/issues/185
1. Check out this proposal or create your own (you can also access details in editor): http://localhost:8080/#/s:0cf5e.eth/proposal/0x124cc146918a5c14e1c9fd40aaa293f5780304f6b26be1a9692160d8d4d4596e
2. You can expand transactions by clicking on them.
=> feat: add transaction details to TransactionsListItem

apps/ui/src/components/Ui/LinkPreview.vue
This PR removes the extra unnecessary div and redundant class from the `UiLinkPreview` component
1. Go to to a proposal with a discussion link (http://localhost:8080/#/s:safe.eth/proposal/0x2c2ad686e94fd97903de8ee520b90d400c98a1985e31b21416da095b28373f18)
2. It should display as before
3. Go to a proposal without preview (http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x21a2d04568291e41485d827def02f2358b981d4a060e879fb3b8b12965d5a2f1)
4. It should display as before
This is a refactoring done while debugging something else, but was finally not the cause of the issue. Submitting a PR instead of throwing those changes away.
=> refactor: remove extra div and class

apps/ui/package.json, apps/ui/src/components/Ui/Markdown.vue, apps/ui/src/helpers/turndownService.ts, apps/ui/src/views/Proposal/Discussion.vue, apps/ui/src/views/SpaceUser/Statement.vue, yarn.lock
- Render HTML content on User statement and discussion
- Display first post in a topic (previously hidden)
- Imporve twitter card
- ![image](https://github.com/user-attachments/assets/b508890c-9fe1-4086-b5cf-5d86850463cd)
Closes: https://github.com/snapshot-labs/workflow/issues/189
1. Go to a discussion page. http://localhost:8080/#/s:lido-snapshot.eth/proposal/0xa478fa5518769096eda2b7403a1d4104ca47de3102e8a9abab8640ef1b50650c/discussion
2. Should be formated similar to https://research.lido.fi/t/organize-the-lido-alliance-program-as-a-lido-dao-adjacent-borg/8173/3
=> feat: Render HTML based content

apps/ui/src/router.ts, apps/ui/src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/workflow/issues/179
With this change tabs are accessed via URL path (`settings/profile`, `settings/voting` etc.)
1. Go to your onchain space settings.
2. Switch tabs, URL updates.
3. Open some URL in new tab, you get redirected to that tab specifically.
=> feat: manage space settings tabs via routes

apps/ui/src/views/Ecosystem.vue
This PR adds the missing page title for the /ecosystem page
1. Go to http://localhost:8080/#/ecosystem
2. It should says "Ecosystem" in the page title
=> fix: add page title to ecosystem

apps/ui/src/components/SpaceDelegates.vue
- Format voting power in delegates page to be same as votes page
1. Go to delegates page http://localhost:8080/#/s:safe.eth/delegates
2. Notice the change in format in which we display voting power
| --- | --- |
| ![image](https://github.com/user-attachments/assets/870d98cb-acab-4a01-b08a-6775fa3e8091) | ![image](https://github.com/user-attachments/assets/56a3b8e9-e373-4688-a66a-d2debf5716ce) |
=> fix: Format voting power in delegates page

apps/ui/src/main.ts
Adds ambire web wallet to known hosts
1. Add snapshot.box in wallet.ambire.com dapps catalog
2. Try to open snapshot.box from dapp catalog
=> Add ambire wallet to known hosts

apps/ui/src/helpers/turndownService.ts
Reported on https://discord.com/channels/955773041898573854/1280493918957473822/1281133931432906788
- On this proposal (http://localhost:8080/#/s:safe.eth/proposal/0x2c2ad686e94fd97903de8ee520b90d400c98a1985e31b21416da095b28373f18/discussion), there is some links without content
Navigate with TAB key, and you will notice that it sometimes does not highlight visible text/links
- This proposal will delete them
1. Go to http://localhost:8080/#/s:safe.eth/proposal/0x2c2ad686e94fd97903de8ee520b90d400c98a1985e31b21416da095b28373f18/discussion
2. you should not see localhost links in console anymore
=> fix: Remove invisible links in discussion topic

apps/ui/src/components/ProposalExecutionActions.vue, apps/ui/src/components/ProposalsList.vue, apps/ui/src/views/Ecosystem.vue, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Proposal/Overview.vue, apps/ui/src/views/Settings/Contacts.vue
Continued from https://github.com/snapshot-labs/sx-monorepo/pull/593#discussion_r1710730620
Use `gap-2`  instead of `inline-block mr-2`
Some places where you can test:
1. Go to http://localhost:8080/#/s:daoxperience.eth/proposals
2. <img width="299" alt="Untitled 2" src="https://github.com/user-attachments/assets/98b920f1-4277-42bc-8a14-96a263cadf8f">
3. Go to http://localhost:8080/#/settings/contacts
4. <img width="412" alt="Untitled 4" src="https://github.com/user-attachments/assets/b7a9928c-c877-434f-8f0f-116ff9f79e70">
5. Go to http://localhost:8080/#/s:shutterdao0x36.eth/proposal/0xfd0e80f5c1b2460f73f63319db5faf9061df263553e38bdc9ab1a4cca946d556
6.
=> refactor: use gap-2 instead of mr-2

apps/ui/src/components/ProposalExecutionsList.vue
Executions depend on proposal network, not where it's going to be executed.
1. Go to http://localhost:8080/#/sn-sep:0x00a330d13703f0af4f87e65d95c898297f8ce6e88ac7e9bff3b3bd270d2f6d5b/proposal/6
2. It shows "Eth relayer execution"
=> fix: use proposal network to get execution name

apps/api/package.json, apps/mana/package.json, apps/ui/package.json, apps/ui/src/stores/followedSpaces.ts, apps/ui/src/views/Space/Settings.vue, apps/ui/src/views/SpaceUser.vue, apps/ui/src/views/User.vue, packages/sx.js/package.json, packages/sx.js/src/strategies/evm/index.ts, packages/sx.js/src/utils/strategies.ts, yarn.lock
Main benefit we get is https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates1
=> chore: bump typescript to 5.5.4

apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/helpers/discourse.ts
- Issue: Throwing error if post doesn't exist
- Fix: Checks if post exist before maping
1. Go to https://snapshot.box/#/s:nation3.eth/proposal/0x9c7b2dc6c9f309e7d67b1c590f9c44adecb91d43ad51454b373e6b6d58e5f74e
2. Notice error: 
3. <img width="587" alt="Untitled 4" src="https://github.com/user-attachments/assets/5cc7fa74-a2ce-4887-a702-96a9d9885227">
4. After fix, you should not see `TypeError: Cannot read properties of undefined (reading 'posts')` error
=> fix: handle empty post

apps/ui/src/views/Space/Settings.vue
Closes: #634
This PR prevents saving a space settings without any authenticators set
We're already ensuring that at least one authenticator is present when creating a space.
This PR will also ensure the same when saving a space, and prevent spaces with invalid settings
1. Go to a space settings
2. Delete all authenticators
3. It should show an error message, and disable the save button
4. The save button should be enabled only when at least one authenticator is present
=> fix: prevent saving space settings without authenticators

apps/mana/src/eth/dependencies.ts, apps/ui/src/helpers/provider.ts, packages/sx.js/package.json
Reported at https://discord.com/channels/955773041898573854/1182427601046884352/1282067787845730304
we've just had a report that the proposals are showing "hasn't started" even though the users have already voted and the proposal already started.
https://snapshot.box/#/sn:0x07bd3419669f9f0cc8f19e9e2457089cdd4804a4c41a5729ee9c7fd02ab8ab62/proposal/5
You should see that proposal is active
=> fix: Change rpc URL domain

apps/ui/src/views/Space/Settings.vue
Same changes as mentioned here https://github.com/snapshot-labs/workflow/issues/197#issuecomment-2334507517
Handle strategy address comparison, Params need to be lowercase when we compare them as once stored they will be stored as bytes (casing is lost).
Closes: https://github.com/snapshot-labs/workflow/issues/197
1. Go to http://localhost:8080/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/settings/voting-strategies
2. Login with `0x8C28Cf33d9Fd3D0293f963b1cd27e3FF422B425c` using impersonator
3. Before fix you should see the "save changes" button without any changes
4. After fix you should see save changes only when you change some settings
=> fix: Handle strategy address comparison

apps/ui/src/helpers/utils.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/starknet/index.ts
Closes: #546 
This PR adds a network switcher (sn_main <-> sn_sepolia) to argent X wallet (braavos don't support this feature)
1. Trigger some action requiring starknet signature
2. If your wallet is on the expected network, argent X should show the signature popup (existing behavior)
3. If the wallet is not on the expected network, argent X should show the network switcher popup
4. If REJECTING the switch, it should cancel the signature
5. if APPROVING the switch, it should switch to the correct network, and show the signature popup
- For those using Braavos wallet, the network switcher will be skipped since unsupported, and will directly show the signature popup using the wallet current network (existing behavior)
- If the target network does not exist, argent X will skip the network …
=> feat: add network switcher for starknet wallet

apps/ui/src/components/SpacesListItem.vue
As discussed on call, 
Display extra line on space items to occupy more space 
(using `line-clamp-4` is actually occupying full empty space)
1. Go to explore page
| --- | --- |
| <img width="1001" alt="Untitled 11" src="https://github.com/user-attachments/assets/e9f6ce56-b34a-45e0-986a-fda972e7e080">| <img width="1052" alt="Untitled 12" src="https://github.com/user-attachments/assets/589234db-53e0-422e-86d1-4d48a301c9f1"> |
=> fix: Show extra line on space items

apps/ui/src/views/Space/Settings.vue
Change settings header z-index to `40` similar to other sticky headers
Closes: https://github.com/snapshot-labs/workflow/issues/203
1. Go to settings page and scroll down with keypad
2. Settings header should go below navbar like all other places
=> fix: change settings header z-index

apps/ui/src/App.vue
Remove the left spacing on sites-* routes.
Temp fix, #740 will fix and prevent futures issues by isolating all layouts
=> fix: remove left spacing on site routes

apps/ui/src/helpers/connectors.ts
Walletconnect safe transaction doesn't trigger
1. Connect to your safe with walletconnect (with new changes make sure to disconnect if you are already connected)
2. Go to any proposal that accept eth transaction
3. Try to vote
4. Before fix. it will show error: "unknown account" 
5. After fix: it will open transaction modal on Safe
=> fix: walletconnect safe transaction doesn't trigger

apps/ui/src/views/SpaceUser.vue
Working toward https://github.com/snapshot-labs/workflow/issues/142
This PR removes the unnecessary `watch` on the address, since the SpaceUser view is already getting the `space` object from the parent Space view, which already have a watcher on the address there.
This PR aims to remove all the unnecessary watcher, to have everything in one place, since watcher on url will not work anymore on white label spaces. Extracting as much unrelated changes as possible in external PR to lighten the whitelabel PR
1. Go to a space user profile
2. Change the user address in the url
3. the content should refresh
4. Change the space in the url
5. the content should refesh
=> refactor: remove unecessary watch

.changeset/neat-falcons-pay.md, apps/mana/src/db.ts, apps/mana/src/stark/registered.ts, apps/mana/src/stark/rpc.ts, apps/ui/src/composables/useActions.ts, apps/ui/src/helpers/mana.ts, packages/sx.js/src/clients/evm/ethereum-tx/index.ts, packages/sx.js/src/clients/starknet/ethereum-tx/index.ts
This PR contains following fixes for EthTx:
1. Initialize transaction is now also possible to be added to Safe without funds.
2. Vote transaction always uses `vote` call to build strategies.
3. Commit is read using (hash, sender) as it was updated on the contracts.
1. Run local mana, update `VITE_MANA_URL=http://localhost:3001`.
2. Use Starknet or Starknet sepolia space with EthTx authenticator and your safe whitelisted.
3. Connect to app with Safe's WC.
4. Try starting a vote without funds, you can prepare transaction.
5. Execute vote on Safe (after you have funds).
6. Wait.
7. After a while mana completes transaction, vote is visible on UI.
We will need to update database on production before merging (or we could drop old table entirely after we back it up)
=> feat: update Starknet's EthTx

apps/ui/src/composables/useWeb3.ts, apps/ui/src/helpers/utils.ts
- Unable to connect to Argent mobile app (unable to pick `chainId`)
- Unable to vote with inbuilt browser inside Argent mobile app (getting `unknow request` error
- While connecting, Pick chainId using `auth.provider.value.chainId`
- While voting inside the inbuilt browser, `wallet_switchStarknetChain` doesn't work, so ignoring it for now (as only SN_MAIN is supported)
1. Connect and with Argent mobile app
2. Test in desktop
3. Test in mobile chrome
4. Test in inbuild browser
=> fix: Can't connect and vote with argent mobile app

apps/ui/src/views/App.vue, apps/ui/src/views/Landing.vue, apps/ui/src/views/Network.vue, apps/ui/src/views/Policy.vue, apps/ui/src/views/Site.vue, apps/ui/src/views/Terms.vue
Working toward https://github.com/snapshot-labs/workflow/issues/142
This PR will set the page title properly inside each page in views/*.vue (except root page containing `<router-view>`), instead of relying on the default one (hardcoded in index.html).
1. Visit all the routes from `site-`
2. There should be a page title reflecting the page content, instead of just 'Snapshot'
3. Homepage is the only one with `Snapshot` as title (which should be fetched from useApp, once https://github.com/snapshot-labs/sx-monorepo/pull/763 is merged)
=> fix: set page title in all sites pages

apps/ui/src/components/SpaceDelegates.vue
- Witdh of delegators is causing text to truncate
1. Go to http://localhost:8080/#/s:balancer.eth/delegates
2. click on delegators column header to sort
3. Notice that text of header is truncated before the fix
| --- | --- |
| <img width="153" alt="Untitled 4" src="https://github.com/user-attachments/assets/0b9208d7-c16a-4a35-9368-0a718c32b083"> | <img width="199" alt="Untitled 5" src="https://github.com/user-attachments/assets/5011745b-b82e-4931-aedd-d2507f26d650"> |
=> fix: Delegators col width

apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts
When loading an invalid proposal like this http://localhost:8080/#/sep:0xb58B05A1c8263441Bd74454544fD66CE25D300AD/proposal/58sdfdsdsff
The page is crashing with 
```
TypeError: Cannot read properties of null (reading 'metadata')
```
This PR ensures proposal object exist before any handling
1. Go to http://localhost:8080/#/sep:0xb58B05A1c8263441Bd74454544fD66CE25D300AD/proposal/58sdfdsdsff
2. There's no more error in the console (page still stuck on loading state, but out-of-scope of this PR)
=> fix: fix network api error when proposal do not exist

apps/ui/src/composables/useApp.ts, apps/ui/src/composables/useSharing.ts, apps/ui/src/composables/useTitle.ts, apps/ui/src/composables/useWalletConnect.ts, apps/ui/src/helpers/connectors.ts, apps/ui/src/helpers/constants.ts
Working toward https://github.com/snapshot-labs/workflow/issues/142
This PR refactors the UI to pull the `APP_NAME` from a single source (constants, then `useApp` composable).
Using the composable instead of the constant directly will allow changing the app name after initialization (e.g. for white label)
There's still a last part, walletLink, which is getting its name directly from the constant. Making it dynamic will requires some more refactoring out-of-scope for this PR
=> refactor: get app name from useApp composable

apps/ui/src/composables/useApps.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/views/App.vue
- Sometimes github field is just username, example `UMAprotocol` instead of `https://github.com/UMAprotocol`
- Sometimes x field starts with `@`, example `@UMAprotocol` instead of `UMAprotocol`
Closes: #
1. Go to http://localhost:8080/#/ecosystem/osnap
2. Before fix, page will fail with error:
3. <img width="867" alt="Untitled 7" src="https://github.com/user-attachments/assets/dcb9926b-74af-401e-864b-4d637e854d32">
4. After the fix, page should open without any errors
5. <img width="227" alt="Untitled 8" src="https://github.com/user-attachments/assets/94e37813-7f7f-452e-a156-12db822cfe41">
=> fix: handle github URL in ecosystem page

apps/ui/src/composables/useApps.ts, apps/ui/src/views/App.vue
Closes: https://github.com/snapshot-labs/workflow/issues/214
NOTE: I have removed newlines on snapshot.box so you won't be able to reproduce there
- If csv values contain new lines `/n` 
for example data like:
- UI will  break like this:
0. Apply this change to see data with new lines:
```bash
diff --git a/apps/ui/src/composables/useApps.ts b/apps/ui/src/composables/useApps.ts
index 5aaad33c..c6d09666 100644
--- a/apps/ui/src/composables/useApps.ts
+++ b/apps/ui/src/composables/useApps.ts
@@ -1,6 +1,6 @@
// URL: https://docs.google.com/spreadsheets/d/1aUkvul0ja3ojK8N30MbG-BdXSbWFwRbGenvdo2dPWGU
const APPS_SHEET_ID =
-  '2PACX-1vSXPvTkgUnjTkBoCs-z1ionjuGFhO8kcGrXqUOw38BbS5Tf60wlgVYJCFk-El1_96xH1tHL6MNeW-6q';
+  '2PACX-1vT8Edufx_yJSqbJpQVhfnp4qj0D-NC23I3Pz8mAeoByhduiLqxIlKnoq2RKW_BnzWPn5bTOq …
```
=> fix: handle newline in csv

apps/ui/src/components/Modal/TransactionProgress.vue, apps/ui/src/components/ProposalIconStatus.vue, apps/ui/src/components/ProposalsListItemHeading.vue, apps/ui/src/components/Ui/Composer.vue, apps/ui/src/components/Ui/Loading.vue, apps/ui/src/views/My/Home.vue, apps/ui/src/views/Space/Proposals.vue
Add a new `size` props to UiLoading and ProposalIconStatus components, to set the `width` and `height` at the same time, and avoid duplication.
This props is already used in some component like Stamp and Nft
- Go to a onchain proposal
- it should show proposal status as before
- all loading icon should have the same size as before
=> feat: add size props to UiLoading

apps/ui/src/composables/useSpaceSettings.ts
Now our params not only will be lowercase-only, but also:
1. stored as hex
2. unpadded
1. Apply diff from below.
2. Go to http://localhost:8080/#/eth:0x6E60b6dCc2923267104Bb4a68F4766f627430664/settings/voting-strategies
3. You don't see save settings prompt.
4. Go to http://localhost:8080/#/sn:0x06f7d16cda7166d007289940ffdf85f18ada9e3fe94f7d75ea260d2bc0ad5a84/settings/authenticators
5. You don't see save settings prompt.
```diff
diff --git a/apps/ui/src/views/Space/Settings.vue b/apps/ui/src/views/Space/Settings.vue
index 1977471f..e70ebc0d 100644
--- a/apps/ui/src/views/Space/Settings.vue
+++ b/apps/ui/src/views/Space/Settings.vue
@@ -490,9 +490,7 @@ watchEffect(() => setTitle(`Edit settings - ${props.space.name}`));
</teleport>
</UiContainerSettings>
<div
-      v-if="
- …
```
=> fix: use raw bytes for params when comparing

apps/ui/src/components/ProposalsListItem.vue, apps/ui/src/components/ProposalsListItemHeading.vue
This PR fix an issue where clicking on the basic voting choice in the proposal list do not open the voting modal (and not nothing)
1. Go to a space with basic choices proposal
2. Go to the /proposals page
3. The basic choice vote form in the proposal list should now work (clicking on any choice should open the vote modal)
=> bug(ux): fix missing vote modal on proposal list

apps/ui/src/components/Modal/VoteReason.vue, apps/ui/src/views/My/Notifications.vue, apps/ui/src/views/Proposal/Overview.vue
Force word to break on long proposal title
Before fix
After fix
Also fix same issue with long vote choice
1. Go to  http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x690486495e089e9ecb8f2e68b95e5a988c5446bd6af101d78a3e8633532f874c
2. Open reason modal for vote in http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x062cc4845a9f7568c931afe3366bd6440b9b43061d98193fa651825f0c8b5173/votes
=> fix(ui): force a word break on long proposal title

apps/ui/src/helpers/discourse.ts
Closes: #767 
Show an error message when the discussion link is invalid
1. Go to http://localhost:8080/#/s:safe.eth/discussions/25745677484848
2. It shows the message `Error while loading the topic.`, instead of empty topic list
=> fix: show an error when discussion link is invalid

apps/ui/src/components/ProposalsListItemHeading.vue, apps/ui/src/views/SpaceUser.vue, apps/ui/src/views/User.vue
This PR break long username into multiple lines when necessary, to avoid UI issues like
1. Go to http://localhost:8080/#/profile/0xab54624A67E8c018a06B176bAAE76a40a385A464
2. Go to https://snapshot.box/#/s:test.wa0x6e.eth/profile/0xab54624A67E8c018a06B176bAAE76a40a385A464
3. Username should not overflow
=> fix: break long username

apps/ui/src/components/ProposalsListItemHeading.vue, apps/ui/src/views/My/Notifications.vue, apps/ui/src/views/SpaceUser/Votes.vue
This PR break long words in proposal title
Before fix 
After fix
This uses the `[overflow-wrap:anywhere]` class to break words properly, since the `break-words` class by tailwind does not cover this use case. See https://github.com/tailwindlabs/tailwindcss/discussions/2213
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposals
2. On wide screen, proposal title should be truncated
3. On small screen, proposal title should be on multiple lines
=> fix: break long words in proposal title

apps/ui/src/stores/notifications.ts
Closes: #785 
This PR start and stop the notification polling only when relevant.
- It starts the poller only when follow list is not empty
- It stops the poller when follow list is empty
1. Apply diff to print console
```diff
diff --git a/apps/ui/src/stores/notifications.ts b/apps/ui/src/stores/notifications.ts
index 24638e43..b920bd95 100644
--- a/apps/ui/src/stores/notifications.ts
+++ b/apps/ui/src/stores/notifications.ts
@@ -127,12 +127,14 @@ export const useNotificationsStore = defineStore('notifications', () => {
loading.value = false;
if (!refreshNotificationInterval) {
+          console.log('start poller');
refreshNotificationInterval = window.setInterval(
loadNotifications,
REFRESH_INTERVAL * 1000
);
}
} else if (!followedSpacesIds.length && refreshNotificationInterval) {
+ …
```
=> fix: do not poll notifications when follow list is empty

apps/ui/src/components/Ui/SelectMultiple.vue
Those were defined wrong way around. Should point down if closed, up if opened.
=> fix: flip dropdown icons

apps/ui/src/composables/useVotingPower.ts
I don't remember exactly why, but for EVM we don't support null as block (issue to investigate it: https://github.com/snapshot-labs/sx-monorepo/issues/805).
But we did use null for pending proposals. This PR prevents it.
1. You see your VP here: http://localhost:8080/#/sep:0xb58B05A1c8263441Bd74454544fD66CE25D300AD/proposal/61
=> fix: do not use null as snapshot for EVM spaces

apps/ui/src/views/Space/Overview.vue
Prevent UI bug on sub spaces like:
1. Visit http://localhost:8080/#/s:test.wa0x6e.eth
2. All sub-spaces stats should now be on same line
=> fix: increase sub space card to accomodate larger stats

.changeset/sweet-papayas-provide.md, apps/ui/src/assets/icons/switch-disabled.svg, apps/ui/src/assets/icons/switch-enabled.svg, apps/ui/src/components/FormSpaceAdvanced.vue, apps/ui/src/components/Modal/DeleteSpace.vue, apps/ui/src/components/Ui/Checkbox.vue, apps/ui/src/components/Ui/ContainerSettings.vue, apps/ui/src/components/Ui/InputString.vue, apps/ui/src/components/Ui/Message.vue, apps/ui/src/components/Ui/Switch.vue, apps/ui/src/components/Ui/WrapperInput.vue, apps/ui/src/composables/useActions.ts, apps/ui/src/composables/useSpaceInputValidation.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/helpers/validation.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/types.ts, apps/ui/src/style.scss, apps/ui/src/views/Space/Settings.vue, packages/sx.js/src/clients/offchain/ethereum-sig/index.ts, packages/sx.js/src/clients/offchain/ethereum-sig/types.ts, packages/sx.js/src/clients/offchain/types.ts
Adding advanced settings page for offchain spaces with following options:
- Sub-spaces (parent and child spaces)
- Terms of services
- Custom domain
- Hide from homepage
- Delete space
Had to make some adjustments from the design, as not everything was clear:
- Not extraneous modals for parent-space, sub-space, custom-domain (in designs we have input, but also modal that opens for you to type in, which I'm not sure makes sense, here I just use inputs directly avoiding modals.
- Designs didn't cover how already added sub-spaces should look like, so I improvised.
- No tooltip for custom domain input as we don't have it either on v1 so I didn't have text to use.
Closes: #
1. Create new space (if you want to delete it, **you will lose ability to recreate space under that domain**).
2. Go to …
=> feat: add Advanced settings for offchain spaces.

apps/ui/src/views/Editor.vue
Toward #801
This PR shows the correct title in TopNav when editing a proposal
1. Go to a proposal edition page
2. The tiltle in topnav should now says "Update proposal"
=> fix: Editor title should reflect update status

apps/ui/src/components/EditorChoices.vue, apps/ui/src/components/Ui/Composer.vue, apps/ui/src/helpers/turbo.ts, apps/ui/src/helpers/validation.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Editor.vue, apps/ui/src/views/Space/Editor.vue
Following https://github.com/snapshot-labs/sx-monorepo/pull/773 with new design
Closes: https://github.com/snapshot-labs/workflow/issues/134
- Show a message when someone tries to post a proposal over the limit
- Show a message when someone tries to add more than the choices limit
- Show a message when someone tries to add more than the body chars limit
- Fix in apps/ui/src/helpers/validation.ts - Throws an error if we try to add more choices than the limit while keeping all choices empty
1.  Update limits in apps/ui/src/helpers/turbo.ts
2. Also update `verified` or `turbo` in https://github.com/snapshot-labs/sx-monorepo/blob/feat-turbo-hints/apps/ui/src/networks/offchain/api/index.ts#L168-L169
When body chars limit is reached:
On turbo space:
On Non-offchain spaces:
When choices limit is …
=> feat: Show hints on proposal editor to get verified or to get turbo

apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/views/Space/Settings.vue
It takes a while to fetch controller. We can make experience better by caching it and reuse it when possible (not loading/reloading space).
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/791
1. Go to offchain space settings, change space name.
2. Click reset.
3. It is instant.
=> feat: cache controller

apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/components/TransactionsListItem.vue
This PR improves of executions list is rendered on small screens by truncating text as needed.
Closes: https://github.com/snapshot-labs/workflow/issues/217
1. Go to http://localhost:8080/#/s:0cf5e.eth/proposal/0x124cc146918a5c14e1c9fd40aaa293f5780304f6b26be1a9692160d8d4d4596e
2. Go to http://localhost:8080/#/s:0cf5e.eth/create/k3erai
3. Play with small screens.
=> fix: improve executions list design on small screens

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/stores/proposals.ts
Closes: #817 
This PR fix an issue where searching for an offchain proposal is not honoring the space ID params.
This means that these 2 urls for 2 different spaces but same proposal id will still show the same proposal
- http://localhost:8080/#/s:safe.eth/proposal/0x24fbb1d77f8ba561a3d77903b68c0c0a6d495eb394465f93a8d94aa537be80dc
- http://localhost:8080/#/s:aave.eth/proposal/0x24fbb1d77f8ba561a3d77903b68c0c0a6d495eb394465f93a8d94aa537be80dc
1. Go to the 2 urls above
2. It should show the proposal only on the correct space
=> fix: fix offchain proposal search ignoring space id

apps/api/src/index.ts, apps/api/src/overrrides.ts, apps/api/src/schema.gql, apps/api/src/writer.ts, apps/subgraph-api/schema.graphql, apps/subgraph-api/src/mapping.ts
This just `verified` (and for future `turbo` property so schema is ready) to API, on Starknet it will set this flag for some spaces. 
Towards: https://github.com/snapshot-labs/workflow/issues/215 (UI changes in future PR once APIs are deployed).
1. Run local API, check verified flag on Nostra (demo) for sepolia.
=> feat: index verified spaces

.github/workflows/test.yml
24.04 is not supported by graph-cli
1. Tests should pass.
=> ci: run tests on Ubuntu 22.04

apps/ui/src/composables/useSharing.ts
This PR renames the `isPrivate` variable to `hasPrivacy`, to reflect its purpose.
`isPrivate` is a property of space, and is used for hiding space from homepage.
This is to avoid confusion, particularly when searching the code for this keyword
=> refactor: avoid confusing isPrivate variable name

apps/ui/src/views/Space/Overview.vue
This PR migrates the children spaces to the scrollerHorizontal component
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth
2. It should behave as before
=> refactor: migrate subspaces to uiscrollerhorizontal

apps/ui/src/composables/useSpaceSettings.ts
Previously delegations didn't have network defined at all, and treasuries network was improperly ignored.
Those issues are now resolved.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/828
1. Go to offchain space settings.
2. Edit delegation network.
3. Edit treasury network.
4. Changes are properly saved.
=> fix: persist network on treasuries and delegations on offchain spaces

apps/ui/package.json, apps/ui/src/components/Combobox.vue, apps/ui/src/components/FormSpaceStrategies.vue, apps/ui/src/components/FormStrategiesStrategyActive.vue, apps/ui/src/components/FormValidation.vue, apps/ui/src/components/Modal/EditStrategy.vue, apps/ui/src/components/Modal/Strategies.vue, apps/ui/src/components/StrategiesConfigurator.vue, apps/ui/src/components/Ui/Form.vue, apps/ui/src/components/Ui/SelectorNetwork.vue, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/helpers/turbo.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/networks/types.ts, apps/ui/src/views/Space/Settings.vue, yarn.lock
This PR adds support for configuring strategies on offchain networks. With this you can add, edit or delete strategies.
There are few changes compared to the [designs](https://www.figma.com/design/hmHTau1Y1KYzrBBKLQr5QV/%23design?node-id=6966-14342&node-type=frame&m=dev):
- Voting symbol is not in this section (it's in the profile).
- Strategy item is not exactly the same as per designs (which used Snapshot v1 design) as it was more unified with existing item.
- No learn more link in Edit strategy modal (as in v1).
1. Go to offchain space's you control settings.
2. You can modify strategy settings.
=> feat: add Strategies settings to offchain spaces.

apps/ui/src/components/Modal/Vote.vue
Closes: #834 
This PR disables vote reason on shutter proposal
1. Go to a shutter proposal
2. The vote modal should not have the reason textarea
3. Go to a regular proposal
4. The vote modal should have the reason textarea
=> fix: disable vote reason on shutter proposals

apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/Modal/LinkWalletConnect.vue, apps/ui/src/components/Modal/SendNft.vue, apps/ui/src/components/Modal/SendToken.vue, apps/ui/src/components/Modal/StakeToken.vue, apps/ui/src/components/Modal/Transaction.vue, apps/ui/src/components/Modal/TreasuryConfig.vue, apps/ui/src/components/PickerToken.vue, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/components/Ui/BadgeNetwork.vue, apps/ui/src/composables/useBalances.ts, apps/ui/src/composables/useNfts.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/composables/useTreasuries.ts, apps/ui/src/composables/useTreasury.ts, apps/ui/src/helpers/alchemy/index.ts, apps/ui/src/helpers/constants.ts, apps/ui/src/helpers/opensea.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/types.ts, apps/ui/src/views/Space/Treasury.vue
This PR starts work towards making treasuries more flexible in terms of support.
- Treasury network doesn't need to be supported by the app to for treasury to show up (will be read-only, can't be used in execution at the moment)
- Treasury can have varying support for tokens/NFTs - if we only support tokens for specific treasury it will still be displayed in the UI, just message that NFTs are not supported for this network will be displayed. We might be missing support for both tokens and NFTs, and it will still be visible, you will have link to explorer to check it yourself.
- Starknet treasuries will be visible now (but they don't have balance/NFTs support at the moment).
- Treasuries for unsupported networks will be displayed in settings (but network selector won't display those …
=> refactor: support any treasury with chainId

.changeset/gentle-peas-nail.md, apps/ui/src/components/FormSpaceDelegations.vue, apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/components/Modal/DelegationConfig.vue, apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/components/Ui/SelectorNetwork.vue, apps/ui/src/composables/useActions.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/composables/useTreasury.ts, apps/ui/src/helpers/constants.ts, apps/ui/src/helpers/explorer.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/evm/index.ts, apps/ui/src/networks/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Create.vue, apps/ui/src/views/Space/Settings.vue, packages/sx.js/src/evmNetworks.ts
Previously delegations would only work for few networks that we have enabled, but with this change we will allow all networks to function by leveraging ETH as base action network that can act on different chainIds.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/830
1. Add some unusual network to your Metamask using https://chainlist.org/ (we don't really handle case if user doesn't have some network added currently, might be another issue to take a look into).
2. Add delegation to your offchain space using this network (I only used dummy contract as I couldn't find erc20-votes tokens on different networks).
3. Go to delegations, you see them, you can start delegating (if you have correct contract).
=> feat: enable delegations on all networks

apps/ui/src/components/Modal/EditStrategy.vue
Closes: https://github.com/snapshot-labs/workflow/issues/243
1. Go to the space creation form, and strategy tab
2. Choose a strategy with contact picker
3. Pick a contact
4. If should show your contact list, and hide the strategy form
=> fix: fix strategy form not hiding on picker open

apps/ui/src/components/FormSpaceProfile.vue, apps/ui/src/components/Layout/App.vue, apps/ui/src/components/SpaceAvatar.vue, apps/ui/src/components/SpaceCover.vue, apps/ui/src/components/Ui/InputStamp.vue, apps/ui/src/components/Ui/Stamp.vue, apps/ui/src/helpers/utils.ts, apps/ui/src/views/Space.vue
Toward https://github.com/snapshot-labs/workflow/issues/220
This PR moves all stamp url to the new `network:address` format, introduced in https://github.com/stamp-labs/stamp/pull/311
This new format enable space avatar and cover for offchain testnet.
This PR is will migrate all stamp type from `space-sx` and `space-cover-sx` to just `space` and `space-cover`, and will prefix all id with the space network
1. Go to the snapshot and snapshot x explore page
2. All space avatar and cover should show as before, (all stamp url are now prefixed with network ID)
=> feat: use new stamp url format for space cover and avatar

apps/ui/src/components/Layout/App.vue
Closes: https://github.com/snapshot-labs/workflow/issues/251
Fix issue with topnav z-index, when sidemenu is open.
Forcing content z-index to always be on top of menu was introduced to fix https://github.com/snapshot-labs/sx-monorepo/pull/800
To prevent this issue from happening, this PR is now using hiding the topnav when not relevant, instead of relying on css z-index.
Hiding the menu will also fix an accessibility issue, where navigating with keyboard was focusing on hidden topnav element
On a small screen
1. Go to a long proposal page
2. scroll down
3. Open the sidemenu
4. Proposal content should not be on top of topnav
5. Go to editor page
6. Open the sidemenu
7. Default topnav should disappear, and only editor topnav should remain
=> fix: fix z-index issue on sidemenu open

apps/ui/src/composables/useWeb3.ts
Currently, on Metamask and ArgentX, when a connected user lock his wallet, he's being logged out.
This PR fix an issue, where this behavior is not working on Braavos wallet.
NOTE: Even after the fix, there's some unrelated issue when reconnecting with Braavos, see note below
1. Connect with your Braavos wallet
2. Lock the wallet
3. It should log you out
4. You can log in again with other wallet type (reconnecting to braavos wallet again has somme issue)
This PR is only fixing the issue where the log out on wallet lock does not work.
When reconnecting with a Braavos wallet, the connector is able to log in, but has some issue like argent x wallet modal not closing, or opening multiple time, etc ...
Those issues are out of scope of this PR, and are probably related to …
=> fix: logout users on Braavos wallet lock

apps/ui/src/components/Ui/InputString.vue
Closes: #732 
This PR fix the invalid input characters counter when the input contains some exotic unicode characters, where some characters like 🔔 are counted as 2
This fix the issue by using (copy/paste) same logic used by AJV to validate string length
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/settings/profile
2. Input with exotic characters, like the voting power symbol should show the correct characters count
=> fix: fix invalid input character count on multi-glyph character

apps/ui/src/components/ProposalLabels.vue, apps/ui/src/components/ProposalsListItemHeading.vue
Proposal titles will be truncated again, leaving labels visible.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/872
1. Go to http://localhost:8080/#/s:fabien.eth/proposals
=> fix: truncate proposal title

apps/ui/src/views/SpaceUser/Statement.vue
Fixes https://github.com/snapshot-labs/workflow/issues/242
This PR removes the HTML to Markdown conversion on user statement.
Conversion has issue when statement is already markdown formatted, as it's removing new line
1. Go to https://snapshot.box/#/s:fabien.eth/profile/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7
2. Markdown content should be formatted properly
=> fix: remove html to markdown conversion on user statement

apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts
Fix failing tests due to circular dependency in utils.ts
This PR removes the `offchainNetwork` check, and let the try/catch just return the input as is on error
1. Tests should pass
2. Stamp avatar should work as before: http://localhost:8080/#/explore and http://localhost:8080/#/explore?p=snapshotx
=> fix: remove circular dependency

apps/ui/src/components/ProposalLabels.vue, apps/ui/src/components/Ui/ProposalLabel.vue
Closes: https://github.com/snapshot-labs/workflow/issues/259
1. Go to proposals, proposal, settings and editor
2. Text size on all labels everywhere should be same
=> style: labels should always use text-sm

apps/mana/src/stark/herodotus.ts
New API version uses API key in the headers.
=> fix: pass Herodotus apiKey in headers

apps/ui/src/networks/offchain/api/index.ts
Network is required to be able to create execution on the UI (required for Stamp in token pickers etc.)
We removed it previously, but it caused treasuries to become unusable in proposals.
Closes: https://github.com/snapshot-labs/workflow/issues/256
1. Go to https://snapshot.box/#/s:jbdao.eth/treasury/1/tokens
2. You see buttons to create execution.
=> fix: set network on offchain treasuries

apps/ui/src/composables/useSpaceSettings.ts
Name shouldn't cause change in strategies to be detected.
Those might not be stable (like addition of (trace 224) to OZ Votes Strategy).
We already compare addresses which are canonical.
Closes: https://github.com/snapshot-labs/workflow/issues/248
1. Apply diff from below.
2. Go to http://localhost:8080/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c/settings/profile
3. You don't see save bar without any changes.
```diff
diff --git a/apps/ui/src/composables/useSpaceSettings.ts b/apps/ui/src/composables/useSpaceSettings.ts
index bb5fbe0d..c677d3b2 100644
--- a/apps/ui/src/composables/useSpaceSettings.ts
+++ b/apps/ui/src/composables/useSpaceSettings.ts
@@ -97,7 +97,7 @@ export function useSpaceSettings(space: Ref<Space>) {
space.value
);
-    return …
```
=> fix: omit strategy name in change detection

apps/mana/src/stark/herodotus.ts
Prod contracts match our own, so we can use it.
=> chore: use production Herodotus API on sepolia

.changeset/eight-icons-explain.md, packages/sx.js/src/strategies/starknet/abis/EVMSlotValue.json
For some reason Scarb doesn't generate this method in ABI. Added it manually.
1. You see your VP here: http://localhost:8080/#/sn-sep:0x06001fefa235867a03ebcc02b82265762ae475c19ad3373e92cb6562ffc6fe61/proposal/6
=> fix: add missing cached_timestamps method in EVMSlotValue ABI

apps/ui/src/components/Ui/LinkPreview.vue
Closes: #891 
This PR fix an issue where the LinkPreview component is showing nothing when the given website has no page title
Before fix
After fix
1. Go to Editor
2. In the discussion input, type `https://snapshot.box`
3. It should show a link preview, with the url in place of the blank page title
4. Create a proposal with this url
5. It should show the same link preview
=> fix: fix blank link preview when url has no page title

apps/ui/src/components/Modal/DelegationConfig.vue
Closes: #893
This PR fix an issue where the contact picker in the space settings delegation modal was not opening the address book on click
1. Go to a space settings -> delegation
2. Add/edit a delegation
3. Go to the address field
4. Click on the contact picker icon
5. It should open the contact list
=> fix: fix contact picker not opening address book

apps/api/src/ipfs.ts
This field is non-nullable so it has to be defined.
Currently this query is failing:
```gql
{
proposals {
metadata {
labels
}
}
}
```
=> fix: always initialize Starknet proposal labels

apps/api/src/schema.gql
Towards https://github.com/snapshot-labs/workflow/issues/260
String type only supports 256 characters in checkpoint so we have to use different type.
=> feat: allow for longer vote reason on Starknet API

apps/ui/src/views/Space/Editor.vue
Closes: #886 
This PR removes blank choices before save. 
1. Create a proposal with some empty choices
2. It should ignore the blank choices on creation
=> fix: filter out empty choices before saving

apps/ui/src/composables/useEditor.ts
Closes: #903 
This PR fix the issue where deleting the current draft will create new one, in addition of not deleting the draft.
Issue is coming from draft considering all blank draft as dirtied, because of the new `labels` property
1. Go to editor
2. dirty the form
3. open draft modal
4. delete current draft
5. It should remove the given draft from the list, without creating new one
=> fix: fix draft ignoring labels

apps/ui/src/components/IndicatorVotingPower.vue, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Space/Proposals.vue
Toward https://github.com/snapshot-labs/workflow/issues/254
This PR will allow the Voting power indicator to shrink and truncate when needed. This fix will allow all elements to be flexible, and neatly shrink when needed, and allow more room for the upcoming labels filter
Before fix
After fix
On a mobile device
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposals
2. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0xbe1481bc1a5cfaa4a19979b950faadd7919d913b87f03115750fc3463d1349d9
3. The voting power indicator should stay on the same line, and will be truncated when needed
=> fix: allow voting power indicator to shrink

apps/ui/src/components/EditorChoices.vue, apps/ui/src/components/EditorVotingType.vue
Elements in the Editor right sidebar have a mix of different spacing, set in different places.
This PR will make sure that:
- the same spacing `space-y-4` (already present in the sidebar container) is always used
- remove all custom spacing inside the components (EditorXXX components)
1. Go to Editor page
2. All elements in the right sidebar should have the same `4` spacing
=> fix: standardize spacing in editor sidebar

apps/ui/src/composables/useActions.ts
due to operator preference networkId was actually ignored
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/917
1. Go to http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50/delegates
2. Sign in with Starknet mainnet account.
3. You can delegate.
=> fix: use networkId if available

apps/ui/src/views/Space/Proposals.vue
This PR uses the `?state=X` query param to persist the proposals page `state` filter
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposals?state=active
2. It should show only active proposals
3. Select another filter in the state dropdown
4. It should refresh the proposals list, and the state query param
5. Passing an invalid value to state query param will be considered as `any`
=> feat: persist proposals state filter in url

apps/subgraph-api/package.json, apps/subgraph-api/src/ipfs.ts
Context https://discord.com/channels/955773041898573854/1030772407226601522/1297968753719640124
Filter out non-string values before doing a .toString()
sepolia subgraph is stuck at block 6,914,255
with error:
```js
A non-deterministic fatal error occured at block 6914256: error while executing at wasm backtrace: 0: 0x2a14 - 
<unknown>!~lib/@graphprotocol/graph-ts/common/value/JSONValue#toString 1: 0x60ec - 
<unknown>!src/ipfs/handleSpaceMetadata~anonymous|3 2: 0x5135 - <unknown>!~lib/array/Array<~lib/assemblyscript-
json/JSON/Value>#map<~lib/string/String> 3: 0x7c20 - <unknown>!src/ipfs/handleVotingPowerValidationStrategyMetadata: Mapping aborted at ~lib/@graphprotocol/graph-
ts/common/value.ts, line 570, column 5, with message: JSON value is not a string. in handler …
```
=> fix: toString() error on strategy metadata

apps/api/src/index.ts
=> chore: disable reset on API

apps/ui/src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/814
This PR disables the space settings controller edition, when the current user is not the controller.
Previously, we could open the modal, change the controller, but clicking on the "Confirm" button was doing nothing.
1. Go to a space settings you are not controller
2. In the controller tab, the edit button to edit the controller should be disabled
3. Go to a space settings you are controller
4. You should be able to edit the space controller
=> fix: disable controller edition when no permission

apps/ui/src/helpers/argentx.ts
This PR fix an error when locking the argent X wallet, when the user is connected with it.
Locking the wallet will disconnect the wallet, but the subsequent `logout()` call will crash with
And result in the user menu being in an invalid state
1. Connect with an argent X wallet
2. Lock the wallet
3. It should log you out properly, without any errors in the console
=> fix: fix error when logging out by locking argent x wallet

apps/ui/src/components/Modal/DelegationConfig.vue
Delegation name is ignored for offchain spaces.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/859
1. Go to your offchain space settings.
2. Add some delegation.
3. There is no name input.
=> feat: remove delegation name for offchain spaces

apps/ui/src/composables/useActions.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/types.ts
`verifyStarknetNetwork` doesn't handle nicely case of it being called on non Starknet connector, but it is possible on master:
1. when deploying dependency on Starknet sometimes we do it through EVM wallet (L1 EthRelayer) - in this case we should limit it to only be called if Starknet connector is used
2. `executeTransactions` - not required - can be called with any wallet or without it as it's done through mana.
3. `executeQueuedProposal` - not required - can be called with any wallet or without it as it's done through mana.
=> fix: only verify starknet networks when starknet connector is required

apps/ui/src/components/ProposalVote.vue, apps/ui/src/components/ProposalsListItem.vue
Fix following error when using `ProposaVote` component
```
proposals.ts:103 [Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
at <ProposalVote proposal=
```
1. Open a space proposals page
2. No more error in the console.log
3. Proposals with basic vote still have `py-2` class, only on proposals list
=> fix: fix passing extraneous props to component

apps/ui/src/views/Proposal/Overview.vue, apps/ui/src/views/Space/Editor.vue
Closes: #933 
This PR fix the "Edit proposal" menu not appearing for pending offchain proposals
1. Go to a pending offchain proposals
2. Click on the 3 dot menu in the proposal heading
3. It should show the "Edit proposal" menu
4. Clicking on it should redirect to the editor, where you can edit the title, body, voting type, choices and labels
5. Submitting the form should update the proposal, and redirect to the proposal page
- Updating an onchain proposal will still redirect back to proposals list page, because of the lag while confirming the tx
=> fix: enable offchain proposal update

apps/subgraph-api/package.json
Already deployed. We lost this bump in choices PR because other API bumped to the same version.
=> chore: bump subgraph-api to 0.0.43

apps/ui/src/components/EditorChoices.vue, apps/ui/src/components/ProposalResults.vue, apps/ui/src/components/ProposalVote.vue, apps/ui/src/components/ProposalVoteBasic.vue, apps/ui/src/components/ProposalsListItem.vue, apps/ui/src/composables/useEditor.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/networks/common/graphqlApi/types.ts, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/workflow/issues/89
- Make basic voting the default voting system
- Add icons for basic voting choices.
- Make choice label editable on basic voting.
- Allow offchain proposals to have 2 options for basic voting (no Abstain).
1. Create proposal on offchain space with custom basic choices, vote on it, edit your vote, check results.
2. 1. Create proposal on onchain space with custom basic choices, vote on it, check results.
=> feat: support custom label for basic voting

apps/api/src/utils.ts, apps/ui/src/composables/useExecutionActions.ts
Fixes issues discovered when working on debugging this issue: https://github.com/snapshot-labs/workflow/issues/267
Looks like there is no issue with execution itself as this task suggests - those are old proposals that were using old contract that didn't include `proposalId` in the message sent to L1 so those won't work.
This PR itself changes two things:
1. You can only try execute once max end has been reached (this is requirement for EthRelayer).
2. `l1DestinationAddress` is now reformatted (because it's stored as string on Starknet it can lose leading zeroes making it incorrect length and it will fail to be stored on Checkpoint.
Closes: https://github.com/snapshot-labs/workflow/issues/267
1. Create new space with EthRelayer (use Safe for avatar, make sure to add matching treasury, …
=> feat: EthRelayer execution fixes

apps/ui/src/views/My/Home.vue
Closes: https://github.com/snapshot-labs/workflow/issues/285
- Show loading when followedSpaces are still loading
1. Disconnect your wallet if you are already connected
2. Go to home page
3. Change network settings to "3G"
4. Connect your wallet
5. You should see "There are no proposal here" before the fix
6. You should see loading icon after the fix
=> fix: home page - show loading when followed spaces are still loading

apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/starknet/constants.ts
- Add min value of `1` for proposal threshold
Closes: #952 
1. Go to your SX space
2. Edit proposal validation
3. Try passing values less than `1`
=> fix: Add minimum value for proposal threshold

apps/ui/src/components/Ui/SelectorNetwork.vue
Depend on and following https://github.com/snapshot-labs/sx-monorepo/pull/946
This PR will hide the "Starknet Sepolia" network in network selector, when using the `s` network, to follow existing pattern of hiding all testnet networks when not relevant
1. Go to an offchain space settings
2. Open the delegation modal
3. The network combolist should contain `Starknet`, but not `Starknet Sepolia`
=> fix: hide testnet network on mainnet

apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/components/Modal/DelegationConfig.vue, apps/ui/src/components/Modal/TreasuryConfig.vue, apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/components/Ui/SelectorNetwork.vue, apps/ui/src/composables/useActions.ts, apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/helpers/validation.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/types.ts
Changes delegations so full list of networks can be used on onchain networks.
- Replaced `contractNetwork` with `chainId`.
- Show full list on delegation selector.
- `contractAddress` now only contains address, without prefix.
Towards https://github.com/snapshot-labs/sx-monorepo/issues/857
1. On onchain space add delegation on different network that is not supported by default (for example Gnosis Chain).
2. It works as expected.
=> refactor: allow any network to be used in delegations

apps/ui/src/components/App/Topnav.vue
Closes: https://github.com/snapshot-labs/workflow/issues/286
- Close account modal when we go to landing page
1. Go to http://127.0.0.1:8080/#/home
2. Connect your wallet
3. Click on Account button
4. Go to landing page http://127.0.0.1:8080/#/
5. Come back to http://127.0.0.1:8080/#/home
6. You should see modal before the fix, but not after
=> fix: close account modal on topnav unmount

apps/mana/src/db.ts, apps/mana/src/stark/index.ts, apps/mana/src/stark/rpc.ts
- Adds a `getDataByMessageHash` method that accepts a `hash` as params and returns all the information required for the user to re-compute his hash independently.
- Modifies `sx.js` in order for the `getProposeHash / getVoteHash / getUpdateProposalHash` methods to accept an `address` instead of a `Signer` (required for the `hash-verifier` to work). Also upgrades the corresponding tests.
Closes: #949 
1. Build locally and use `yarn link` to link with the [hash-verifier](https://github.com/snapshot-labs/hash-verifier) script.
Question: is `getDataByMessageHash` a proper name? Should we find a better name?
=> feat: add getDataByMessageHash data endpoint

apps/mana/src/db.ts
Completing #950  , we forgot to add `sender` to the values returned by `getDataByMessageHash`
=> fix: add sender to the returned info of getDataByMessageHash

.changeset/odd-apples-explain.md, packages/sx.js/src/clients/starknet/ethereum-tx/index.ts, packages/sx.js/test/unit/clients/starknet/ethereum-tx/index.test.ts
Use `address` instead of signer for the ethereum-tx client's methods
For reference: https://github.com/snapshot-labs/sx-monorepo/pull/950#discussion_r1827827446
=> sx.js: use address instead of signer for ethereum-tx methods

apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/types.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Create.vue
Toward https://github.com/snapshot-labs/workflow/issues/274
This PR moves the `terms` property from `OffchainAdditionalRawData` to the main `Space` type, following recommendation by
https://github.com/snapshot-labs/sx-monorepo/blob/fe5d64d546f2d715c7074a0c71e5a57ff932ffa8/apps/ui/src/types.ts#L212-L213
This will prepare the ground for the other PR to:
- use the `terms` property to show a modal
- adds `terms` to onchain space settings
1. Go to an offchain space settings
2. In advanced, edit and save the `terms` field
3. It should save
=> refactor: move Space `terms` property to main Space type 

apps/ui/src/helpers/connectors.ts, apps/ui/src/main.ts
- Allow snapshot inside fantom safe https://safe.fantom.network/
- Allow fantom networks using walletconnect
1. Go to https://safe.fantom.network/apps/custom?safe=ftm:0xEA3fFa8e61Cc58122593D482a7eCaEf74bc68Da9 
2. Connect walletconnect
3. Before fix you should see an error
4. ![image](https://github.com/user-attachments/assets/6ca4a1e7-c7a7-4e57-a6b2-ae390e05c583)
=> fix: Allow snapshot in fantom safe and add fantom networks to WC

packages/sx.js/test/integration/starknet/index.test.ts, packages/sx.js/test/integration/starknet/utils.ts
The issue is with starknetjs implementation of waitForTransaction, that will always take at least 10s with default settings.
We can improve it a lot by just decreasing intervals.
https://github.com/starknet-io/starknet.js/issues/1237#issuecomment-2475861985
1. In sx.js
2. Run `yarn node:starknet`
3. Run `yarn test:integration:starknet`
4. It's actually manageably fast.
=> test: improve speed of starknet integration tests 10x

.github/workflows/test.yml, package.json, packages/sx.js/package.json, packages/sx.js/test/integration/starknet/index.test.ts, packages/sx.js/test/integration/starknet/utils.ts, packages/sx.js/test/run-integration-tests.sh, turbo.json
With this change integration tests will run on the CI.
This also includes few changes:
- Fixed issue with integration tests (avoid sleep), forward time on L1 node.
- Added `test:integration` script.
=> ci: run integration tests on CI

apps/ui/src/components/Combobox.vue, apps/ui/src/components/FormSpaceProfile.vue, apps/ui/src/components/Ui/Dropdown.vue, apps/ui/src/components/Ui/SelectorNetwork.vue, apps/ui/src/composables/useOffchainNetworksList.ts, apps/ui/src/composables/useSpaces.ts, apps/ui/src/helpers/constants.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/types.ts, apps/ui/src/views/My/Explore.vue
This PR adds ability to filter by Network and Category on explore page.
Closes: https://github.com/snapshot-labs/workflow/issues/213
@bonustrack original issue calls for multi-selection on category, but API only supports single category filter, do we want to implement it with multi-selection (would also require changes on the API).
1. Go to http://localhost:8080/#/explore
2. Try different filters.
https://github.com/user-attachments/assets/2ea101a2-4a5c-42e0-b18d-7aac3f199bf6
=> feat: add explore page Category and Network filters

apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/FormSpaceTreasuries.vue, apps/ui/src/components/Modal/SendToken.vue, apps/ui/src/components/Modal/StakeToken.vue, apps/ui/src/components/Modal/TreasuryConfig.vue, apps/ui/src/components/PickerToken.vue, apps/ui/src/components/ProposalExecutionActions.vue, apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/components/SpaceTreasury.vue, apps/ui/src/components/TransactionsListItem.vue, apps/ui/src/composables/useExecutionActions.ts, apps/ui/src/composables/useOffchainNetworksList.ts, apps/ui/src/composables/useTreasuries.ts, apps/ui/src/composables/useTreasury.ts, apps/ui/src/helpers/explorer.ts, apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/types.ts
Now any network should be possible to be used in Treasuries on onchain spaces.
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/946
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/857
1. Go to SX space settings.
2. Create treasuries on some non-SX supported network (Base for example).
3. It shows up in treasuries.
=> feat: allow any network to be used in Treasuries

.github/workflows/release.yml, .github/workflows/test.yml, package.json
We currently use v18 which is a bit old (in JS terms). I'm currently working on some feature that use `Intl.NumberFormat` and some options (`roundingMode`) were added in node v19 so tests are failing with v18.
=> chore: upgrade node to v22

apps/ui/src/composables/useSpaceSettings.ts
Closes: https://github.com/snapshot-labs/workflow/issues/307
https://github.com/snapshot-labs/snapshot/blob/9e4c95e0e001f33328d95e4cb18d82464fdbf156/src/components/ModalValidation.vue#L82-L83
1. Go to http://localhost:8080/#/s:safe.eth/settings/proposal
2. Open validation.
3. Min score is populated.
=> fix: copy minScore from filters to params

apps/ui/src/networks/evm/constants.ts
Closes: https://github.com/snapshot-labs/workflow/issues/291
This way it's clearer for users. Not sure if now description matches, because it mentions avatar (Avatar contract, the most popular one being a Safe), might be confusing if someone actually tries to use non-safe avatar. Maybe it should say `Avatar (eg. Safe) address`? @bonustrack 
1. When configuring space we show Safe instead of Avatar.
=> chore: rename avatar input to safe

apps/ui/src/components/EditorLabels.vue, apps/ui/src/components/PickerLabel.vue, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/types.ts, apps/ui/src/stores/proposals.ts, apps/ui/src/views/Space/Proposals.vue
Closes: https://github.com/snapshot-labs/workflow/issues/254
Re-submission of https://github.com/snapshot-labs/sx-monorepo/pull/910 which was merged, but reverted due to issue with SX api.
This PR is pushing the same changes again, but with some minor fixes to support both onchain and offchain API.
Particularly, onchain API is filtering labels using `metadata.labels_contains`, whereas offchain uses `labels_in`.
1. Go to http://localhost:8080/#/sep:0xb58B05A1c8263441Bd74454544fD66CE25D300AD/proposals
2. You should be able to filter proposals by labels (filtered using AND)
3. http://localhost:8080/#/s:test.wa0x6e.eth/proposals
4. You should be able to filter proposals by labels (as of now, filtered using OR, will use AND once https://github.com/snapshot-labs/snapshot-hub/pull/957 is merged)
=> feat: add labels filter to proposals list

apps/ui/src/networks/starknet/constants.ts, packages/sx.js/src/starknetNetworks.ts
Adds previously not deployed trace 208 oz votes strategy on mainnet Starknet.
1. It's available in Starknet mainnet editor.
2. It works (not tested).
=> feat: add trace208 oz votes strategy to mainnet

apps/ui/src/components/ProposalVote.vue
This PR will truncate long choice text on edit vote message.
Closes: https://github.com/snapshot-labs/workflow/issues/301
1. On offchain create proposal with long choice.
2. Vote on this long choice.
3. Edit message should truncate text.
=> fix: truncate too long choices

packages/sx.js/src/starknetNetworks.ts
=> fix: remove padding on OZ trace 208 voting strategy

apps/ui/src/components/AppLink.vue, apps/ui/src/views/My/Explore.vue, apps/ui/src/views/Settings/Spaces.vue
This PR adds link to create route or https://snapshot.org/#/setup?step=0 for offchain in explore page and settings.
Closes: https://github.com/snapshot-labs/workflow/issues/308
1. Go to Explore page.
2. You can see button for creating new space (works for offchain and onchain).
3. Same in Settings.
=> feat: add create space link on explore page

apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Proposal/Overview.vue
Closes: https://github.com/snapshot-labs/workflow/issues/304
This PR shows a warning message when viewing a flagged proposal
This warning will appear only when accessing flagged proposals directly (knowing the link), as the space's proposals list is already filtering out all flagged proposals
1. Go to http://localhost:8080/#/s:safe.eth/proposal/0x669c3ea414783e16ed98142ba6203a684d6a2e06dbf5e6a6ef372943d75fdf23
2. It should show a warning message above the proposal title
3. Go to any other proposals from the space proposals list
4. It should not show any warnings
=> feat: show warning message for flagged proposals

apps/ui/src/composables/usePropositionPower.ts, apps/ui/src/views/Space/Editor.vue
Toward #939 
This PR extracts the proposition power from the `useVotingPower` into its own composable, and avoid mixing voting and proposing power.
Merging this one first will allow #938 to use the final correct name, without filename collision
1. Everything should work as before
2. Create a proposal on a space you have proposition power, you should be able to create a proposal
3. Create a proposal on a space you do not have proposition power, it should show a message about insufficient proposition power.
=> refactor: create dedicated composable for proposing power

apps/api/src/index.ts
Newer version adds reorg support so also a new database schema so reset is needed to call createStore.
=> chore: bring back API reset

apps/ui/src/views/Space/Editor.vue
This PR migrates the editor right sidebar to use the Affix component, which will scroll the sidebar content together with the main content.
With this changes, all right sidebars are now migrated to Affix
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/create
2. The right sidebar should scroll using same behavior as the proposal page sidebar (stop scrolling when reaching top/bottom)
=> feat: use affix sidebar for editor sidebar

apps/ui/src/stores/votingPowers.ts
This PR fix an issue where admins and moderators couldn't create proposal by default.
Before: admins and moderators are considered like any other proposer, and have to pass the proposal validation (and hold some VP)
after: admins and moderators can always create proposals, regardless of any space settings
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/create
2. Connect as regular member `0xab54624a67e8c018a06b176baae76a40a385a464` account using https://impersonator.xyz/
3. You should see a message about insufficient voting power to create a proposal
4. Connect as a moderator `0x757a20e145435b5bdaf0e274987653aecd47cf37`
5. You should not see any warning message, and the publish button should be enabled
=> fix: always allow admins and moderators to propose

apps/ui/src/composables/usePropositionPower.ts, apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1008
This PR fix an issue where the proposition power was not updating on account change
1. Go to a space editor where you have some VP
2. There is no warning
3. Without leaving the page, change your metamask to another wallet without VP on the space
4. It should show a warning about insufficient VP
=> fix: fix proposition power to updating on account change

apps/ui/src/components/Layout/App.vue, apps/ui/src/views/My/Explore.vue, apps/ui/src/views/My/Home.vue, apps/ui/src/views/Proposal.vue, apps/ui/src/views/Proposal/Votes.vue, apps/ui/src/views/Settings/Contacts.vue, apps/ui/src/views/Settings/Spaces.vue, apps/ui/src/views/Space/Delegates.vue, apps/ui/src/views/Space/Leaderboard.vue, apps/ui/src/views/Space/Settings.vue, apps/ui/src/views/Space/Treasury.vue
Closes: https://github.com/snapshot-labs/workflow/issues/297
This PR fix the gap in the Affix sidebar bottom.
Most of the changes are about adding an encapsulating `<div>` to all views which do not already have it, to allow passing the `pb-6` class to router view, instead of it being set directly on the Layout/App.
This will allow each view to overwrite the bottom padding class if necessary, instead of polluting the App layout.
1. Go to http://localhost:8080/#/s:aave.eth/proposal/0xef7dfa4e96e5f6a7337648d2dd3882f7b10e969c9564c118a34ce99eccec9383
2. Scroll to bottom of the page
3. The right sidebar bottom should go all the way to the page bottom
=> fix: fix gap in proposal sidebar bottom

apps/ui/src/components/Site/Footer.vue, apps/ui/src/networks/offchain/index.ts, apps/ui/src/routes/index.ts, apps/ui/src/views/My/Explore.vue, apps/ui/src/views/Settings/Spaces.vue
Add redirections from v1 URL paths like:
- `/#/safe.eth` to v2 path `/#/s:safe.eth`
- `/#/delegate/safe.eth` to v2 path `/#/s:safe.eth/delegates`
- `/#/safe.eth/proposals` to v2 path `/#/s:safe.eth/proposals`
- `/#/safe.eth/about` to v2 path `/#/s:safe.eth`
Also update snapshot.org URLs to point to v1.snapshot.box and testnet.v1.snapshot.org
=> feat: redirect v1 URL paths to v2

apps/ui/src/networks/offchain/constants.ts
With this change gnosis & walletlink should be supported manager connectors for offchain spaces (editing space settings etc.)
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/986
1. Add your Safe as space admin.
2. Add this PR's preview as Safe app.
3. Navigate to your space through Safe app.
4. You can edit settings.
=> fix: add gnosis & walletlink as managerConnectors for offchain

apps/ui/src/components/Landing/Ecosystem.vue, apps/ui/src/components/Landing/Features.vue, apps/ui/src/components/Landing/Flow.vue, apps/ui/src/components/Landing/Hero.vue, apps/ui/src/components/Landing/Start.vue
Closes: https://github.com/snapshot-labs/workflow/issues/316
- 56px reduced to 40px 
- 44px reduced to 36px
1. Go to landing page
2. No horizontal scrolling anymore on small screen (support 320px minimum)
=> fix: reduce font size on small screen

apps/ui/src/components/FormSpaceStrategies.vue, apps/ui/src/components/Modal/EditStrategy.vue, apps/ui/src/components/Ui/SelectorNetwork.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1029 and https://github.com/snapshot-labs/sx-monorepo/issues/1030
1. Go to offchain space settings
2. Strategies tab
3. Network selector should show offchain networks (should not show testnet networks)
5. On testnet offchain space, you should see both testnet and mainnet networks
=> fix: show offchain networks in network selector

apps/ui/src/views/Proposal/Overview.vue
Closes: https://github.com/snapshot-labs/workflow/issues/322
This PR adds a new button in the proposal overview dropdown menu, to duplicate the current proposal.
1. Go to any proposal
2. Go to the dropdown menu (next to share, under the title)
3. Click om "Duplicate proposal"
4. It should create a new draft, pre-populated with the proposal content
=> feat: add button to duplicate proposal

apps/ui/src/components/FlashMessageWelcome.vue, apps/ui/src/components/Layout/App.vue
Closes: https://github.com/snapshot-labs/workflow/issues/318
This PR adds a new flash message on the bottom right corner, introducing the v2, as well as show link to go back to v1
Once closed, flash message will not appear again (state saved in localStorage)
1. Open the app (not available on landing page)
2. Close the message
3. Message will not appear again on page refresh
=> feat: add flash message introducing v2

apps/ui/src/components/Layout/Site.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/pull/1028#issuecomment-2532568521
This PR will also show the v2 welcome flash message on landing page
1. clear your local storage
2. Go to landing page
3. You should see the v2 welcome message
=> fix: show the v2 welcome message also on landing page

apps/ui/src/composables/useVotingPower.ts
Closes: #940
This PR fix the voting power for offchain pending proposal, which were based on `latest` block, instead of the proposal own snapshot
1. Open the network in the dev console
2. Go to an offchain pending proposal
3. Inspect the payload for `https://score.snapshot.org/`
4. It should use a number as `snapshot`, instead of `latest`
=> fix: voting power for offchain pending proposals should use the proposal snapshot

apps/ui/src/stores/notifications.ts, apps/ui/src/views/My/Home.vue, apps/ui/src/views/My/Notifications.vue, apps/ui/src/views/Settings.vue
Closes: https://github.com/snapshot-labs/workflow/issues/325
This PR will force prompt users to login only page depending on the current wallet (except /home).
- Remove the force login modal on the /home page, will redirect users to /explore page instead
- Add the force login modal on /notifications and /settings/* page, since these page make sense only if wallet is connected, and accessible only with direct link
Also fix a minor issue where logging out while on the /notifications page was not clearing the existing notifications
1. Disconnect your wallet
2. Go to /home
3. You should be redirected to /explore
4. Go to /notifications or /settings
5. You should see the login modal
6. Login
7. Go to /home
8. You should see the /home
=> fix: force user to login only on account dependent page

apps/ui/src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/workflow/issues/330
1. Go there: http://localhost:8080/#/sep:0xEB8EA538C90D2E009460ED69adD7025560E18481
2. You can see 5 proposals.
=> fix: show 5 proposals on overview page

apps/ui/src/components/Breadcrumb.vue
Closes: https://github.com/snapshot-labs/workflow/issues/337
Regression from https://github.com/snapshot-labs/sx-monorepo/pull/1048
1. Go to a space overview and proposal page
2. The avatar in the topnav breadcrumb should not shrink anymore
=> fix: fix space avatar from shrinking

apps/ui/src/components/Modal/DateTime.vue, apps/ui/src/style.scss
Closes: https://github.com/snapshot-labs/sx-monorepo/pull/1015#issuecomment-2531409401
This PR improve the time input UI:
- hides the webkit default control on time input (not tested on non-webkit browsers)
- uses the `s-box` style for the time input
Before
After
1. Go to a date edition in the editor
2. The time picker should appear without the browser default control, and with the same style as all other inputs
=> fix: improve time input UI

apps/ui/src/components/Modal/VotingPower.vue, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/offchain/index.test.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/types.ts, apps/ui/src/stores/votingPowers.ts, apps/ui/src/views/Proposal.vue, apps/ui/src/views/SpaceUser.vue
In case of onchain strategies decimals are only there to specify how
strategy value should be formatted, but it doesn't have effect on how
this value is interpreted (strategy with VP value of 1 and 18 decimals and
strategy with VP value of 1 and 0 decimals are actually the same and give sum
of 2 VP).
We need to separate cumulativeDecimals (used to calculate cumulative VP) and
displayDecimals (used to display specific strategy's value).
Depending on the context one or another needs to be used.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1036
**Onchain**
1. Go to http://127.0.0.1:8080/#/sep:0xa6380C7eC883CC0BcdAaf9f46d6F83Fa872BF700/profile/0x556B14CbdA79A36dC33FcD461a04A5BCb5dC2A70
2. User has 8 AXMVP
3. Impersonate as `0x556B14CbdA79A36dC33FcD461a04A5BCb5dC2A70`
4. Go to …
=> fix: use decimals of each strategy to calculate voting power

apps/ui/src/networks/evm/index.ts
Closes: https://github.com/snapshot-labs/workflow/issues/331
This PR will proxy the network requests to thegraph.com via our subgrapher service, to avoid rate limit on queries without API keys
1. Open network tab in the dev panel
2. Go to http://localhost:8080/#/explore?p=snapshotx&n=all
3. It should onchain spaces
4. Filter the spaces by network
5. It should load the spaces only for the specific network
6. In the dev panel, you should see requests to subgrapher instead of thegraph.com directly
=> fix: proxy thegraph request via subgrapher

apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/views/SpaceUser.vue
Closes: https://github.com/snapshot-labs/workflow/issues/335
This PR adds a button to open the delegate modal from the space user page, to delegate to the current user.
Since a space can have multiple delegation settings, it will show a list of those delegations on the delegation modal when needed. (hidden when only one)
1. Go to http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50/delegates
2. When delegating from the Starknet tab, it should delegate using the starknet settings (no UI changes)
3. When delegating from the Ethereum tab, it should delegate using the ethereum settings (no UI changes)
4. Go to an onchain space user page with multiple delegations: http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e …
=> feat: add button to delegate to user from space user page

apps/ui/src/components/ProposalResults.vue
This PR restore the missing (may be due to some botched merge conflict) feature introduced with #1044
Also show a lock icon instead of votes count for progress
1. PENDING: Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0xf68984180a080d0331c873ea7c48e04c9ef00ca12c95da004fc586e1bcec3b0b
2. It should show results, with LOCK icon instead of results count
3. CLOSED: http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0xfe22dfb4473476dc73ea54cadff7cf1faf30540c4afe97e3292d6e51d38cbfbc
4. It should show the results, with the final votes count
5. ACTIVE: http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x605c475a7aac97c53272ca02e973e5cd5676f0c5abcdc8fdbb2a182f3fe22313
6. It should just show a message instead of results
=> fix: Restore back missing feature where choices for pending shutter proposals are visible

apps/ui/index.html
The `<script>` tag with `var global = global || window;` is placed outside of the `<body>`. It’s better to move it inside the `<body>` or put it in the _<head>_ to avoid potential loading issues.
=> refactor: move script to html tag

apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/helpers/quorum.test.ts, apps/ui/src/helpers/quorum.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts
Onchain spaces only take for and abstain votes into quorum progress. Against votes are not counted.
Offchain spaces take all votes into account (for oSnap/SafeSnap).
1. Go to onchain space with against votes: http://localhost:8080/#/sep:0x3CB9321Ed733dc336A59199b05b2FC29beA8b66B/proposal/2
2. Against is not counted towards quorum, proposal is rejected, you can't execute proposal.
3. Go to onchain space that passed: http://localhost:8080/#/sep:0x3CB9321Ed733dc336A59199b05b2FC29beA8b66B/proposal/4
4. Quorum counts all votes, proposal is passed, you can execute proposal (at least button shows up, I haven't configured execution on Safe).
=> fix: match quorum formula based on contracts

apps/ui/src/composables/useReportDownload.ts, apps/ui/src/views/Proposal.vue
This PR adds functionality to download votes for `s` spaces.
UI is temporary as it wasn't specified in the issue, but functionality should be good.
Currently server returns bad response while report is generated (doesn't return `PENDING_GENERATION`).
This PR contains workaround to handle that response:
```json
{
"jsonrpc": "2.0",
"result": "0",
"id": "0x345d62b550421b53c717ca2ca9b3edd4ebe6a4c12cef0ed26493d5164c22c4c6"
}
```
Closes: https://github.com/snapshot-labs/workflow/issues/336
1. Go to offchain (`s`) space.
2. Go to proposal that has passed.
3. Try downloading it.
4. You will get notification if it's still pending or it will prompt you to download report if it's ready.
Current UI:
=> feat: add download votes button

apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/index.ts, apps/ui/src/views/Proposal/Overview.vue
We currently do not support SafeSnap executions, so when detected we link to v1 UI.
Closes: https://github.com/snapshot-labs/workflow/issues/324
1. Go to http://localhost:8080/#/s:launchdao.eth/proposal/0x2440b546cecc6292c56f55539942f10108831a1d6eff3b90a3603a9a157dbeae
2. You have execution section and link to v1 UI.
=> feat: link SafeSnap executions to old interface

apps/ui/src/helpers/ens.ts
- Gets and validated ENS resolver before settings snapshot text record
1. Go to http://127.0.0.1:8080/#/s:odos.eth/settings/controller
2. Login with resolver address `0x47E2D28169738039755586743E2dfCF3bd643f86` using Safe's wallet connect
3. Change controller to some other address in space settings
4. Transaction on safe should display new resolver address
| ------- | ----- |
| <img width="432" alt="Untitled 8" src="https://github.com/user-attachments/assets/348502ef-0ee6-440f-9795-3b52d6fee4ac" /> | <img width="460" alt="Untitled 9" src="https://github.com/user-attachments/assets/bcf216c6-8566-46d6-845b-d348c7fb69c7" />  |
=> fix: validate resolver address before setting snapshot text record

apps/ui/src/components/ProposalExecutionsList.vue
- previously button was shown when quorum reaches above 100%
- Fix will show the button when it reaches 100%
=> fix: finalize proposal excection button when proposal reaches its quorum

apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/views/Proposal.vue
Issue 1:
- All SX proposals have `completed` field as `undefined` so we display this message on all proposals
- Example space: https://snapshot.box/#/sn:0x07bd3419669f9f0cc8f19e9e2457089cdd4804a4c41a5729ee9c7fd02ab8ab62/proposals
- <img width="1151" alt="image" src="https://github.com/user-attachments/assets/b351a0bd-bd20-4602-b84d-0aadb98680b2" />
Issue 2:
- Also if a proposal is not completed we should not show the download button 
- Example proposal: https://snapshot.box/#/s:thanku.eth/proposal/0x9201a8459b93a29e1e0cf76fb73d5c0364f963a659cdbeed8827cbb50fb5e5f6
- <img width="350" alt="image" src="https://github.com/user-attachments/assets/8bf1472d-bb34-424f-bd4e-abd0af15def6" />
1. Go to [SX space](http://localhost:8080/#/sn:0x07bd3419669f9f0cc8f19e9e2457089cdd4804a4c41a5729ee9c7fd02ab8a …
=> fix: completed field on sx proposals

apps/ui/src/components/Layout/App.vue
Closes: https://github.com/snapshot-labs/workflow/issues/360
1. Run `VITE_WHITE_LABEL_MAPPING='127.0.0.1;balancer.eth' yarn dev`
2. Go to http://127.0.0.1:8080/#/ on incognito 
3. You should not see welcome popup like before
4. Go to http://localhost:8080/#/home
5. You should still see popup
=> fix: hide welcome popup on whitelabel domain

apps/ui/src/views/Space.vue
Closes: https://github.com/snapshot-labs/workflow/issues/361
1. Run `VITE_WHITE_LABEL_MAPPING='127.0.0.1;balancer.eth' yarn dev`
2. Go to http://127.0.0.1:8080/#/ on incognito 
3. You should see  balancer space's favicon
4. Go to http://localhost:8080/#/home
5. You should still see favicon according to route
=> fix: use space favicon on white label domains

apps/ui/src/helpers/etherscan.ts
- Current API works only with Ethereum (if you try to use contract call execution on base, it will ask for ABI instead of fetching it)
- Update etherscan API url to use v2 so it works for multichain with single API key
1. Go to http://127.0.0.1:8080/#/s:nation3.eth/create
2. Use contract call execution on Ethereum using contract `0x524cab2ec69124574082676e6f654a18df49a048`
3. It should get ABI and show methods 
4. Go to http://127.0.0.1:8080/#/base:0xED3b9f4B7AbFd08c0C73b665D732083e63316DfD/create
5. Use contract call execution on base using contract `0x14a03056324c4102b85d175be2fa299f85e18581`
6. It should get ABI and show methods
7. <img width="445" alt="Untitled 7" src="https://github.com/user-attachments/assets/7824f4c2-4cb5-4360-80a3-17d4cb91663c" />
=> fix: Use etherscan API v2 to use it for multichain

apps/ui/src/stores/votingPowers.ts
Closes: https://github.com/snapshot-labs/workflow/issues/348
- Check proposal validation only if address is not a space member
1. Connect with `0xa53D1eED800BD55d15C01733C2647AC77017aaA8` using impersonator
2. Go to http://127.0.0.1:8080/#/s:gitcoindao.eth/create you should not see proposal validation error (different issue)
=> fix: stop checking proposal validation for space members

apps/ui/src/components/EditorTimeline.vue, apps/ui/src/components/ProposalTimeline.vue
`yarn typecheck doesn't work on https://github.com/snapshot-labs/sx-monorepo/pull/954#issuecomment-2571711076
Throws this error:
```bash
ui:typecheck: src/components/EditorTimeline.vue:91:15 - error TS2322: Type 'Space | { created: number; start: number; min_end: number; max_end: number; id: string; network: NetworkID; verified: boolean; turbo: boolean; snapshot_chain_id?: number | undefined; ... 43 more ...; additionalRawData?: OffchainAdditionalRawData | undefined; }' is not assignable to type 'Space | Proposal'.
ui:typecheck:   Object literal may only specify known properties, and 'start' does not exist in type 'Space'.
ui:typecheck: 
ui:typecheck: 91               start,
ui:typecheck:                  ~~~~~
ui:typecheck: 
ui:typecheck:   src/components/ProposalTimeline.vue:17:29 …
```
=> fix: proposal timeline types

apps/ui/src/components/Modal/SelectValidation.vue
Now if unsupported stamp is in the space settings it will be removed from the list (same behavior as on v1).
Closes: https://github.com/snapshot-labs/workflow/issues/349
1. Go to http://localhost:8080/#/s:gitcoindao.eth/settings/proposal
2. You can select some stamps without errors.
3. Apply changes.
4. Open gitcoin passport validation again.
5. What you selected is still there.
=> fix: remove unsupported Gitcoin Passport stamps

apps/ui/src/components/ProposalIconStatus.vue, apps/ui/src/components/ProposalStatus.vue, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/types.ts, apps/ui/src/views/My/Home.vue, apps/ui/src/views/Space/Proposals.vue
Non basic proposals will now use Closed status instead of Passed.
Closes: https://github.com/snapshot-labs/workflow/issues/342
Wasn't sure about icons/colors to be used. Let me know what should be used @bonustrack
1. Go to http://localhost:8080/#/s:veyfi.eth/proposals
2. Go to http://localhost:8080/#/s:veyfi.eth/proposal/0xdfdf20a60f67ee7d55125699121924070e18dd1df65ca7c27b88d1bce52d4f1d
3. Non-basic proposals have Closed status.
=> feat: add closed proposal status for non-basic proposals

apps/ui/src/components/Modal/Vote.vue, apps/ui/src/components/ProposalResults.vue, apps/ui/src/components/ProposalVote.vue, apps/ui/src/components/ProposalVoteApproval.vue, apps/ui/src/components/ProposalVoteChoice.vue, apps/ui/src/components/ProposalVoteRankedChoice.vue, apps/ui/src/components/ProposalVoteSingleChoice.vue, apps/ui/src/components/ProposalVoteWeighted.vue, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/types.ts
Old checks expected no-privacy proposals to use null, but now it's string 'none'.
We have to update checks to match.
Regression form https://github.com/snapshot-labs/sx-monorepo/pull/954
1. Go there: http://localhost:8080/#/base:0x282d013BF31374D0046F04D6a7644d97751ed339/proposal/6
2. It works as expected (results are visible, votes have choice visible, you can use Reason in vote modal).
=> fix: update privacy checks to match new type

apps/ui/src/helpers/discourse.ts
Adds discussions to odos.eth space
1. Go to odos.eth space 
2. you should see discussions page
=> chore: Add odos.eth space's discussions link

apps/ui/src/composables/useSpaceSettings.ts
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1095
1. Go to your space settings
2. Update quorum to `0`
3. Save settings
4. Reload
5. You should see `0` after fix instead `1`
=> fix: Default quorum to zero

apps/ui/src/components/FormSpaceProfile.vue
This PR fix the incorrect max and min length for the space profile voting power symbol field, which was always returning the limit for offchain
1. Go to an offchain/onchain space settings > Profile
2. Focus on the Voting power input
3. The chars counter should show the max limit as 16 for offchain, and 12 for onchain
=> fix: fix wrong voting power max/min length limit

apps/ui/src/components/FormController.vue, apps/ui/src/components/FormNetwork.vue, apps/ui/src/components/FormVoting.vue, apps/ui/src/components/Ui/InputDuration.vue, apps/ui/src/views/Create.vue
Toward https://github.com/snapshot-labs/workflow/issues/151
This PR improves the consistency for the `FormXXXX` components, used in space creation.
Some components are wrapped using `<UiContainerSettings>`, some other are defining its own `<h3>`.
This PR will migrate the remaining components to use `<UiContainerSettings>`, for consistency, and to prepare the components to be reused in the offchain space creation, where the title and description may be a little different.
Also fix a minor issue where the label is too close to the input duration form
1. Go to the space creation page
2. The title H3 for all steps should have the same size and line-height
=> refactor: improve Form component consistency

apps/ui/src/views/Proposal.vue
When proposal is closed (not using basic voting so can't tell if it passed or rejected) we should show download votes button if it's completed.
Closes: https://github.com/snapshot-labs/workflow/issues/390
1. Go to http://localhost:8080/#/s:breadnbutterfun.eth/proposal/0x9739f7de9d32836f0f043978c3befdf963982ade9ca5af04060984e1e4959717
2. Can download votes.
=> fix: show download votes button for closed proposals

apps/ui/src/components/FormSpaceController.vue, apps/ui/src/views/Space/Settings.vue
Toward https://github.com/snapshot-labs/workflow/issues/151
- [refactor] Extract the space controller settings form into is own component, for easier reuse.
- [fix] Disable the space controller edition on offchain space
- [fix] Add a message for offchain for offchain space owner, explaining why the controller can't be changed 
1. Go to an onchain space controller settings
2. Form is disabled if you're not the owner, you can change the controller otherwise
3. Go to an offchain space controller settings
4. Form is always disabled
5. If you are the controller, it will additionally show a message explaining why edition is disabled
=> refactor: extract controller settings form into its own component

apps/ui/src/components/Messenger.vue
Closes: https://github.com/snapshot-labs/workflow/issues/394
Regression from: https://github.com/snapshot-labs/sx-monorepo/pull/1050
1. Go to http://localhost:8080/#/s:ethpoll.eth/proposal/0x2e185a920cdfb7739a76f31c4fbc75bbb4026c5223a32d79932aaae2c3859bd4
2. Messenger icon is visible above sidebar.
=> fix: match messenger z-index to resizable siderbar

apps/ui/src/components/FormController.vue, apps/ui/src/components/FormSpaceController.vue, apps/ui/src/components/Modal/ChangeController.vue, apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/components/Modal/DelegationConfig.vue, apps/ui/src/components/Modal/SendNft.vue, apps/ui/src/components/Modal/SendToken.vue, apps/ui/src/components/Modal/Transaction.vue, apps/ui/src/components/Modal/TreasuryConfig.vue, apps/ui/src/components/Ui/InputAddress.vue, apps/ui/src/helpers/utils.ts, apps/ui/src/helpers/validation.ts, apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/starknet/constants.ts, apps/ui/src/views/Create.vue
This PR adds network icon with network name in tooltip in UiInputAddress.
Closes: https://github.com/snapshot-labs/workflow/issues/290
1. Go to different inputs/modals in space creation form or settings forms.
2. Go to send token/send NFT/contract call modals.
3. Go to delegate voting power modal on delegation page.
4. Inputs have network annotation.
=> feat: add network icon to UiInputAddress

apps/ui/src/views/Space/Settings.vue
This commit updates settings tabs with new order, but also merges previously separate tabs into single entry. In case of previously separate tabs that ended up as single entry title of the tab has been updated to be the same, but we use old description for each.
- Profile - leave as-is (shared)
- Proposal - merge proposal (offchain) and proposal-validation (SX)
- Voting strategies - merge strategies (offchain) and voting-strategies (SX)
- Voting - leave as-is (shared)
- Members - leave as-is (offchain)
- Execution - leave as-is (SX)
- Authenticators - leave as-is (SX)
- Treasuries - leave as-is (shared)
- Delegations - leave as-is (shared)
- Labels - leave as-is (shared)
- Advanced - leave as-is (offchain)
- Controller - leave as-is (shared)
New tab order is:
**Snapshot**: Profile, …
=> feat: reorganize Settings tabs

apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/views/SpaceUser.vue
This PR fix 2 issues:
- Show a different message for spaces using split-delegation: show a link to v1, instead of showing an "invalid settings" message, which is leading users to believe the space is misconfigured, which is not the case.
- For spaces using split-delegation, we should disable the DELEGATE form.
1. Go to a space's user, on a space with supported validation: http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50/profile/0x0799262e608528601e7d269e381c9f909025dbabe23897bb395a64a55f19ea2a
2. It should show the DELEGATE button on the top right corner
3. Go to a space's user, on a space with unsupported validation:
4. http://localhost:8080/#/s:paraswap-dao.eth/profile/0x168F87fBfe36B84E44B9d06278B2aA1CC73d7400
5. The DELEGATE button should …
=> fix: handle unsupported delegation type

apps/ui/src/networks/offchain/index.ts
As requested by signator team,
Signator has updated its IPFS URL path to https://signator.io/ipfs/bafkreibtcg6jbo6dwbai5s5arh74osuf7t522w4lg7fb5nnfb4wgzupfue instead of `?ipfs` query
1. Go to the votes page of any off-chain spaces
2. It should redirect to a new URL instead of old
=> fix: Update signator URL path

apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts
m is used for minutes.
1. Go there: http://localhost:8080/#/s:cow.eth
2. Check proposal timestamps.
=> feat: use "mo" as months abbreviation instead of "m"

apps/ui/src/components/ButtonFollow.vue, apps/ui/src/components/SpacesListItem.vue, apps/ui/src/composables/useSettings.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/types.ts, apps/ui/src/stores/followedSpaces.ts, apps/ui/src/types.ts
Toward https://github.com/snapshot-labs/workflow/issues/315
Some constants, like the limits are currently hard coded.
Those limits are re-used on multiple services, and a new `options` endpoint has been added to the hub, to serve as the only source of truth. (see https://hub.snapshot.org/graphql?query=query%20%7B%0A%20%20options%20%7B%20%0A%20%20name%20%0A%20%20value%7D%0A%7D)
This PR will add a new API to fetch those settings from the hub, and expose them via a new composable.
As demonstration, the follow space module has been refactored to take the new limit into consideration. Implementation of the others settings will come in a later PR.
1. Follow some spaces
2. When reaching the 25 spaces limit, all FOLLOW buttons should be disabled, and show a tooltip with the explanation.
=> feat: pull constant from hub

apps/ui/package.json, apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/composables/useDelegates.ts, apps/ui/src/main.ts, yarn.lock
This PR introduces [VueQuery](https://tanstack.com/query/latest) by porting space delegates to use it.
With this:
1. Fetching data is simplified (loading/error/data/infinite loading is all normalized and handled by vue-query).
2. There is now caching in our queries providing better UX (no more waiting for results to show up after we go back if it was fetched previously).
3. We can invalidate our queries to trigger refetches (although it's not used now as delegating has delay to when it will update in the API).
1. Go to http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/delegates
2. Use different filters, if ending up at the same filter as before data is restored.
3. Go to user profile and go back, list is restored immediately.
=> refactor: fetch space delegates using vue-query

apps/ui/src/components/SpaceDelegates.vue
Closes: #1119 
This PR fix an UI issue on the delegates page (e.g http://localhost:8080/#/s:gitcoindao.eth/delegates) where the delegates statement column was being cut on one line, instead of being trumcated with ellipsis on 2 lines
1. Go to http://localhost:8080/#/s:gitcoindao.eth/delegates
2. The statement should appear on 2 lines, and end with `...` when truncated
=> fix: fix truncated delegate statement

apps/api/package.json
For now we will only have 3 warnings left:
1. One checkpoint related that needs to be fixed upstream (by replacing outdated package, we don't have good replacement though unless we make Apollo Server the default).
2. One WalletConnect related (needs to be fixed upstream to avoid dependency that requires react as per dep).
3. `starknetkit` related one that can be fixed by bumping it to newer version however it breaks the app.
1. Run `yarn install --force`.
=> build: install graphql locally to limit peer deps warnings

apps/ui/src/components/SpaceDelegates.vue
- Added `w-0` to avoid overflow caused by `grow`
- Reduced `Delegates` column width to `80px` instead of `120px` ( which is way more than required)
Closes https://github.com/snapshot-labs/workflow/issues/415
1. Go to http://127.0.0.1:8080/#/s:cow.eth/delegates
2. The table should be responsive like before
3. Overflow of statements should be fixed
| --- | --- |
| ![image](https://github.com/user-attachments/assets/b253a906-051f-46cd-b818-81ce993afa4f) | ![image](https://github.com/user-attachments/assets/0f40de29-de13-4bae-946e-cf4c884e79e1) |
=> fix: delegates table columns width

apps/ui/src/helpers/delegation.ts
We used eth before, but in case it's not enabled we should use any of enabled EVM network.
Closes: https://github.com/snapshot-labs/workflow/issues/422
1. Run UI with `VITE_METADATA_NETWORK=s-tn VITE_ENABLED_NETWORKS=s-tn,sep,sn-sep yarn dev`.
2. Go to http://localhost:8080/#/s-tn:thanku.eth/delegates
3. Delegate to some address (list will be empty https://github.com/snapshot-labs/workflow/issues/423)
4. It works.
=> fix: pick any available evm network for delegation

apps/ui/src/composables/useOffchainNetworksList.ts, apps/ui/src/views/Space/Editor.vue
Closes https://github.com/snapshot-labs/workflow/issues/427
This PR will wait until the list of premium networks are loaded before showing the warning, else all networks will be considered as non-premium
1. Go to http://localhost:8080/#/s:stgdao.eth/create/hvwau
2. It should show only Avalanche as non-premium network, and not all strategies networks for a moment
=> fix: use networks list only once ready

apps/ui/src/networks/offchain/api/index.ts
Before delegation registry only worked for mainnet spaces. Now we have second instance that is used for s-tn spaces.
Closes: https://github.com/snapshot-labs/workflow/issues/423
1. Go to http://localhost:8080/#/s:cow.eth/delegates (mainnet) - it works
2. Go to http://localhost:8080/#/s-tn:thanku.eth/delegates - it works
=> fix: add testnet delegation registry

apps/ui/src/views/Proposal.vue
This PR fix an issue where a watcher inside the proposal page is not being triggered, since the proposal is now fetched async out of the watcher with vue query
1. Go to a proposal with some discussion, like http://localhost:8080/#/s:apecoin.eth/proposal/0xb732d60fcf82a2cd739f94fb76e950734475f08ce7b588e801fae9736f46f636
2. On page load, it should show the discussions count number
3. Navigating internally between some proposals page should refresh the counter
=> fix: fix watcher not being triggered on proposal change

apps/ui/src/components/Combobox.vue, apps/ui/src/components/FormController.vue, apps/ui/src/components/Modal/ChangeController.vue, apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/components/Modal/DeleteSpace.vue, apps/ui/src/components/Modal/SendNft.vue, apps/ui/src/components/Modal/SendToken.vue, apps/ui/src/components/Modal/Transaction.vue, apps/ui/src/components/Ui/Form.vue, apps/ui/src/components/Ui/InputAddress.vue, apps/ui/src/components/Ui/InputAmount.vue, apps/ui/src/components/Ui/InputCheckbox.vue, apps/ui/src/components/Ui/InputColor.vue, apps/ui/src/components/Ui/InputDuration.vue, apps/ui/src/components/Ui/InputNumber.vue, apps/ui/src/components/Ui/InputString.vue, apps/ui/src/components/Ui/Select.vue, apps/ui/src/components/Ui/SelectMultiple.vue, apps/ui/src/components/Ui/Textarea.vue, apps/ui/src/components/Ui/WrapperInput.vue, apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/workflow/issues/439
This PR adds a `*` next to the label of mandatory form fields
=> fix(ui): add marker for mandatory form fields

apps/ui/src/components/SpaceCreateSnapshot.vue, apps/ui/src/components/SpaceCreateSnapshotX.vue, apps/ui/src/components/Ui/ContainerSettings.vue
Toward https://github.com/snapshot-labs/workflow/issues/437 
This PR removes the title and description in the PROFILE section, while creating a space, and removes the `text-md leading-6` from the step title
=> fix: remove title in space profile step

apps/ui/src/components/Combobox.vue, apps/ui/src/views/My/Explore.vue
- Show network logo in network selector everywhere
- Adjust width dynamically on explore page
Closes https://github.com/snapshot-labs/workflow/issues/426
Closes https://github.com/snapshot-labs/workflow/issues/434
1. Go to explore page, network selector should use dynamic width
2. ![image](https://github.com/user-attachments/assets/4e087032-3123-428b-8dea-77b0885031b6)
3. Go to strategies settings page, network selector should display network logo
4. <img width="627" alt="image" src="https://github.com/user-attachments/assets/46bdabd8-ea6a-4b65-9aa5-33b688c31ee7" />
5. Edit any strategy
6. <img width="550" alt="image" src="https://github.com/user-attachments/assets/1d774682-1837-4818-b8a5-ceb263c39ee5" />
7. Go to http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c …
=> fix: show network logo and apply dynamic width to network selector

apps/ui/src/components/EnsConfiguratorOffchain.vue, apps/ui/src/components/Ui/Stepper.vue, apps/ui/src/views/CreateSpaceSnapshot.vue
Toward https://github.com/snapshot-labs/workflow/issues/437
This PR removes the "Getting started" step, in offchain space creation.
Since this removed step was also ensuring that only logged in users can move to step 2 before, a message was added in the ENS step for guest users, asking them to login
1. Go to http://localhost:8080/#/create/snapshot
2. The "Getting started" step was removed, and the first step is now ENS name
3. In logged in, it should show your ENS names as before, else, it will show a message asking you to log in
=> fix: remove the offchain getting started step in space creation

apps/ui/src/components/Modal/LabelConfig.vue, apps/ui/src/components/Ui/InputColor.vue, apps/ui/src/helpers/utils.ts, apps/ui/src/helpers/validation.ts
This PR adds a few improvements to the color input, following comments/reviews in the other PR (https://github.com/snapshot-labs/sx-monorepo/pull/1153)
- Add a native color picker when clicking on the color preview, which is sync with the input value
- Add a new option to the definition, to control when to show the "generate random color" control
- Move the default value out of the input (default random color is set by the component using the InputColor, and not triggered inside the Input anymore), to allow empty default color
1. Go to the label edition modal in the space settings
2. It should set a random default color when empty
3. Clicking on the color preview will open the OS color picker
4. Picking a color from that picker will fill the input
=> feat: improve color input

apps/mana/src/constants.ts, apps/mana/src/db.ts, apps/mana/src/index.ts, apps/mana/src/stark/index.ts, apps/mana/src/stark/networks.ts, apps/mana/src/stark/rpc.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/helpers/mana.ts, apps/ui/src/networks/common/helpers.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/evm/constants.test.ts, apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/starknet/constants.test.ts, apps/ui/src/networks/starknet/constants.ts, apps/ui/src/networks/types.ts, packages/sx.js/src/strategies/starknet/erc20Votes.ts, packages/sx.js/src/strategies/starknet/evmSlotValue.ts, packages/sx.js/src/strategies/starknet/merkleWhitelist.ts, packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts, packages/sx.js/src/strategies/starknet/vanilla.ts, packages/sx.js/src/types/index.ts, packages/sx.js/src/utils/merkletree.ts, packages/sx.js/src/utils/strategies.ts, packages/sx.js/test/integration/starknet/utils.ts, packages/sx.js/test/unit/strategies/starknet/merkleWhitelist.test.ts, packages/sx.js/test/unit/utils/merkletree.test.ts
In some cases merkle tree is hard to compute (example Starknet with 63k entries). It takes around 5 minutes to generate all entries hashes and precompute tree). All this generation was synchronous previously and would cause issues:
1. Saving settings would freeze the app.
2. Voting/proposing will freeze the app (because proof is being computed from raw tree).
3. Voting/proposing will freeze mana (because Mana generates payload for voting for StarkTx client).
This PR addresses this by moving tree computation to the server, preventing UI from freezing and speeding up voting/proposing, necessary changes were:
1. Different way of computing merkle tree so it can be computed and persisted (functionally the same, but differences come from the lack of insertion of "0x0" entries at levels with odd …
=> feat: use precomputed merkletree on Starknet

apps/ui/src/components/Modal/LabelConfig.vue, apps/ui/src/components/Ui/InputColor.vue
When adding a new label, the label preview was missing the background color.
This PR fix this issue, by generating and setting the default color in the form ref, instead of the definition default
1. Go to a space settings, and add a new label
2. The label preview should have the same background color as the color in the input color
=> fix: fix missing default color in label modal

apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/evm/index.ts, packages/sx.js/src/evmNetworks.ts
With this change it won't be visible in space settings and no request will be made to Highlight API.
Closes: https://github.com/snapshot-labs/workflow/issues/414
1. Go to http://localhost:8080/#/create/snapshot-x, select Ethereum Sepolia go to Executions - no Axiom/Isokratia visible.
2. Go to http://localhost:8080/#/sep:0x3CB9321Ed733dc336A59199b05b2FC29beA8b66B, no requests to Highlight API.
=> chore: remove Axiom/Isokratia from UI

apps/ui/src/components/FormSpaceProfile.vue, apps/ui/src/networks/offchain/api/index.ts
When an offchain space is created without voting power symbol, going to the new space settings will show that the settings are invalid by default, without dirtying the form (see toobar in page bottom)
See https://snapshot.box/#/s:%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86.wa0x6e.eth/settings 
1. Go to https://snapshot.box/#/s:%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86.wa0x6e.eth/settings
2. After PR, space profile is valid
=> fix: allow empty voting power symbol in space settings

apps/ui/src/components/ProposalsListItemHeading.vue, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Proposal/Overview.vue
This PR adds labels for author role if author is a member. It will show up for offchain spaces.
Closes: https://github.com/snapshot-labs/workflow/issues/429
1. Go to offchain space that has members defined and proposals from those members (http://localhost:8080/#/s:0cf5e.eth/proposals)
2. It shows up in proposals lists and on proposal overview.
=> feat: show labels for members

apps/ui/src/components/Breadcrumb.vue, apps/ui/src/components/FormSpaceWhitelabel.vue, apps/ui/src/components/Ui/InputStamp.vue, apps/ui/src/components/Ui/Select.vue, apps/ui/src/components/Ui/Stamp.vue, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/queries.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/types.ts, apps/ui/src/views/Space/Settings.vue
This reverts commit a901721ec185d78853c3dd236b696dc4cf5a5398.
The commit about skin settings edition has been reverted, due to sequencer rejecting payload when non-turbo spaces has a `skinSettings` property.
This PR will re-submit the same PR, with a patch to remove the `skinSettings` payload from the space settings object before submitting, for non-whitelabel spaces (= space without existing domain, or non-turbo spaces)
1. Save a regular space with whitelabel disabled
2. It should save, and in the sequencer payload, the `skinSettings` params should be missing from the payload
3. Save a whitelabel space
4. It should save, and the `skinSettings` params should be present in the sequencer payload
=> Reapply "feat: add form to update skin settings (#1148)" (#1192)

apps/ui/src/components/App/Nav.vue, apps/ui/src/composables/useSpaceController.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/views/Space/Settings.vue
This PR reduces number of requests made to RPC node on offchain spaces when checking for controller.
This is achieved by addition of `useSpaceController` composable that managed fetching space controller and caches it
via `vue-query`. I also added stale time to this query so it will be cached for 1 minute.
This way space controller fetched for `Nav` and `useSpaceSettings` will use only single call (or 3 depending on ENS configuration), instead of double that.
Additionally `isOwner` is now lazy computable so when `useSpaceSettings` it won't be computed (in some cases it results in 2 RPC calls) unless used (for example `OnboardingSpace` uses that composable but doesn't need `isOwner`).
Closes: https://github.com/snapshot-labs/workflow/issues/448
1. Have …
=> refactor: reduce number of RPC calls for controller checks

apps/ui/src/components/Modal/SelectValidation.vue, apps/ui/src/components/ProposalValidationConfigurator.vue, apps/ui/src/helpers/constants.ts, apps/ui/src/networks/offchain/constants.ts
Discussion https://discord.com/channels/955773041898573854/1031838169282392144/1343016499639750727
Following https://github.com/snapshot-labs/score-api/pull/1268
This PR will drop support for the arbitrum proposal validation 
1. Go to an offchain space settings, and open the proposal validation modal
2. `arbitrum` is missing from the list
=> fix: remove arbitrum proposal validation support

apps/ui/src/components/Ui/Calendar.vue
Closes: https://github.com/snapshot-labs/workflow/issues/459
1.  Open calander
2. Go to next month
| --- | --- |
| ![image](https://github.com/user-attachments/assets/2a9afe3e-0c76-4084-9458-6bbb897b9718) | ![image](https://github.com/user-attachments/assets/0df0a430-c372-4eb0-a332-9683f3e8054a) |
=> fix: display today mark only in current month

apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/workflow/issues/458
This PR will not redirect the users to the space proposal page when submitting a proposal as guest. 
The modal will now open in the Editor
1. Submit a proposal as guest
2. It should open the login modal, without redirection
=> fix: do not redirect to proposals page when submitting a proposal as guest

apps/ui/src/composables/useSpaceSettings.ts
Previously it was possible to quickly modify state from unmodified to modified that it would result in isModified to be false.
This is now avoided by usage of computedAsync. Previously isModified was false while it was being computed so we do the same here, using isModifiedEvaluating ref.
Closes: https://github.com/snapshot-labs/workflow/issues/460
You can use `Hide whitespace` to make diff easier for review:
1. Go to SX space that you can edit settings for.
2. Add `!` space name.
3. **Quickly** remove `!` and add it back in.
4. Save button is visible (previously it would not show up).
=> fix: use computedAsync for isModified to handle concurrent callbacks

apps/ui/src/networks/offchain/actions.ts
Closes: https://github.com/snapshot-labs/workflow/issues/461
1. Go to http://localhost:8080/#/s:stakersunion.eth/proposal/0x45bbcac34dd8e32080815692720ba28bf1651aa7f846c280446197a0a68d8c93
2. Use matamask wallet (remove gnosis chain from networks list)
3. You should still be able to vote without error
4. Use sequence wallet
5. You should still be able to vote
=> fix: ensure network verification only for sequence provider

apps/ui/src/components/FormSpaceWhitelabel.vue, apps/ui/src/components/Ui/InputStamp.vue
Closes: https://github.com/snapshot-labs/workflow/issues/464
This PR fix an issue where the stamp input field is using a fixed size, breaking layout on small sceeen.
1. Go to your space settings > whitelabel on a small screen
2. The custom logo input field is max 380px, and responsive on small screen
=> fix: fix ui stamp input dimension on small screen

apps/ui/src/components/Modal/Strategies.vue, apps/ui/src/components/SetupStrategiesConfiguratorOffchain.vue, apps/ui/src/components/Ui/StrategiesConfiguratorOffchain.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1193
This PR hides the `ticket` strategy from the strategies list on offchain space creation.
Offchain space creation does not have the vote validation step, required to setup this strategy.
1. Go to http://localhost:8080/#/create/snapshot and to the strategies step
2. Add a strategy
3. The `ticket` strategy should be unavailable
4. Go to your offchain space settings > strategies > open the add strategy modal
5. The `ticket` strategy should be available
=> fix: hide ticket strategy in offchain space creation

apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1227
1. Go go editor
2. Right sidebar border should go all the way to the bottom
3. On smaller screen, the help icon should not overlap with the sidebar content
=> fix: remove extra bottom padding in editor

apps/ui/src/components/ProposalResults.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1156
This PR fix an issue where the "finalizing vote" message is showing in the proposal list
1. Go go http://localhost:8080/#/s:frami.eth/search?q=poi+list
2. It should not show the "finalizing results" message in the proposals list
3. Go to http://localhost:8080/#/s:frami.eth/proposal/QmXLRQ3AibPJiLzqYz2vykTGvYS5e7PYJicnTA8cgmqQpA
4. It should show the "finalizing message" in the sidebar
=> fix: hide finalizing vote message from proposal list

apps/ui/src/views/Space/Overview.vue
Remove unwanted link on avatar
Closes: https://github.com/snapshot-labs/workflow/issues/465
1. Go to space overview http://localhost:8080/#/s:walletconnect.eth
2. Should not show hand mouse on space avatar
3. Test in mobile
4. Test with whitelabel
=> fix: remove link on avatar in space overview

apps/ui/src/components/ProposalsList.vue, apps/ui/src/queries/proposals.ts, apps/ui/src/views/My/Home.vue, apps/ui/src/views/Space/Overview.vue, apps/ui/src/views/Space/Proposals.vue, apps/ui/src/views/Space/Search.vue
This PR refactors Home page proposals to be fetched with vue-query.
Also added `isError `state to proposals list.
Closes: Towards
1. Go to http://localhost:8080/#/
2. Sign in.
3. You see proposals from followed (offchain) spaces.
4. Switching between Home and Explore pages you don't see loading states.
5. Status filter works.
6. Clicking on proposal from the list opens proposal without loading.
=> refactor: use vue-query to fetch Home page proposals

apps/ui/src/components/FormSpaceStrategies.vue
Closes: https://github.com/snapshot-labs/workflow/issues/471
This PR removes the extra margin in the space voting strategies 
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/settings/voting-strategies
2. There is no extra margin in the voting strategies list
3. Go to http://localhost:8080/#/create/snapshot > strategies
4. There is a margin, like all other steps
=> fix: remove extra margin in offchain voting strategies

apps/ui/src/helpers/connectors/coinbase.ts
1. Login using coinbase, but cancel the connection inside the coinbase modal
2. In the console panel, should not have any other error than the 4001 error
=> fix: remove legacy code from old coinbase version

apps/ui/src/queries/proposals.ts, apps/ui/src/views/My/Home.vue
When not following any spaces we should show message about no proposals instead of error. 
Closes: https://github.com/snapshot-labs/workflow/issues/481
1. Go to http://localhost:8080/#/ with account that has no follows.
=> fix: show no proposals message if user has no follows

apps/ui/src/components/StrategiesConfigurator.vue, apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/types.ts, packages/sx.js/src/authenticators/evm/ethSig.ts, packages/sx.js/src/authenticators/evm/index.ts, packages/sx.js/src/evmNetworks.ts, packages/sx.js/src/types/networkConfig.ts
Our previous EVM EthSig authenticators didn't support EIP-1271 which meant contract signatures (like from Safe wallets)
were not supported.
EIP-1271 support was added on the contract side [here](https://github.com/snapshot-labs/sx-evm/pull/254). This PR adds support for it on the UI. Old versions will continue to work but will be marked by legacy and won't be possible to be added to new spaces.
Closes: https://github.com/snapshot-labs/workflow/issues/329
1. Run local mana and use it in .env for UI.
2. Edit your space so you have VP to propose/vote with your Safe, and remove legacy EthSig authenticator.
3. Connect with your Safe (via Safe app or via WalletConnect - in case of WC you need to disable on chain signatures).
4. Try proposing or voting.
5. You get prompted in Safe to sign your …
=> feat: add EthSig authenticator with EIP-1271 support

apps/ui/src/helpers/constants.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/networks/evm/index.ts, apps/ui/src/networks/index.ts, apps/ui/src/networks/starknet/index.ts, apps/ui/src/networks/types.ts, apps/ui/src/queries/spaces.ts, turbo.json
This PR moves UI to use unified API.
Currently used instance only contains mainnet spaces (excluding Mantle), so trying to access testnet spaces will result in 404.
API is a bit slow, I will see if we can improve it.
Closes: https://github.com/snapshot-labs/workflow/issues/155
1. Go to explore page.
2. Select SnapshotX -> All Networks.
3. Only one API is queried.
4. You see results from all networks sorted by votes.
5. There is working pagination.
6. Other stuff works as well.
=> feat: use unified API for all SX spaces

apps/api/package.json, yarn.lock
This should fix issue with broken reorg handling in multi-indexer setup.
=> chore: bump checkpoint to 0.1.0-beta.52

apps/ui/src/views/Space/Leaderboard.vue
Replaces https://github.com/snapshot-labs/sx-monorepo/pull/1254 because I didn't notice AI was taking over.
Towards: https://github.com/snapshot-labs/workflow/issues/410
1. Go to http://localhost:8080/#/s:aave.eth/leaderboard
2. It fetches as expected, sorting works.
=> refactor: fetch space leaderboard using vue-query

apps/ui/src/components/EditorVotingType.vue, apps/ui/src/components/FormSpaceVoting.vue, apps/ui/src/components/Modal/SelectVotingType.vue, apps/ui/src/helpers/constants.ts, apps/ui/src/networks/offchain/constants.ts, apps/ui/src/types.ts, apps/ui/src/views/Space/Editor.vue
Closes https://github.com/snapshot-labs/workflow/issues/487
- Added "beta" label for Copeland voting type
- Updated voting types order to show Copeland after ranked choice
- Removed filtering of Copeland voting type to display it on production
- Go to your space settings
- You should always see Copeland voting type after ranked choice
- You should see "beta" tag for copeland
- Should be same while proposal creation
=> feat: add beta tag for copeland voting type and allow in production

apps/ui/src/helpers/connectors/coinbase.ts
Use deconstuction to import coinbase sdk
Also remove the duplicate check, should be unnecessary on v4, will put back if we get this bug again.
=> fix: improve coinbase lazy import

apps/ui/src/networks/offchain/api/index.ts
- https://snapshot.box/#/s:metislayer2.eth/proposal/0x3fe7f9f946a9157d37093c6800e39cb3a4f8f7094c06a1d73ee53804e80f49b9 
- This proposal is displaying "Rejected" based on Basic voting type but ignoring the "Quorum of rejection" 
If a proposal is using "Quorum of rejection" display either "Passed" or "Rejected"
1. Go to http://localhost:8080/#/s:metislayer2.eth/proposal/0x3fe7f9f946a9157d37093c6800e39cb3a4f8f7094c06a1d73ee53804e80f49b9 and 
http://localhost:8080/#/s:usualmoney.eth/proposal/0x1b1938083ec6b3f630b888d6d7d756aff26f0a0a693ed8f97caf835d04dc1018
2. You should see passed instead of rejected 
3. [Proposal with quorum of rejection and quroum less than 100% + Basic voting](http://localhost:8080/#/s:usualmoney.eth/proposal/0x1b081d3b3dd611094e96b690dc5d981d86bb724cce5ef562d9eecbe580b535 …
=> fix: quorum of rejection should default to passed state if quorum is not reach

apps/ui/src/components/ProposalResults.vue
- Originally reported by Aura, for this [proposal](http://localhost:8080/#/s:gauges.aurafinance.eth/proposal/0xcb1770f2c1f1a2d822d0eed697149bbefc8cef6d702a94ccd8fdf0887128bc40)
- Was showing results for score_state with `pending` state + non basic proposals
- Instead, it should show the "Finalizing results" message
1. Go to http://localhost:8080/#/s:aave.eth/proposal/0x95a80ac25f97e0fc06528452e2c33d7cc179b801ddc4d8dd164964ce8e1d450e/votes
2. Before the fix, You should see results even if `scores_state` is `pending`
3. After the fix, you should see "Finalizing results"
=> fix: include 'closed' state in finalizing logic

apps/api/package.json
This adds `dev:debug` script that will run API with inspect breakpoint.
1. Run `yarn dev:debug` in `apps/api`.
2. Go to `chrome://inspect`.
3. You can attach to debugger.
=> build: add dev:debug script to api

apps/ui/src/queries/votingPower.ts
It used to be the case, but this check got flipped in https://github.com/snapshot-labs/sx-monorepo/pull/1220
https://github.com/snapshot-labs/sx-monorepo/pull/1220/files#diff-a5eb90aaca074d576a85d84efe9da82dc0aaf9a1563ff46112f858f8b8028b7cL14-L22
1. Go to (while it's pending) http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/proposal/8
2. Sign in with Starknet wallet.
3. Voting power is visible.
=> fix: use null snapshot for onchain pending proposals

apps/ui/src/queries/votingPower.ts
This error is just used to convey information.
We shouldn't retry if we see it.
1. Go to (while it's pending) http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/proposal/8
2. Sing in with Metamask wallet.
3. You see your VP quickly.
4. You don't see multiple requests to Infura with error `Timestamp not cached`.
=> fix: do not retry fetching VP on NOT_READY_YET error

apps/api/.env.example, apps/api/package.json, apps/api/src/api.ts, apps/api/src/index.ts, apps/api/src/indexer.ts, apps/ui/src/helpers/constants.ts, yarn.lock
Closes: https://github.com/snapshot-labs/workflow/issues/502
Closes: https://github.com/snapshot-labs/workflow/issues/496
This PR adds API changes:
- Indexer is now enabled by `IS_INDEXER` flag. If not used only API will be started.
- API now supports `DATABASE_URL_INDEX` flag that allows it to switch between provided database URLs (`DATABASE_URL_N`).
- API now supports `/deployment` endpoint that returns `DATABASE_URL_INDEX` to be able to track which underlying indexer is being used.
- UI will use separate app that hosts only API. Those apps are now running under `api.snapshot.box` and `testnet-api.snapshot.box`.
- Migrations to new API will be made by adjusting `DATABASE_URL_INDEX` in GraphQL API app.
- Mantle is now available again.
This includes couple fixes in Checkpoint:
- linking …
=> refactor: migrate to new unified APIs

apps/ui/src/components/Breadcrumb.vue, apps/ui/src/components/Layout/App.vue, apps/ui/src/composables/useWhiteLabel.ts
Closes: https://github.com/snapshot-labs/workflow/issues/506
This PR will adds whitelabel support for onchain spaces, albeit only hardcoded for now.
All whitelabel features are supported.
1. Run 
```diff --git a/apps/ui/src/composables/useWhiteLabel.ts b/apps/ui/src/composables/useWhiteLabel.ts
index e1ff9984..6a82299e 100644
--- a/apps/ui/src/composables/useWhiteLabel.ts
+++ b/apps/ui/src/composables/useWhiteLabel.ts
@@ -7,7 +7,7 @@ const domain = window.location.hostname;
// Hardcoded white label mappings for onchain spaces
const MAPPING = {
-  'vanilla.box': {
+  '127.0.0.1': {
network: 'base',
id: '0x8cF43759f3d4E72cB72cED6bd69cCe43d4428264',
skinSettings: {
```
2. ```yarn dev```
3. the app will start with the `0x8cF43759f3d4E72cB72cED6bd69cCe43d4428264` space as whitelabel, with …
=> feat: add hardcoded whitelabel support for onchain spaces

apps/ui/src/components/SpaceDelegates.vue
Now should work until width of 340px (iPhone SE is 375px).
Previously it would start getting broken below 450px.
It uses hard-coded widths because it looks like it's the way we synchronize table header and items.
Closes: https://github.com/snapshot-labs/workflow/issues/516
1. Go to http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/delegates
2. UI looks on smaller screens (sub 450px - up until 340px).
https://github.com/user-attachments/assets/4918b6ef-527a-46cd-a203-2937942cbdfa
https://github.com/user-attachments/assets/b5ca575a-091c-4e64-b3f7-674b78dbdc29
=> fix: improve SpaceDelegates layout on small screens

apps/ui/src/components/Layout/App.vue, apps/ui/src/style.scss
Closes: https://github.com/snapshot-labs/workflow/issues/504
1. scroll the page and open any modal
2. the page should not scroll back to the top when opening the modal
- these is a small issue, where all `fixed` element are not taking the scrollbar width into account, resulting in a margin right 15px smaller, on modal open.
=> fix: fix page scroll to top on modal opening

.changeset/gold-papayas-fly.md, apps/api/package.json, apps/api/src/evm/abis/IExecutionStrategy.json, apps/api/src/evm/ipfs.ts, apps/api/src/evm/utils.ts, apps/api/src/evm/writers.ts, apps/api/src/schema.gql, apps/api/src/starknet/writers.ts, apps/ui/src/components/Modal/CustomStrategy.vue, apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/composables/useActions.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/helpers/ui.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/evm/index.ts, apps/ui/src/networks/offchain/index.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/starknet/index.ts, apps/ui/src/networks/types.ts, apps/ui/src/views/Proposal/Overview.vue, apps/ui/src/views/Space/Settings.vue, packages/sx.js/src/executors/index.ts, yarn.lock
Closes: https://github.com/snapshot-labs/workflow/issues/470
This PR adds ability to add custom execution strategy to EVM spaces.
This required couple of changes:
1. `treasuries` and `execution_strategy_details` are now persisted on proposal so changing executors or treasuries at space level won't cause changes in existing proposals.
2. Custom strategies can be deployed without proxy. When execution strategy is added to space it will be fetched and data will be read from it to create ExecutionStrategy entity on API.
3. Separated `isExecutorSupported` and `isExecutorActionsSupported` helpers. First one specifies if executor can be used to create execution, second one specifies if actions (like Execute transactions on passed proposals) are supported.
4. Added modal to add custom strategies …
=> feat: add custom strategies support

apps/api/package.json, yarn.lock
This version includes fix for crash during reorg handling.
=> chore: bump @checkpoint-labs/checkpoint to 0.1.0-beta.56

apps/api/src/evm/config.ts
For computation of topic indexed modifier is omitted.
Because of this OwnershipTransferred event wasn't indexed.
=> fix: update OwnershipTransferred event signature

apps/mana/knexfile.ts, apps/mana/migrations/20250328123634_create_registered_transactions_table.ts, apps/mana/migrations/20250328123755_create_registered_proposals_table.ts, apps/mana/migrations/20250328123900_create_merkletree_requests_table.ts, apps/mana/migrations/20250328124001_create_merkletrees_table.ts, apps/mana/package.json, apps/mana/src/db.ts, apps/mana/src/index.ts, apps/mana/src/knex.ts
Currently it's not great when we need to make some changes to database schema on prod when we can't just drop the database.
Adding migrations so changes (like adding `chainId` to merkletrees) can be done smoothly.
=> feat: set up migrations for Mana

apps/api/package.json, apps/api/src/common/ipfs.ts, apps/ui/src/networks/common/graphqlApi/index.ts, yarn.lock
Depends on: https://github.com/checkpoint-labs/checkpoint/pull/353
This PR addresses various issues related to proposal validation strategies mostly caused by unstable ordering, which has been now addressed at Checkpoint (now entities are sorted by `block_range`).
Testing against unstable ordering is problematic because it can't be reproduced reliably, but it should be addressed by the following changes:
Newest entries are now last in results.
For proposal validation strategies metadata we take last N items as current.
If we use try to reuse existing entities it can result in issues, for example:
1. Add whitelist strategy (ID: `0x001/0/ipfs-hash-1`).
2. Remove whitelist strategy and add ERC20 strategy (ID: `0x001/0/ipfs-hash-2`).
3. Remove ERC20 strategy and add *same* whitelist strategy …
=> fix: make strategies order stable

apps/api/src/common/utils.ts, apps/api/src/evm/writers.ts, apps/api/src/schema.gql, apps/api/src/starknet/writers.ts
This PR adds `networks` entity to API so you can keep track of `space_count`, `proposal_count`, `vote_count`.
Closes: https://github.com/snapshot-labs/workflow/issues/377
1. Run API with `yarn dev:interactive`.
2. Let it run for a while.
3. Run following query:
```graphql
{
networks {
id
_indexer
space_count
proposal_count
vote_count
}
}
```
=> feat: add global counters in API

apps/ui/src/components/ProposalsListItemHeading.vue, apps/ui/src/helpers/constants.ts, apps/ui/src/helpers/ens.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/types.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/types.ts, apps/ui/src/views/Proposal/Overview.vue
This PR changes how we handle proposals without metadata.
Now they will be displayed with placeholder values.
At the same time it will be marked as invalid and appropriate label and message will be displayed on the UI.
If proposal also includes execution different messaging is used prompting users to reject it.
Closes: https://github.com/snapshot-labs/workflow/issues/498
1. Go to http://localhost:8080/#/sep:0xB6f74Cf069E382E81834bBF4544277D2FC65b088
2. You see 3 proposals, 2 of them are flagged.
3. Go to first proposal, no message, it's valid proposal.
4. Go to second proposal, message is visible (it's invalid proposal without execution).
5. Go to third proposal, different message is visible (it's invalid proposal **with** execution).
=> feat: display proposals without metadata

.changeset/fluffy-dogs-shake.md, .changeset/loud-shoes-attend.md, apps/mana/src/eth/rpc.ts, apps/ui/package.json, apps/ui/src/helpers/whitelistServer.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/starknet/constants.ts, packages/sx.js/src/clients/evm/ethereum-sig/index.ts, packages/sx.js/src/clients/evm/ethereum-tx/index.ts, packages/sx.js/src/clients/evm/types.ts, packages/sx.js/src/strategies/evm/index.ts, packages/sx.js/src/strategies/evm/merkleWhitelist.ts, packages/sx.js/test/integration/evm/index.test.ts, packages/sx.js/test/integration/evm/utils.ts, packages/sx.js/test/unit/clients/evm/ethereum-sig/__snapshots__/index.test.ts.snap, packages/sx.js/test/unit/clients/evm/ethereum-sig/index.test.ts
This PR moves computation of EVM merkletrees to [whitelist-server](https://github.com/snapshot-labs/whitelist-server).
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/1303
Closes: https://github.com/snapshot-labs/workflow/issues/517
1. Run local UI and Mana (using `yarn dev:interactive`).
2. Copy whitelist from https://snapshot.box/#/base:0x282d013BF31374D0046F04D6a7644d97751ed339/settings/voting-strategies
3. Add it your space as voting strategy, before saving check voting strategy params is equals to `0xd94deeb88599f74495bb0b5eca0c62c8b3468f15afeffb8bad4714137535ecea` (same as before).
4. Create new proposal (if you are in that whitelist, if not add yourself first).
5. Vote on this proposal.
6. It works.
=> feat: use whitelist server to compute EVM merkletrees

apps/ui/src/networks/offchain/api/index.ts
- Adjusted logic to return 'closed' for non-basic proposals
1. Go to http://localhost:8080/#/s:citizenshouse.eth/proposal/0xd07e5c85dae5f59dc444838cbfba8ecf6bd5cabdc3e3787bfa7559877bfd2b1d
2. Proposal state should be closed instead of rejected
=> fix: always show closed state for non-basic proposals

apps/ui/src/views/Settings/Spaces.vue
Looks like we are not setting it to true anymore
Go to http://localhost:8080/#/settings
you should see your spaces/a message instead of loading icon
=> chore: remove un-used `loaded` ref

package.json, yarn.lock
Currently we run that script with ts-node, but it has its own latency so it takes a while for our code to run.
Node v22.6.0 shipped with TS type stripping (behind experimental flag). It's no longer exerimental in Node v23, but we keep those flags for now.
By using node directly we make this script startup faster.
1. Run `yarn dev:interactive`.
2. It works.
=> chore: run dev:interactive script with node

apps/ui/src/composables/useActions.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/types.ts
- Updated provider to use the delegation's chain ID instead of wallet's chainID
- Removed unnecessary `web3` parameter from `getDelegatee` in EVM and Starknet actions
Closes: https://github.com/snapshot-labs/workflow/issues/537
1. Go to http://localhost:8080/#/s:arcadiafi.eth/delegates
2. Delegations should work
=> fix: updated provider to use the delegation's chain ID instead of wallet's chainid

apps/ui/src/networks/common/graphqlApi/index.ts
Because we only sort strategies metadatas by block if there are multiple
metadatas inserted at the same block we don't have guarantee that the
last entry here will have the highest index.
Instead we now look at last N metadatas (where N is number of active
strategies) and extract maxIndex from it.
1. Go to http://localhost:8080/#/sep:0xb58B05A1c8263441Bd74454544fD66CE25D300AD/settings/delegations
2. Space loads.
=> fix: extract maxIndex from last N metadatas instead of last

apps/ui/src/networks/offchain/constants.ts
This PR adds the `guest` connector to the list of connectors supported by offchain networks.
Guest is already added to evm and starknet, adding it to offchain was missed.
This currently only fix an issue with a the future pr https://github.com/snapshot-labs/sx-monorepo/pull/1200, where the payment modal does not work when connected as guest
=> fix: add guest connector to list of offchain supported connectors

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/queries/delegatees.ts
Toward https://github.com/snapshot-labs/workflow/issues/540
This PR start a refactoring process on the SpaceDelegation vue file, by moving the delegatee fetching using tanstack query into its own file, to make the vue file more slim, in anticipation of future code, handling the split delegation.
1. Go to http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/delegates?as=0cf5e.eth then ethereum tab
2. Go to https://snapshot.box/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/delegates?as=0cf5e.eth then ethereum tab
3. The 2 pages above should give the same result
4. Changing wallet should reflect
=> refactor: move delegatees fetching to own query file

packages/sx.js/src/utils/encoding/eth-sig.ts
V needs to be either 27 or 28, but some wallets use 0 and 1 so this needs to be mapped.
=> fix: map v in RSV to 27 or 28

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/queries/delegates.ts
Toward https://github.com/snapshot-labs/workflow/issues/540
Similar to https://github.com/snapshot-labs/sx-monorepo/pull/1345 , this PR moves the delegates vue query into its own file
1. Go to http://localhost:8080/#/s:starknet.eth/delegates
2. It should work as before
=> refactor: move delegates vue queries into its own file

packages/sx.js/package.json
As our default config (used in IDEs) includes both src/ and test/ then building project with it will create those subdirectories in dist/
But this is not the structure our npm package exposes (files should be in dist directly). Because of this UI won't automatically reload when there are changes in sx.js.
Regression from https://github.com/snapshot-labs/sx-monorepo/pull/1320
1. Run `yarn dev`.
2. Open UI in your browser.
3. Make some change in sx.js package.
4. UI reloads.
=> chore: use esnext tsconfig for building dev version of sx.js

apps/ui/src/helpers/utils.test.ts, apps/ui/src/helpers/utils.ts
Sometimes Etherscan returns ABI without method parameters. We need to create placeholders for those.
1. Go there: http://localhost:8080/#/eth:0x77cA6535CfDF9f4BC911F2a02e76f898dF5c926A/
2. Click on Contract call execution.
3. Use this address: `0x72eD19788Bce2971A5ed6401662230ee57e254B7`.
4. It works, you can add execution.
=> fix: use placeholder names for inputs if they are missing

apps/ui/src/components/EditorExecution.vue, apps/ui/src/components/TransactionsListItem.vue
Fix left gap in the transaction list, when the sort icon is hidden 
1. Go to http://localhost:8080/#/s:paraswap-dao.eth/create/yrbww
2. Create an execution
3. There should be no left gap anymore
=> fix: fix empty space

apps/ui/src/components/Ui/InputCheckbox.vue, apps/ui/src/helpers/transactions.ts, apps/ui/src/style.scss
Two issues are handled in this
1. Unable to click checkbox
Users are not able to click the checkbox
There are multiple reasons for this:
- Padding is overlaping
- No default value
- No id for label
2.  Unable to submit the form because we are passing wrong args order than ABI
In this case it is expecting `bytes32,uint256,bool` but we are passing `[true,"0x7d0de5791c9acd069e616817b7b1ce2becaa81e7a4d236e44c9e400c1a9e7b91","114440878338729613389"]`
- Improved InputCheckbox component to ensure default value is set correctly on mount (false), 
- Removed required mark and style fixes for checkbox
- Updated transaction helper to maintain argument order as per ABI
1. Go to http://localhost:8080/#/s:paraswap-dao.eth/create/yrbww
2. Add a `contract call` on `GovCo Optimism` 
3. Use contract address …
=> fix: issues with InputCheckbox and transaction handling

apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/workflow/issues/547
This PR decrease the minimum required number of choices to 1 for offchain proposals, when not a basic voting proposal
1.
=> fix: allow single choice for voting choice

apps/highlight/src/agents/townhall.ts, apps/highlight/src/api/schema.gql, apps/highlight/src/api/writers.ts, apps/ui/src/composables/useTownhall.ts, apps/ui/src/helpers/townhall/api.ts, apps/ui/src/views/Townhall/Create.vue, apps/ui/src/views/Townhall/Discussion.vue, packages/sx.js/src/clients/highlight/ethereum-sig.ts, packages/sx.js/src/clients/highlight/types.ts, packages/sx.js/src/highlightConstants.ts, turbo.json
For now just adding it as additional argument in entrypoint/event. In the future we might want to replace it with IPFS/Swarm, but for now keeping it as simple as possible.
Towards: https://github.com/snapshot-labs/workflow/issues/549
1. Go to http://localhost:8080/#/townhall/ethereum/create
2. Fill in form.
3. Use `https://forum.balancer.fi/t/bip-xxx-grant-maxis-stablesurge-v2-parameter-change-permissions/6492` for Discussion URL.
4. Submit, you can see discussion URL in the final discussion.
=> feat(townhall): add discussion URL input to discussions

apps/ui/src/networks/offchain/index.ts
Closes: https://github.com/snapshot-labs/workflow/issues/550
1. Go to http://localhost:8080/#/s-tn:chakrin.eth/proposal/0xf010d9269a273ba9329d4bbfbd33b6c36c856ddb99379daaa65467dfbf84e9dd
2. The execute button should not appear
=> fix: hide the execute actions on read-only execution

packages/sx.js/src/strategies/offchain/remote-validate.ts, packages/sx.js/src/strategies/offchain/remote-vp.ts
Closes: https://github.com/snapshot-labs/workflow/issues/553
This PR will always pass `network` as a string to score-api
1. Go to the network tab in the dev console
2. in all requests to score-api, the `network` value in the body should now be string instead of a number
=> fix: always string network to score-api

apps/highlight/src/index.ts, apps/ui/src/components/Townhall/StatementItem.vue, apps/ui/src/helpers/townhall/api.ts, apps/ui/src/queries/townhall.ts, apps/ui/src/views/Townhall/Discussion.vue
This PR adds ability to filter results by specific roles. This is done by addition of REST endpoint that computes those values from database.
Towards: https://github.com/snapshot-labs/workflow/issues/549
**Note:** There might be some bugs with WebSockets as `kbyte` doesn't support unsubscribing that means that if you change something in code and app is reloaded it might subscribe multiple times and we end up receiving events multiple times, that can result in vote counts increasing more than they should. I left it as-is as WebSockets will be removed.
1. Go to http://localhost:8080/#/townhall/ethereum/settings
2. Create some roles
3. Claim some roles (on multiple accounts so you can then filter results).
4. Create discussion.
5. Vote on few accounts.
6. You see results from specific role …
=> feat: add ability to filter results by role

apps/ui/src/components/Modal/Vote.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/603
After submitting an offchain vote, refresh the votes list
1. Go to an offchain proposal page, then votes tab
2. vote using the right sidebar
3. after submitting the vote, the votes list should refresh and be updated to reflect your vote
=> fix: refresh the votes list after a vote

apps/ui/src/networks/starknet/index.ts
Using brovider instead of hardcoded Infura URLs for Starknet L1 nodes.
1. Go to http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/proposal/37
2. VP loads.
=> chore: use brovider for Starknet L1 nodes

apps/ui/src/components/App/Notifications.vue
Previously entire horizontal section of screen would become occupied by notification click area.
Now it's limited only to the notification itself.
Closes: https://github.com/snapshot-labs/workflow/issues/559
1. Apply patch from below to simulate notifications.
2. Go to http://localhost:8080/#/
3. You can click links at the same height as notifications.
4. You can dismiss notification by button.
```diff
diff --git a/apps/ui/src/App.vue b/apps/ui/src/App.vue
index af992a888..ef2cb7964 100644
--- a/apps/ui/src/App.vue
+++ b/apps/ui/src/App.vue
@@ -5,6 +5,7 @@ import whiteLabelRoutes from '@/routes/whiteLabel';
const route = useRoute();
const router = useRouter();
const { app } = useApp();
+const { addNotification } = useUiStore();
const {
init: initWhiteLabel,
isWhiteLabel,
@@ -37,7 +38,18 …
```
=> fix: limit notification click area to notification itself

apps/api/src/config.ts, apps/api/src/starknet/config.ts
Instead of using Infura for Starknet we now use Brovider everywhere.
=> feat: use brovider for Starknet in API

apps/ui/src/components/FormSpaceVoting.vue
Closes: https://github.com/snapshot-labs/workflow/issues/555
Remove the 'ignore abstain votes' option in the space settings
1. Go to a space settings, the vote tab
2. The 'hide abstain votes' option is gone
3. If the space has enabled it already, saving the setting should keep it to `true`:
```
"hideAbstain": true
```
=> fix: remove hide abstain switcher from space settings

apps/ui/src/components/ProposalsListItemHeading.vue, apps/ui/src/components/TimeRelative.vue, apps/ui/src/components/TopicsListItem.vue, apps/ui/src/composables/useRelativeTime.ts, apps/ui/src/helpers/utils.ts, apps/ui/src/views/My/Notifications.vue, apps/ui/src/views/Proposal/Overview.vue, apps/ui/src/views/Proposal/Votes.vue, apps/ui/src/views/Topic.vue
Adding two helpers than can be used to reactively update relative time.
- useRelativeTime - composable when time is needed in setup code
- TimeRelative - component for rendering reactive relative time
Closes: https://github.com/snapshot-labs/workflow/issues/532
1. Create proposal.
2. Open it.
3. Time it was created is updated on-the-fly.
=> feat: update relative time reactively

apps/ui/src/components/SpaceDelegates.vue, apps/ui/src/queries/delegatees.ts
This PR fixes couple issue with delegatees loading:
1. Fixes reactivity for enabled flag in (#1359), regression from #1345
2. Only shows section "Delegating to" if user is logged in (otherwise it was showing empty section that loaded forever), regression from #1344
3. Updated `fetchSplitDelegationDelegatees` to make API call only for Ethereum addresses, otherwise when signed with Starknet wallet it will end up trying to load it from API and retry 3 times so it was loading for ~10 seconds.
Closes: #1359
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/delegates unlogged.
2. No "Delegating to" section.
3. Sign in with Metamask, it works as expected.
4. Switch to Argent, it works as expected (not delegating message).
=> fix: delegation page delegatee loading

apps/ui/src/queries/delegatees.ts
This PR fix an issue where the amount in the VP column in the delegatees section of the split delegation is not correct.
It was showing the delegatee full VP, instead of just the VP the delegatee get from the current user
1. Go to http://localhost:8080/#/s:paraswap-dao.eth/delegates?as=0x9DC3E0fC228c2455773E70ee9E987aE2a6FBc07D
2. In the "delegatees" section, the vp for the delegatee "enerow" should be "1.1M psp" (the amount the current user has delegated)
3. Go to http://localhost:8080/#/s:paraswap-dao.eth/delegates?as=0x17F26c67fD5074d859ae63e00CF5b3Fd793c0786
4. The amount should be different
=> fix: show only the user's delegated voting power in split-delegation

apps/api/src/config.ts, apps/api/src/evm/config.ts, apps/api/src/evm/utils.ts, apps/api/src/evm/writers.ts, apps/api/src/starknet/config.ts, apps/mana/migrations/20250604134037_create_apegas_proposals_table.ts, apps/mana/src/db.ts, apps/mana/src/eth/index.ts, apps/mana/src/eth/registered.ts, apps/mana/src/eth/rpc.ts, apps/mana/src/index.ts, turbo.json
This PR adds detection of ApeGas proposals in API and those proposals are saved in Mana via RPC.
Then Mana will try to process those proposals using Herodotus API.
1. Apply patch below (it just changes local API to index curtis only).
2. Run `yarn dev:interactive`.
3. Create proposal on Space that uses ApeGas voting strategy (you can use this space http://localhost:8080/#/curtis:0xf6238F73A87D390CB00b2B380D2B777E13Fe2725 or create your own on [this PR](https://github.com/pulls)).
4. Inspect `SELECT * FROM public.apegas_proposals` on Mana database.
5. You see your request and Herodotus ID.
6. (optional) After around 1.5 hours you can vote on that proposal (if you have VP) on [this PR](https://github.com/pulls).
```diff
diff --git a/scripts/dev-interactive.ts b/scripts/dev-interactive.ts …
```
=> feat: automatically process ApeGas proposals

apps/ui/src/components/Modal/Transaction.vue, apps/ui/src/composables/useSafeWallet.ts, apps/ui/src/helpers/constants.ts, apps/ui/src/helpers/contracts.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/starknet/actions.ts
After Pectra update EOA's getCode call can return non 0x responses. This links EOA to smart contract and it can be detected by 0xef0100 delegation indicator.
We need to check if code is not just EIP-7702 reference before assuming it's a contract.
1. Upgrade your mainnet account to EIP-7702 (not sure how I did that anymore).
2. After that Snapshot works as it used to.
3. For example you can follow and unfollow spaces (before it would tell you that Safe wallets can't follow spaces).
=> fix: update isContract checks to support EIP-7702

apps/highlight/src/agents/townhall.ts, apps/highlight/src/api/config.json, apps/highlight/src/api/schema.gql, apps/highlight/src/api/writers.ts, apps/highlight/src/index.ts, apps/ui/src/components/Townhall/PostItem.vue, apps/ui/src/components/Townhall/Posts.vue, apps/ui/src/components/TownhallTopicsList.vue, apps/ui/src/composables/useTownhall.ts, apps/ui/src/helpers/townhall/api.ts, apps/ui/src/helpers/townhall/types.ts, apps/ui/src/queries/townhall.ts, apps/ui/src/views/Space/Overview.vue, apps/ui/src/views/Townhall/Create.vue, apps/ui/src/views/Townhall/Roles.vue, apps/ui/src/views/Townhall/Topic.vue, packages/sx.js/src/clients/highlight/ethereum-sig.ts, packages/sx.js/src/clients/highlight/types.ts, packages/sx.js/src/highlightConstants.ts, yarn.lock
This PR renames Discussions to Topics and Statements to Posts.
I also included few fixes that make testing this PR easier (otherwise you will hit some minor bugs that might be confusing if they are coming from this PR or not):
1. New role's optimistic entry uses correct format.
2. Add unpin action (before always pin was used even if you saw "Unpin post").
3. Prevent crash of API on results endpoint.
Closes: https://github.com/snapshot-labs/townhall/issues/15
1. Go to http://localhost:8080/#/s:ethpoll.eth/townhall
2. Create topic.
3. Create posts, vote on them, pin, unpin, hide.
4. Vote on posts.
5. Close topic.
6. Everything works as supposed, not mentions of legacy names (discussion, statement).
=> refactor: rename Discussion -> Topic, Statement -> Post

apps/ui/src/components/ProposalResults.vue, apps/ui/src/components/ProposalVoteApproval.vue, apps/ui/src/components/ProposalVoteRankedChoice.vue, apps/ui/src/components/ProposalVoteSingleChoice.vue, apps/ui/src/components/ProposalVoteWeighted.vue, apps/ui/src/components/Ui/TooltipOnTruncate.vue
Closes: https://github.com/snapshot-labs/workflow/issues/573
Show a tooltip for long choice in results and vote, only when the choice is truncated
Test with:
- http://127.0.0.1:8080/#/s:test.wa0x6e.eth/proposal/0xfe38f18680b255721c276013284cebccaed6d09b62164baf12e60436a9de5413
- http://127.0.0.1:8080/#/s:test.wa0x6e.eth/proposal/0x9d45d6cb75e93b582b35d4e27c960551c3dd3c2d071c3c7d8615639b37ab2af2
1. The vote form and result choice label should show a tooltip on mouse hover when truncated
2. There is no tooltip when not truncated
3. Resize the right sidebar
4. The tooltip status should react to the resize and new truncate status
=> fix: show tooltip for truncated choices

apps/ui/src/views/Townhall/Topic.vue
Right now if we switch Role filter entire page turns into loading state. We can avoid that by having separate loading indicator just for the results.
1. Go to Townhall
2. Create some role.
3. Create topic.
4. Change Role filter.
5. Page is not blinking when loading.
=> fix: separate results loading indicator

apps/ui/src/components/Chatbot.vue, apps/ui/src/views/Townhall/Topic.vue, apps/ui/src/views/Townhall/Topics.vue
Improve keyboard navigation:
- Remove double focus on the "Create topic" button when navigating the page with keyboard
- Convert element with `onClick` event to `button`, to allow focus when navigating with keyboard
=> fix: improve keyboard navigation

apps/api/src/common/utils.ts, apps/api/src/config.ts, apps/api/src/evm/config.ts, apps/api/src/evm/writers.ts, apps/api/src/schema.gql, apps/api/src/starknet/writers.ts, scripts/dev-interactive.ts, turbo.json
This way we can reference entity URI directly form API.
Closes: https://github.com/snapshot-labs/workflow/issues/575
1. Run `yarn dev:interactive` with UI and API.
2. Let it run for 15 seconds.
3. Run following query.
4. You can access spaces/proposals via provided link.
```gql
{
spaces {
id
_indexer
link
}
proposals {
id
_indexer
link
}
}
```
=> feat: add spaces and proposals UI links

apps/highlight/src/agents/townhall.ts, apps/highlight/src/api/index.ts, apps/highlight/src/api/schema.gql, apps/highlight/src/api/writers.ts, apps/highlight/src/index.ts, apps/ui/src/components/App/Nav.vue, apps/ui/src/components/Townhall/PostItem.vue, apps/ui/src/components/Townhall/Posts.vue, apps/ui/src/components/TownhallTopicsList.vue, apps/ui/src/composables/useTownhall.ts, apps/ui/src/composables/useTownhallSpace.ts, apps/ui/src/helpers/townhall/api.ts, apps/ui/src/queries/townhall.ts, apps/ui/src/views/Space.vue, apps/ui/src/views/Space/Overview.vue, apps/ui/src/views/Townhall/Create.vue, apps/ui/src/views/Townhall/Roles.vue, apps/ui/src/views/Townhall/Topic.vue, apps/ui/src/views/Townhall/Topics.vue, packages/sx.js/src/clients/highlight/ethereum-sig.ts, packages/sx.js/src/clients/highlight/types.ts, packages/sx.js/src/highlightConstants.ts
This PR now links all topics and roles to specific page, so topics and roles are not mixed up.
Closes: https://github.com/snapshot-labs/townhall/issues/13
1. Go to http://localhost:8080/#/s:openagora.eth
2. Check roles, topics.
3. Create some role and claim it.
4. Create some topic and vote.
5. Check results.
6. All works as expected.
7. Go to http://localhost:8080/#/s:ethpoll.eth/townhall and http://localhost:8080/#/s:ethpoll.eth/townhall/roles
8. You don't see other space's topics and roles
9. You can create roles and topics there and they are not mixed up.
=> feat: link topics and roles to specific space

apps/ui/src/components/Ui/InputStamp.vue, apps/ui/src/components/Ui/InputStampCover.vue, apps/ui/src/composables/useMarkdownEditor.ts, apps/ui/src/helpers/constants.ts, apps/ui/src/helpers/utils.ts
Closes https://github.com/snapshot-labs/workflow/issues/577
- added file size check to ensure uploads are less than 1 MB
- improved error handling to provide specific feedback on upload failures
- Go to your space settings
- Try to upload images that are larger than 1MB to avatar and cover
- Should throw new error instead of "failed to upload image."
=> fix: show error about max file size when uploading an image

apps/ui/src/components/ProposalVote.vue, apps/ui/src/networks/common/helpers.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/evm/index.ts, apps/ui/src/networks/offchain/index.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/networks/starknet/constants.ts, apps/ui/src/networks/starknet/index.ts, apps/ui/src/networks/types.ts
Adding simple condition so Starknet wallet can't be used on EVM spaces.
Closes: https://github.com/snapshot-labs/workflow/issues/578
1. Go to http://localhost:8080/#/ape:0xa1282429A4a34F9f91D50ecf3d8217Fc6654eF6e/proposal/1
2. Sign in with Starknet wallet.
3. You see message that this wallet is not supported.
=> feat: show message if connector is not supported for voting

apps/api/src/evm/writers.ts, apps/api/src/schema.gql, apps/api/src/starknet/writers.ts, apps/ui/src/networks/common/helpers.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/starknet/actions.ts
Those were renamed to "indices".
This PR removes deprecated fields using wrong grammar from API as well updates some leftovers in UI code.
=> chore: remove deprecated "indicies"

apps/api/src/common/ipfs.ts, apps/api/src/common/utils.ts, apps/api/src/evm/writers.ts, apps/api/src/schema.gql, apps/api/src/starknet/writers.ts
With this change:
1. API tracks voting strategies decimals. Those can be accessed using vp_decimals on Space or Proposal entities.
2. Vote VP and Proposal scores now have parsed variant (_parsed suffix) that is formatted using decimals value.
Closes: https://github.com/snapshot-labs/workflow/issues/567
1. Apply diff from below (Curtis is easier to sync up).
2. Run query below on http://localhost:3000
3. Values are formatted.
```diff
diff --git a/scripts/dev-interactive.ts b/scripts/dev-interactive.ts
index 5a60152e..39560f2c 100644
--- a/scripts/dev-interactive.ts
+++ b/scripts/dev-interactive.ts
@@ -14,8 +14,8 @@ const SERVICES: Record<ServiceType, Service> = {
api: {
env: {
UI_URL: 'http://localhost:8080',
-      ENABLED_NETWORKS: 'sep,sn-sep',
-      VITE_ENABLED_NETWORKS: …
```
=> feat: compute parsed VP on API

apps/api/src/common/utils.ts, apps/api/src/evm/writers.ts, apps/api/src/starknet/writers.ts
Before it would return -Infinity which can't be written to DB.
Fixes issue in https://github.com/snapshot-labs/sx-monorepo/pull/1435
=> fix: use 0 decimals if strategies are empty

apps/ui/src/composables/useSpaceAlerts.ts
This PR disabled `unsupportedProOnlyNetworks` on onchain spaces (other alerts had this check already).
Closes: https://github.com/snapshot-labs/workflow/issues/597
1. Go to http://localhost:8080/#/base:0x282d013BF31374D0046F04D6a7644d97751ed339/settings/voting-strategies
2. You don't see an alert.
=> fix: disable unsupportedProOnlyNetworks for onchain spaces

apps/api/src/evm/config.ts, apps/api/src/evm/writers.ts, apps/api/src/schema.gql, apps/api/src/starknet/writers.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts
Closes https://github.com/snapshot-labs/workflow/issues/581
- introduced handleQuorumUpdated for quorum updates
- changed proposal quorum type from BigInt to BigDecimalVP
- ensured quorum values are strings for consistency
- apply this patch
```bash
diff --git a/apps/api/src/evm/config.ts b/apps/api/src/evm/config.ts
index 704698ef..209afd5f 100644
--- a/apps/api/src/evm/config.ts
+++ b/apps/api/src/evm/config.ts
@@ -28,7 +28,7 @@ const START_BLOCKS: Record<NetworkID, number> = {
arb1: 157825417,
base: 23524251,
mnt: 75662182,
-  ape: 12100384,
+  ape: 18217450,
curtis: 16682282
};
diff --git a/scripts/dev-interactive.ts b/scripts/dev-interactive.ts
index 5a60152e..e57d023e 100644
--- a/scripts/dev-interactive.ts
+++ b/scripts/dev-interactive.ts
@@ -14,9 +14,9 @@ const SERVICES: …
```
=> feat: quorum update handling

apps/ui/src/composables/useSpaceAlerts.ts, apps/ui/src/views/Space/Editor.vue
- Go to http://localhost:8080/#/s:aavegotchi.eth/settings/voting-strategies
- You should see polygon notice like before
- Go to http://localhost:8080/#/s:aavegotchi.eth/create/eq2qk
- You should not see polygon notice like before
=> fix: show notice for polygon on settings but not editor

apps/ui/src/components/Modal/TestStrategy.vue
This PR fix an issue where testing strategies from offchain spaces was ignoring the strategy network.
Also cleanup the payload to send only relevant data to score-api
1. Go to an offchain space, using multiple strategy on different network (e.g. http://localhost:8080/#/s:cow.eth/settings/voting-strategies)
2. When testing a strategy on custon network, it should send the request to score-api with the correct network
Before
```json
{
"jsonrpc": "2.0",
"method": "get_vp",
"params": {
"address": "0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3",
"space": "cow.eth",
"strategies": [
{
"id": "ecc42e06-5067-446f-8509-9ce8f0127105",
"chainId": 100,
"address": "erc20-balance-of",
"name": "erc20-balance-of",
"paramsDefinition": null,
"params": {
"symbol": "vCOW (GC)",
"address": …
```
=> fix: fix missing network params when testing offchain strategies

apps/mana/src/stark/herodotus.ts, apps/mana/src/stark/rpc.ts
`deployAccount` needs to be called so address is deployed before usage.
=> fix: call deployAccount in herodotus/execute calls

apps/ui/package.json, apps/ui/src/components/ButtonFollow.vue, apps/ui/src/components/FormSpaceStrategies.vue, apps/ui/src/components/Modal/Delegate.vue, apps/ui/src/components/Modal/EditStrategy.vue, apps/ui/src/components/Modal/TestStrategy.vue, apps/ui/src/components/Ui/BadgeNetwork.vue, apps/ui/src/components/Ui/InputAddress.vue, apps/ui/src/components/Ui/SelectorNetwork.vue, apps/ui/src/composables/useOffchainNetworksList.ts, apps/ui/src/composables/useSafeWallet.ts, apps/ui/src/composables/useSpaceAlerts.ts, apps/ui/src/composables/useSpaceSettings.ts, apps/ui/src/composables/useWeb3.ts, apps/ui/src/networks/offchain/actions.ts, apps/ui/src/networks/offchain/api/index.ts, apps/ui/src/networks/offchain/api/types.ts, apps/ui/src/networks/offchain/index.ts, apps/ui/src/networks/types.ts, apps/ui/src/types.ts, apps/ui/src/views/CreateSpaceSnapshot.vue, apps/ui/src/views/Space/Settings.vue, packages/sx.js/src/clients/offchain/types.ts, yarn.lock
Toward https://github.com/snapshot-labs/workflow/issues/562
This PR enables offchain spaces to select Starknet networks in the UI while maintaining backward compatibility with existing EVM-based spaces. This is a foundational change that prepares the system for Starknet integration on offchain spaces.
- **Enables Starknet Network Selection**: Users can now select Starknet networks (mainnet/testnet) when configuring offchain spaces and strategies
- **Type System Migration**: Updates `snapshot_chain_id` from `number` to `string` to support Starknet's string-based chain IDs
- **Unified Network Lists**: Consolidates network selection to use `networks.json` as the single source of truth
- **Safe Operation Blocking**: Prevents unsupported operations (like proposal creation) on Starknet networks …
=> fix: allow starknet network on offchain spaces

apps/highlight/src/api/writers.ts
Fix an issue where creating a new topic under a category is failing
1. Create a new topic, inside a category
2. It should create the topic
=> fix: fix invalid topic ID when under a category

apps/ui/src/networks/evm/index.ts, apps/ui/src/networks/offchain/index.ts, apps/ui/src/networks/starknet/index.ts
For relayer addresses, we display address with padding `0` but the link redirect without `0`
This address without `0` is not accepted inside argent wallet
This will add address formatting in all explorer URLs for addresses (EVM, starknet, offchain)
- Go to http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50/settings/authenticators
- Click on relayer address
- It should redirect to address with `0` padding
=> fix: address formatting in explorer URL

apps/ui/src/networks/common/helpers.ts, apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/starknet/constants.ts
Now authenticators will be sorted by priority (those were not set plus order was messed up in .sort)
Signature relayers (EthSig, StarkSig) get default priority 0. Deprecated EthSig on EVM gets lower priority than new one.
EthTx on EVM and StarkTx on Starknet get lower priority (2 or 1).
EthTx on Starknet gets lowest priority because UX is bad.
1. Vote there: http://localhost:8080/#/sn:0x07c251045154318a2376a3bb65be47d3c90df1740d8e35c9b9d943aa3f240e50
2. You get signature prompt, not transaction prompt.
=> fix: properly sort authenticators

apps/ui/src/views/Space/Settings.vue
Settings has not been updated to take into account the removed horizontal scroller menu
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1449
Remove extra spacing in space settings toolbar
1. Go to your space settings
2. Dirty the settings to make the bottom toolbar appears
3. When the page content shorter than the browser height, the bottom toobar should stick to the bottom of the page, without extra gap
=> fix(ui): remove extra spacing in space setting bottom toolbar

apps/ui/src/helpers/discourse.ts
On [this proposal](https://snapshot.box/#/s:lido-snapshot.eth/proposal/0xc3f92bcdf8926cfa7528ca6a979c0fdce1e4d0cfaaa72dd6410a76a2e1e55766) we are displaying wrong discussion under "Discussion" tab
looks like we support only topic URLs like this
https://research.lido.fi/t/community-staking-module/5917
But the link provided in proposal is for post
https://research.lido.fi/t/community-staking-module/5917/139
- Enhanced `loadSingleTopic()` to handle Discourse URLs containing both topic ID and post number
- Added automatic post filtering when a specific post number is provided in the URL
| URL Format | API Request | Post Filtering |
|------------|-------------|----------------|
| `/t/topic-name/139` | `139.json` | None (all posts) |
| `/t/topic-name/5917/139` | `5917/139.json` | Posts ≥ 139 …
=> feat: add support for discourse URLs with specific post numbers

apps/ui/src/docs/icons.mdx
This PR adds icons gallery for Heroicons.
Closes: https://github.com/snapshot-labs/workflow/issues/624
1. Go to Storybook.
2. Go to iconography.
=> feat: add Icons gallery to Storybook

apps/ui/index.html
This seems to cause issues on Chrome on iOS.
Closes: https://github.com/snapshot-labs/workflow/issues/622
1. Open explore page on Chrome iOS.
2. Scroll down and up to see bottom bar with Login button to be sticky on bottom.
https://github.com/user-attachments/assets/c3f2c838-0c65-4bde-b3e6-5452dfc8568a
=> chore: add viewport-fit=cover

apps/ui/src/components/ProposalExecutionsList.vue, apps/ui/src/components/SpaceCover.vue, apps/ui/src/components/Ui/ImagePreview.vue, apps/ui/src/components/Ui/InputStamp.vue, apps/ui/src/components/Ui/InputStampCover.vue, apps/ui/src/helpers/constants.ts, apps/ui/src/helpers/utils.ts
Closes: https://github.com/snapshot-labs/workflow/issues/272
This PR will show the InputStamp and InputStampCover image preview with the same ratio as the one shown by the UiStamp and UiStampCover component.
The image in space settings was shown differently, due to it coming from stamp, after being resized, while the one in the space settings is the original one without any processing.
Before the fix, the space cover in these 2 pages are different
- https://snapshot.box/#/s:%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86.wa0x6e.eth
- https://snapshot.box/#/s:%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86.wa0x6e.eth/settings/profile
After the fix, the 2 space covers are identical
- http://localhost:8080/#/s:%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86.wa0x6e.eth
- …
=> fix: use correct ratio when showing image with UiStampInput*

apps/ui/src/docs/colors.mdx
This PR adds basic colors we **use** in the app to Storybook.
Those colors are duplicated between style.scss and this file as there is no clean way to get those extracted (we could get those from Tailwind config but our colors are parametrized by CSS variables so we don't get anything usable).
Closes: https://github.com/snapshot-labs/workflow/issues/623
1. Open storybook.
2. You see colors.
=> feat: add colors to storybook

.github/workflows/deploy.yml, apps/api/package.json, scripts/deploy-api-prod.sh
This will reintroduce [blue-green deployments](https://en.wikipedia.org/wiki/Blue%E2%80%93green_deployment). Changes will be automatically deployed to staging app (detected using https://api.snapshot.box/deployment).
We have issue in this workflow currently which is that once we upgrade API-1 to be production app then it's often the case that we forget to trigger redeployment of API-2 so it can pull latest changes - this will need to be automated so it's all handled automatically.
Apply diff below:
```diff
diff --git a/scripts/deploy-api-prod.sh b/scripts/deploy-api-prod.sh
index 11ea41a6..f22e5d96 100755
--- a/scripts/deploy-api-prod.sh
+++ b/scripts/deploy-api-prod.sh
@@ -19,4 +19,4 @@ fi
echo "Starting deployment to staging app: $CURRENT_STAGING_APP_ID"
-./scripts/deploy-changed.sh …
```
=> feat: add API blue-green deployments

.github/workflows/deploy.yml
Now instead of two separate and very similar jobs
we have one that uses strategy matrix to deploy across two environments.
=> ci: simplify deploy_api jobs by using matrix

.github/actions/get-deployments/action.yml, .github/workflows/promote-api.yml
This workflow will be used to promote staging API to production (it will be possible to trigger this workflow using Github UI). This workflow does following:
1. Checks current production/staging apps.
2. Updates public app to use staging app (so it becomes production app).
3. Deploys new changes to (new) staging app.
Used environment should require confirmation from authorized users before it can run.
Tested using `act` promoting testnet-api-1 to production.
TODO:
=> ci: add Promote API workflow

apps/mana/logger.ts, apps/mana/package.json, yarn.lock
DigitalOcean log forwarding has hard limit of 2000 bytes per message. This is not quite enough for many logs (votes, but most notably errors from RPC that contain lots of output).
Those logs are become hard to use because as the message itself is JSON it's no longer parseable once truncated so we actually lose all the context (and all logs become INFO even though it was ERROR for example).
We can now configure Logtail as Pino transport directly cutting out DigitalOcean processing avoiding this limit.
Now long messages parse properly:
Where before it would be turned into a mess:
=> feat: add Logtail Pino transport

apps/ui/src/helpers/constants.ts
Missing delegates page on http://localhost:8080/#/s:youcanjustbuildthings.eth
You should see delegates tab on http://localhost:8080/#/s:youcanjustbuildthings.eth
=> chore: add spark delegation strategy to the registry

apps/ui/src/components/ProposalExecutionActions.vue, apps/ui/src/components/ProposalIconStatus.vue, apps/ui/src/components/ProposalResults.vue, apps/ui/src/components/ProposalStatus.vue, apps/ui/src/components/ProposalVote.vue, apps/ui/src/composables/useExecutionActions.ts, apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/common/graphqlApi/queries.ts, apps/ui/src/types.ts, apps/ui/src/views/Proposal/Overview.vue
This PR adds support for timelock Queued and Vetoed proposal statuses. Before Governor support is merged this will affect only SnapshotX proposals with Timelock.
This was extracted from https://github.com/snapshot-labs/sx-monorepo/pull/1514.
There are two commits there: one that adds queued/vetoed statuses and second one that refactors `useExecutionAction` composables to fix reactivity. It's recommended to review this PR per-commit to avoid mixing kind of different concerns.
1. Create SnapshotX space with timelock (or use existing one), make sure you have treasury created for your timelock so it can be used in the UI.
2. Create proposal with execution.
3. Vote, you can Execute transactions.
4. Proposal will now become Queued (you need to F5 or go away from the page and come back to …
=> feat: add Queued & Vetoed proposal status

apps/ui/src/networks/evm/constants.ts, apps/ui/src/networks/starknet/constants.ts, apps/ui/src/queries/propositionPower.ts
This PR fixes issue with checking proposal threshold on the UI. The value users provide in the form is provided in base units. So if you insert `5` and you use ERC-20 votes strategy you don't require 1 TEST, you require 0.000000000000000005 TEST. This was always the case, so nothing changes there. The only issue was that UI actually interpreted that threshold as 5 TEST, so users with 1 TEST were prevented from proposing, but they actually met the requirement on the contract level.
This fix is achieved by:
- Proposal threshold is now inserted as string so it doesn't crash ethers when inserting overflowing Numbers.
- We do not divide proposition power by decimals when comparing them to proposal threshold.
The main issue is that if we have proposition strategy that has 18 decimals (for …
=> fix: check raw proposition power against proposal threshold

apps/ui/src/components/Modal/Transaction.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1549
When inputing an invalid address after a valid contract address in the transaction form, the form crash.
See [issue](https://github.com/snapshot-labs/sx-monorepo/issues/1549) for more details
1. Go 
2. Input `0x000000000000cd1734581aa8147b8D3950260FF` in the address
3. It refresh the form with the contract fields
4. Input a non-contract address in the contract input e.g. `0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3`
5. It should clear the form, and show an error message on the address field
6. Put a valid contract address again: `0x000000000000cd1734581aa8147b8D3950260FF`
7. It should refresh the form, and show the contract fields again
=> fix(ui): fix transaction form error when updating from valid to invalid address

apps/ui/src/components/FormController.vue, apps/ui/src/components/Modal/EditContact.vue, apps/ui/src/components/Modal/Transaction.vue, apps/ui/src/components/Ui/InputAddress.vue, apps/ui/src/helpers/validation.ts
Closes https://github.com/snapshot-labs/sx-monorepo/issues/1477
In the contact create/edit form, we show a picker icon in the address input, but it is currently not doing anything on click.
It also should not be present logically, as we can not pick a contact when editing/creating a contact (contacts are unique)
This PR will hide the picker icon in create/edit contact form
Also moved the picker button to be after the input in keyboard navigation.
1. Go to http://localhost:8080/#/settings/contacts
2. Create/Edit a contact
3. In the form, there is no picker in the address input
4. Go go http://localhost:8080/#/s:test.wa0x6e.eth/create/ygqbl
5. Create a contract call execution
6. Paste `0x000000000000cd17345801aa8147b8D3950260FF` in the address field
7. The picker icon should be replaced by …
=> fix: hide address picker in contact edit form

apps/ui/src/components/Ui/ResizableHorizontal.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1555
This PR fixes a drag event bubbling issue during resizing by adding a data attribute to prevent sidebar swipe interactions.
This will prevent the sidebar opening action on some screen resolution, while resizing the proposal sidebar
1. Go to a proposal page on a touch screen device
2. Resolution of the device should allow the left sidebar to be hidden by default
3. Click on the left border of the proposal sidebar, and drag to resize
4. You should be able to resize by dragging left and right, without triggering the sidebar opening event
5. When swiping the page from left to right, it should open the sidebar
=> fix(ui): do not bubble the drag event when resizing

apps/ui/src/composables/useWhiteLabel.ts
We redirect a whitelabel to main site (snapshot.box), when the space is not pro.
But while the redirection is happening, the whitelabel site is showing briefly.
This PR will avoid flashing the whitelabel site while redirecting, and keep the loading spinner  instead.
1. Edit your .env file, and set `VITE_HOST=snapshot.box`
2. In the dev console, network, set throttling to something slower
3. Start the server with `VITE_WHITE_LABEL_MAPPING='127.0.0.1;s:aavegotchi.eth' yarn dev`
4. Go to http://127.0.0.1:8080/
5. It should show the loading icon, until the redirection to snapshot.box (before, it will show the resolved whitelabel site, until snapshot.box is loaded)
=> fix(ux): avoid content flashing while redirecting non-pro whitelabel to main domain

apps/ui/src/helpers/constants.ts, apps/ui/src/views/Space/Settings.vue
Show "Strategies are invalid" error when space is using overriding strategies similar to when space is using multichain strategy
Closes: https://github.com/snapshot-labs/workflow/issues/645
1. Go to https://snapshot.box/#/s:odos.eth/settings/voting-strategies?as=0x7AEBD46FDbE4f12E9E46988D4Bf0673563005A5e
2. You will not see any error
3. Go to `http://localhost:8080/#/s:odos.eth/settings/voting-strategies?as=0x7AEBD46FDbE4f12E9E46988D4Bf0673563005A5e` 
4. You should not be able to save settings without removing the delegation strategy
=> fix: show error if space is using overriding strategies

apps/ui/src/views/Space/Settings.vue
- updated strategy check for turbo spaces
- turbo space http://localhost:8080/#/s:superfluid.eth/settings/voting-strategies should not show any error
- non turbo space http://localhost:8080/#/s:odos.eth/settings/voting-strategies should still show error
=> fix: allow overriding strategies validation for non-turbo spaces

apps/ui/src/components/EnsConfiguratorOffchain.vue, apps/ui/src/views/CreateSpaceSnapshot.vue, apps/ui/src/views/Space/Settings.vue
This address a concern from some of our domain name partner, where we refer to the domain name of an offchain space as "ENS Domain" when creating a space, although we support more than ens domain.
Just to name a few, we also support:h
- .bnb name
- .sonic name
- .shib name
- a few other names from offchain resolvers
This PR will fix the wording on our space creation UI, to migrate reference from "ENS domain name" to just "domain name".
1. Go to http://localhost:8080/#/create/snapshot
2. The copy should not imply that we support only ens domain as sole domain provider
=> fix(ui): rename "ens domain" to a more generic term

apps/api/src/evm/protocols/governor-bravo/writers.ts, apps/api/src/evm/protocols/snapshot-x/writers.ts, apps/api/src/schema.gql
On EVM block numbers are native timepoints. We want to migrate API to return timestamps on default start/min_end/max_end/snapshot so we need intermediate update to API where we just duplicate those.
After this PR is merged we will migrate UI to use those `_block_number` variants and we will be free to change how default start/min_end/max_end/snapshot works.
Towards: https://github.com/snapshot-labs/sx-monorepo/issues/1583
=> feat: index timeline events with block_number

apps/ui/src/networks/common/graphqlApi/index.ts, apps/ui/src/networks/evm/actions.ts, apps/ui/src/networks/starknet/actions.ts, apps/ui/src/types.ts
Depends on https://github.com/snapshot-labs/sx-monorepo/pull/1594
This PR should be compatible with both API versions (both string and number proposal ID) so it can be merged independently, but ideally we should promote it soon so types actually match what API returns.
=> refactor: convert proposalId to string on UI

apps/api/src/evm/protocols/governor-bravo/writers.ts, apps/api/src/evm/protocols/snapshot-x/writers.ts, apps/api/src/evm/utils.ts, apps/api/src/schema.gql
Those values will now be computed on API so `start`/`min_end`/`max_end` are always timestamps.
Towards: https://github.com/snapshot-labs/sx-monorepo/issues/1583
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/1600
1. Apply patch from below.
2. Run query from below.
3. You see both block numbers and timestamps and values are fairly accurate when looking at explorer.
```diff
diff --git a/scripts/dev-interactive.ts b/scripts/dev-interactive.ts
index af201d16b..b9e4d5564 100644
--- a/scripts/dev-interactive.ts
+++ b/scripts/dev-interactive.ts
@@ -14,8 +14,8 @@ const SERVICES: Record<ServiceType, Service> = {
api: {
env: {
UI_URL: 'http://localhost:8080',
-      ENABLED_NETWORKS: 'sep,sn-sep',
-      VITE_ENABLED_NETWORKS: 's-tn,sep,sn-sep',
+      ENABLED_NETWORKS: 'sep',
+ …
```
=> feat: compute start/min_end/max_end timestamps on API

apps/ui/src/components/ButtonFollow.vue
This PR removes the extra space in the space overview action buttons, appearing only on whitelabel
1. Go to a whitelabel space
2. The buttons are now aligned to right, without extra space
=> fix(ui): remove extra space in space overview actions buttons

apps/ui/src/helpers/utils.test.ts
- removed test case for shib name on testnet
- CI should now pass
=> chore: remove test for space controller address on shib testnet

apps/ui/src/components/App/Nav.vue
Fixes https://github.com/snapshot-labs/sx-monorepo/issues/1619
- added a new navigation item for Snapshot Pro
- should redirect to pro page
- Go to http://localhost:8080/#/s:arbitrumfoundation.eth/settings
- Click on "Snapshot Pro"
- It should redirect to pro page http://localhost:8080/#/s:arbitrumfoundation.eth/pro
=> feat: add snapshot pro link to settings menu

apps/ui/src/components/ButtonFollow.vue, apps/ui/src/stores/followedSpaces.ts
Fixes https://github.com/snapshot-labs/workflow/issues/656
- Open account modal if user is not logged in before attempting to follow
1. Disconnect the wallet
2. Click on follow button on explore page and space page
3. It should open account modal
=> fix: open account modal when follow button clicked without login
