- apps/sx-ui/src/networks/offchain/index.ts
Change to new URL, More details: https://discord.com/channels/955773041898573854/1030772407226601522/1175036485842509884
> fix: update hub testnet URL

- package.json
If you don't mind this it would be great as I'm using a package where I just type `nr` and hit enter twice to start the dev server.
Package is https://github.com/antfu/ni
> style: move dev to first position

- packages/sx.js/package.json
- packages/sx.js/src/authenticators/starknet/ethSig.ts
- packages/sx.js/src/clients/evm/ethereum-sig/index.ts
- packages/sx.js/src/clients/offchain/ethereum-sig/index.ts
- packages/sx.js/src/clients/starknet/starknet-sig/index.ts
- packages/sx.js/src/offchainNetworks.ts
- packages/sx.js/src/strategies/evm/merkleWhitelist.ts
- packages/sx.js/src/strategies/starknet/erc20Votes.ts
- packages/sx.js/src/strategies/starknet/merkleWhitelist.ts
- packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts
- packages/sx.js/src/types/networkConfig.ts
- packages/sx.js/src/utils/encoding/calldata.ts
- packages/sx.js/src/utils/ints-sequence.ts
- packages/sx.js/src/utils/merkletree.ts
- packages/sx.js/src/utils/storage-proofs/proof.ts
- packages/sx.js/src/utils/strategies.ts
- packages/sx.js/test/unit/strategies/starknet/merkleWhitelist.test.ts
- packages/sx.js/tsconfig.json
- yarn.lock
Using common config, enabling noImplicitAny and noUncheckedIndexedAccess
1. Tests pass.
2. You can also run integration tests (tested on evm and starknet myself).
> refactor: improve typing on sx.js repo

- apps/mana/src/eth/index.ts
- apps/mana/src/stark/index.ts
We send it as null in clients.
> feat: do not require id to be number

- apps/api/src/currentConfig.ts
- apps/api/src/utils.ts
- apps/api/src/writer.ts
- apps/api/test/unit/writer.test.ts
- apps/api/tsconfig.json
Using shared config with `noImplicitAny` and `noUncheckedIndexedAccess`.
1. Tests pass.
> chore: improve typing in api repo

- apps/ui/src/composables/useWalletConnect.ts
Sometimes it takes a while to init and it blocks other parts of the app.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/91
> refactor: initialize Web3Wallet client asynchronously

- apps/ui/src/components/Modal/Account.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/42
1. Connect wallet 
2. Go to my account and click "Connect wallet" again
> fix: Connect wallet not working

- apps/ui/src/composables/useUserSkin.ts
Refactors `useUserSkin` to reuse `vueuse` composables. 
1. Changing theme works as it used to.
> refactor: use vueuse in useUserSkin composable

- apps/ui/src/components/Modal/Account.vue
Enable types in `ModalAccount`.
1. Can connect with no issues.
> refactor: add types to ModalAccount

- .changeset/wise-starfishes-tan.md
- apps/ui/src/components/EditorVotingType.vue
- apps/ui/src/components/ProposalVoteRankedChoice.vue
- apps/ui/src/helpers/constants.ts
- apps/ui/src/networks/offchain/constants.ts
- apps/ui/src/networks/offchain/helpers.ts
- apps/ui/src/views/Proposal.vue
- packages/sx.js/src/clients/offchain/ethereum-sig/index.ts
- packages/sx.js/src/clients/offchain/ethereum-sig/types.ts
Closes: #150
Add support for ranked choices voting for offchain spaces
- UI is a copy/paste from snapshot v1
1. Go to one of your offchain space on sx
2. Create a proposal with type "Ranked Choice"
3. Try to vote on your newly created proposal
> feat: add support for ranked choice voting for offchain spaces

- apps/ui/src/components/ProposalResults.vue
- apps/ui/src/style.scss
Use same results style for all voting type.
Basic voting type still have a particular flavor, with ICON and different background color.
Closes: #214
1. Go to http://localhost:8080/#/s:pistachiodao.eth/proposal/0x38c654c0f81b63ea1839ec3b221fad6ecba474aa0c4e8b4e8bc957f70100e753
2. Go to http://localhost:8080/#/s:pistachiodao.eth/proposal/0x08c3bd2960700525770a1d634f8599ba967e55fcc05b6c1649d984d88253769d
Both results should have similar UI, with basic voting more colorful
> fix(ui): use same results style for all vote type

- apps/ui/src/components/Ui/BadgeVerified.vue
- apps/ui/src/networks/common/graphqlApi/index.ts
- apps/ui/src/networks/offchain/api/index.ts
- apps/ui/src/networks/offchain/api/queries.ts
- apps/ui/src/networks/offchain/api/types.ts
- apps/ui/src/types.ts
- apps/ui/src/views/Space/Overview.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/239
1. Check verified space like http://localhost:8080/#/s:balancer.eth
> feat: add BadgeVerified to offchain spaces

- apps/ui/src/components/ProposalVoteRankedChoice.vue
Closes: #268 
Fix wrong text color
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x504dd8da2930579b0aeb88946396140a74ce59fb8ccad5902cf1bfd2d33f1e07
2. The rank label in the choice form should have the correct text color on light and dark theme
> fix(ui): fix wrong text color

- apps/ui/src/networks/evm/constants.ts
Those were reversed in settings.
> fix: update OZVotes/OZVotes comp labels

- apps/api/src/schema.gql
- apps/subgraph-api/package.json
- apps/subgraph-api/schema.graphql
- apps/subgraph-api/src/mapping.ts
Those are needed so Highlight can fetch VP.
Already deploying to prod.
> feat: index axiom snapshot_address/snapshot_slot

- apps/ui/src/composables/useAccount.ts
- apps/ui/src/composables/useEditor.ts
- apps/ui/src/composables/useMarkdownEditor.ts
- As mentioned in https://github.com/snapshot-labs/sx-monorepo/pull/299#discussion_r1586336539 we need to move effects to the bottom 
- Everything should work same as before in editor while creating proposals
> refactor: Move all effects to bottom

- apps/ui/src/views/Proposal/Votes.vue
Add back the feature added in #343, which was gone when resolving a merge conflict
It's the same commit that has already been tAcked before
> fix: limit decimal in voting power

- apps/subgraph-api/package.json
Those are already deployed and syncing.
> chore: release subgraph-api 0.0.33

- apps/ui/src/App.vue
- apps/ui/src/components/EditorVotingType.vue
- apps/ui/src/components/Modal/LinkWalletConnect.vue
- apps/ui/src/components/Modal/SelectVotingType.vue
- apps/ui/src/components/SpaceTreasury.vue
- apps/ui/src/composables/useEditor.ts
- apps/ui/src/composables/useWalletConnect.ts
- apps/ui/src/composables/useWalletConnectTransaction.ts
- apps/ui/src/helpers/constants.ts
- apps/ui/src/types.ts
- apps/ui/src/views/Editor.vue
- apps/ui/src/views/Proposal/Overview.vue
This PR adds two column layout on Editor:
1. Voting type is moved to right sidebar (empty on onchain spaces currently).
2. Single choice voting is default (is network supports it).
3. Voting type is selected via Modal.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/336
1. Go to offchain space, try creating proposal, select different voting types.
> feat: add two-column Editor layout

- apps/ui/src/networks/offchain/api/index.ts
Closes: #
1. Go to http://localhost:8080/#/s:aave.eth
2. The 3 proposals should load
> fix: fix calling delete on undefined

- apps/ui/src/networks/common/graphqlApi/index.ts
- apps/ui/src/networks/offchain/api/index.ts
Refactor: avoid manipulating property on the original object
> refactor: do not manipulate original filters object

- apps/ui/src/components/App/Sidebar.vue
Add 8px height gradient on sidebar to make scroll looks more smooth
> style: add sidebar gradient

- apps/ui/src/networks/starknet/index.ts
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/422
> chore: rename Starknet (Sepolia) to Starknet Sepolia

- apps/api/src/overrrides.ts
- apps/mana/.env.example
- apps/mana/src/stark/herodotus.ts
- apps/ui/src/networks/starknet/constants.ts
- packages/sx.js/package.json
- packages/sx.js/src/clients/starknet/herodotus/abis/Strategy.json
- packages/sx.js/src/clients/starknet/herodotus/abis/StrategyLegacy.json
- packages/sx.js/src/clients/starknet/herodotus/index.ts
- packages/sx.js/src/starknetNetworks.ts
- packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts
- packages/sx.js/src/strategies/starknet/utils.ts
- packages/sx.js/src/types/networkConfig.ts
- packages/sx.js/test/unit/strategies/starknet/ozVotesStorageProof.test.ts
Closes: https://github.com/snapshot-labs/pitches/issues/82
1. Create space with new strategy (can use this token with OZVotes 224, slot index 8, `0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4`).
2. Create proposal.
3. You can vote on it after a while.
> feat: add support for updated Herodotus contracts on Sepolia

- apps/ui/package.json
- apps/ui/src/components/Ui/Textarea.test.ts
- yarn.lock
This covers https://github.com/snapshot-labs/sx-monorepo/pull/418
> test: add Textarea UI tests

- apps/ui/src/components/SpaceDelegates.vue
- apps/ui/src/composables/useDelegates.ts
Support a delegates API which index data from multiple tokens, this is to avoid running many delegates API.
> feat: support multi token delegates API

- apps/ui/package.json
- apps/ui/src/helpers/argentx.ts
- yarn.lock
- Move to starknetkit to support Argent mobile 
- Also include changes from https://github.com/snapshot-labs/sx-monorepo/pull/458/files
1. Try to connect with all sn wallets
2. Try to vote and create proposals
> feat: Move to starknetkit

- apps/ui/src/views/User.vue
- fix vote and proposal count percentage if total votes/proposals count is `0`
1. Go to http://localhost:8080/#/profile/0x24F15402C6Bb870554489b2fd2049A85d75B982f
| -------- | ------- |
| <img width="461" alt="Untitled 4" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/7214bde0-ac3e-4367-825d-dc3e3024b6f9"> | <img width="427" alt="Untitled 2" src="https://github.com/snapshot-labs/sx-monorepo/assets/15967809/b0427970-d2eb-4192-b371-10bd3d1309df"> |
> fix: NaN in user profile

- apps/ui/src/views/Settings/Spaces.vue
Closes: #454 
Fix an issue where the http://localhost:8080/#/settings was not returning any results
1. Go to http://localhost:8080/#/settings
2. It should show all your spaces again (both onchain and offchain), with a protocol switcher similar to the explore page
3. Changing protocol should show the corresponding spaces (if any)
4. Spaces should refresh when changing wallet
5. Spaces should refresh when logging in/out
> fix: fix my spaces pages not returning any results

- apps/ui/src/views/Proposal.vue
Issue after merging https://github.com/snapshot-labs/sx-monorepo/pull/427
- Tests should pass.
> chore: update help desk link format after merge

- apps/api/src/overrrides.ts
- apps/ui/.env
- packages/sx.js/src/clients/evm/ethereum-sig/index.ts
Update Mana to a new domain mana.box
> chore: update Mana domain

- apps/ui/README.md
- apps/ui/public/manifest.json
- apps/ui/src/components/SpaceDelegates.vue
- apps/ui/src/composables/useTitle.ts
- apps/ui/src/composables/useWalletConnect.ts
- apps/ui/src/networks/starknet/index.ts
- apps/ui/src/views/Proposal/Votes.vue
- apps/ui/src/views/Space/EditSettings.vue
- Fixes #559 
- Add meta title on edit settings page
- Use "Snapshot" instead of "Snapshot X" as app title
- Add spacing in delegate info message
> chore: small UI fixes

- apps/ui/src/components/Modal/LinkWalletConnect.vue
- apps/ui/src/views/Space/Overview.vue
- apps/ui/src/views/SpaceUser.vue
- apps/ui/src/views/SpaceUser/Statement.vue
- apps/ui/src/views/User.vue
This PR fixes the errors after running `yarn lint`
> chore: fix lint error

- apps/ui/src/views/Network.vue
Add recently added networks to network page
1. Go to http://localhost:8080/#/network
2. you should see new networks 
3. ![image](https://github.com/user-attachments/assets/273c4f08-3601-4aea-b70d-9bd5d6cff166)
> fix: Add zklink and fantom to network list

- apps/ui/src/views/Editor.vue
This way we can trigger prompt to sign user in.
1. Log out.
2. Enter editor.
3. Fill in the form, button to publish gets enabled.
4. When you click on it you will be prompted to sign in.
> fix: enable publish button if user is not logged in

- .changeset/big-schools-teach.md
Forgot to include changeset in that PR.
> chore: add missing changeset from #446

- apps/ui/src/components/Ui/SelectDropdown.vue
Add back the update from #532, gone from a merge conflict
> fix(ux): add outline to select dropdown

- packages/sx.js/src/clients/offchain/ethereum-sig/index.ts
- packages/sx.js/src/clients/starknet/starknet-sig/index.ts
- packages/sx.js/test/integration/offchain/index.test.ts
- packages/sx.js/test/unit/clients/offchain/ethereum-sig/index.test.ts
Missed a few here https://github.com/snapshot-labs/sx-monorepo/pull/593#discussion_r1706794172
- Changes values from scientific to standard notation
> chore: Change values to standard notation

- apps/ui/src/views/SpaceUser/Statement.vue
- apps/ui/src/views/User.vue
This PR fix an issue where 2 addresses are not considered the same, due to different case
> fix: use more robust address comparison from utils

- apps/ui/src/components/App/Topnav.vue
- apps/ui/src/components/Modal/Account.vue
On edit profile, User in top navbar is not updated. even after the reload, the avatar stays same as before
After editing name and avatar:
After a reload:
Changed it to use user from `usersStore` instead of `web3` values
1. Go to your profile
2. Edit your name and avatar
3. Before fix:
Notice that values in top nav are not updated, even after reloading avatar stays same
4. After fix:
Values are updated once user edit their profile
5. Also click on Account in top nav, it should open a "Account" modal, here avatar should be updated with new one
> fix: User in top nav is not updated on edit profile

- apps/ui/src/views/SpaceUser/Statement.vue
Closes: #668
- Make the link not full width
- Add external link icon
1. Go to http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/profile/0x0ac7231Cc1994fD98F80DB1c58efBA712Fb72f1A
2. The source link should not take full width
3. There is an arrow icon next to the source logo
> fix: improve statement source link format

- apps/ui/src/components/AppsListItem.vue
- apps/ui/src/components/TopicsListItem.vue
- apps/ui/src/helpers/discourse.ts
- apps/ui/src/views/Editor.vue
- apps/ui/src/views/Proposal/Overview.vue
- Use external links for the `/apps` page
- Fix user left overflow on topic items
- Increase width of proposal content and editor
You can test before after discussions before after here:
https://snapshot.box/#/s:safe.eth/discussions
https://bafybeihmbqlygdvj5eynb4rgvh37gfmbg5fzrdjefmcggkgvqsnpcd43zm.on.fleek.co/#/s:safe.eth/discussions
Proposal and editor here:
https://snapshot.box/#/s:safe.eth/proposal/0x86e0cee860e17a2f90b0d26e6e5ae0aff0c21330b8729ad449650c7ab84a0636
https://bafybeihmbqlygdvj5eynb4rgvh37gfmbg5fzrdjefmcggkgvqsnpcd43zm.on.fleek.co/#/s:safe.eth/proposal/0x86e0cee860e17a2f90b0d26e6e5ae0aff0c21330b8729ad449650c7ab84a0636
https://snapshot.box/#/s:safe.eth/create
https://bafybeihmbqlygdvj5eynb4rgvh37gfmbg5fzrdjefmcggkgvqsnpcd43zm.on.fleek.co/#/s:safe.eth/create
Apps: …
> style: various improvements

- apps/ui/src/components/Landing/Users.vue
Fixes infinite scroll animation on landing page
> fix: Infinite scroll animation on landing page

- apps/ui/src/views/My/Home.vue
If you visit http://localhost:8080/#/home you will be redirected to http://localhost:8080/#/explore
1. Go to http://localhost:8080/#/home as logged in, you see this page.
2. Go to http://localhost:8080/#/home as guest, you get redirected.
> feat: redirect home to explore if not logged in

- apps/ui/src/views/My/Home.vue
> chore: lint fix - removing unused variable

- apps/ui/src/components/App/Topnav.vue
- apps/ui/src/components/Ui/Modal.vue
- apps/ui/src/composables/useModal.ts
- apps/ui/src/views/My/Home.vue
Now visiting http://localhost:8080/#/home as not logged in user will trigger forced login.
1. Go to http://localhost:8080/#/home as logged in, you see your content.
2. Go to http://localhost:8080/#/home as guest, you are forced to log in.
3. Go to http://localhost:8080/#/explore as guest, it works.
> feat: force login on Home page

- apps/ui/src/stores/votingPowers.ts
This PR will calculate `canPropose` against `proposeVp` instead of using voting VP.
This is quick fix, generally I'm not a fan of the current setup we got, it's super complex, built on assumptions and error prone (we got second regression caused by it now), so there are still issue with it:
1. It uses assumption that when calling fetchVotingPower with proposal we want voting info, and when calling with space, we want proposing info, but it's not accurate. If we go to Proposals page we want to fetch VP for voting (so we display it in the UI) and information about the fact if we can propose or not. So VotingPowerItem has mix of two (`canPropose` flag computed on proposeVotingPowers which is different from `votingPowers` that it has inside as well.
2. Storage of `votingPowers` store is not …
> fix: validate proposal VP when fetching VP for space

- apps/ui/src/views/My/Explore.vue
- apps/ui/src/views/Settings/Spaces.vue
Bring back button to filter by protocol on Explore and My spaces pages.
> chore: show protocol filters

- apps/ui/src/components/FormSpaceDelegations.vue
- apps/ui/src/components/FormSpaceTreasuries.vue
- apps/ui/src/views/Create.vue
- apps/ui/src/views/Space/Settings.vue
Now users can change order of delegations and treasuries.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/728
1. Go to your space settings and add at least 2 treasuries or delegations.
2. You can change order of those.
> feat: add delegations and treasuries ordering

- packages/sx.js/src/strategies/starknet/evmSlotValue.ts
- packages/sx.js/src/strategies/starknet/ozVotesStorageProof.ts
Current contracts revert if slot is zero, but it's valid value (no VP). It has been updated on the contracts, but we use older version.
1. Go to http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/proposal/19
using account `0x1594D95E9D922fFeECa6C70CC6Bce3a62377D1A3`.
2. VP loads properly.
> fix: handle storage proof slot being zero

- .changeset/mighty-crabs-thank.md
https://github.com/snapshot-labs/sx-monorepo/pull/743/
> chore: add missing changeset

- apps/ui/src/components/Modal/Account.vue
Working towards https://github.com/snapshot-labs/workflow/issues/142
This PR is refactoring the account modal to remove extra div and classes. 
A more simpler code is needed, to make the white label PR changes less complex
1. Open the account modal as guest
2. It should look the same as before
3. Open the account modal as connected user
4. It should look the same as before
> refactor: cleanup and simplify account modal html structure

- apps/ui/src/components/SpaceTreasury.vue
- apps/ui/src/views/Space/Treasury.vue
As mentioned in https://github.com/snapshot-labs/sx-monorepo/pull/720#discussion_r1750927780
Going to http://localhost:8080/#/s:fabien.eth/treasury/1 should go to http://localhost:8080/#/s:fabien.eth/treasury/1/tokens instead of http://localhost:8080/#/s:fabien.eth/treasury/tokens
> fix: Default index for treasury

- apps/ui/src/components/App/Nav.vue
- apps/ui/src/helpers/ens.ts
- apps/ui/src/networks/evm/index.ts
- apps/ui/src/networks/offchain/index.ts
- apps/ui/src/networks/starknet/index.ts
- apps/ui/src/networks/types.ts
- apps/ui/src/views/Space/Settings.vue
This method can be used to get space controller in network agnostic matter.
1. Go to your offchain space.
2. You can see Settings navigation item.
> feat: add getSpaceController helper method

- apps/ui/src/components/EditorChoices.vue
- apps/ui/src/components/EditorVotingType.vue
- apps/ui/src/components/Modal/SelectVotingType.vue
- apps/ui/src/components/Ui/Composer.vue
- apps/ui/src/views/Editor.vue
Various improvements in the editors:
- Support deleting a choice using backspace key
- Add placeholder to content body
- Add tooltip for drafts button
- Separate draft and publish button, and use primary color for publish
- Rename voting type to voting system
> chore: editor improvements

- apps/ui/src/components/FormSpaceProfile.vue
From: https://github.com/snapshot-labs/sx-monorepo/pull/718#issuecomment-2350992127
1. Voting power symbol is loaded and updated properly.
> fix: update offchain settings to properly store VP symbol

- apps/ui/src/components/App/Nav.vue
- apps/ui/src/components/FormSpaceMembers.vue
- apps/ui/src/components/Modal/AddMembers.vue
- apps/ui/src/components/Ui/Dropdown.vue
- apps/ui/src/composables/useSpaceSettings.ts
- apps/ui/src/helpers/utils.test.ts
- apps/ui/src/helpers/utils.ts
- apps/ui/src/helpers/validation.ts
- apps/ui/src/networks/offchain/index.ts
- apps/ui/src/types.ts
- apps/ui/src/views/Space/Settings.vue
This PR adds members settings to offchain spaces.
1. Go to settings of offchain space you control.
2. You can go to members.
3. You can modify members as you want and save it.
> feat: add members settings for offchain spaces

- apps/ui/src/components/App/Nav.vue
- apps/ui/src/composables/useActions.ts
- apps/ui/src/composables/useSpaceSettings.ts
- apps/ui/src/helpers/ens.ts
- apps/ui/src/helpers/networks.json
- apps/ui/src/networks/offchain/actions.ts
- apps/ui/src/networks/offchain/index.ts
- apps/ui/src/networks/types.ts
- apps/ui/src/views/Space/Settings.vue
Changes:
- check `snapshot` record on ENS to detect real controller (as opposed to owner)
- add ability to change controller if you are a space owner
1. Go to your offchain space settings.
2. Change controller.
> feat: add space controller edition for offchain spaces

- apps/ui/src/components/App/Topnav.vue
- apps/ui/src/components/Modal/Account.vue
- apps/ui/src/components/Modal/Connector.vue
Closes https://github.com/snapshot-labs/workflow/issues/224
> fix: rename connect wallet to log in

- apps/ui/src/components/EditorChoices.vue
- apps/ui/src/components/SpaceDelegates.vue
- apps/ui/src/views/Proposal/Overview.vue
- apps/ui/src/views/Proposal/Votes.vue
Fix UiButton classes not being applied properly, need to used `!` to override default button style
> fix(ui): fix wrong button style

- apps/ui/src/components/SpaceDelegates.vue
- apps/ui/src/views/Proposal/Votes.vue
- apps/ui/src/views/User.vue
Closes: #772
1. Go to http://localhost:8080/#/s:apecoin.eth/delegates
2. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x062cc4845a9f7568c931afe3366bd6440b9b43061d98193fa651825f0c8b5173/votes
3. The voting power column should be truncated
> fix: truncate voting power column

- apps/ui/src/components/ButtonStrategy.vue
- apps/ui/src/components/EditorExecution.vue
- apps/ui/src/components/TransactionsListItem.vue
Closes https://github.com/snapshot-labs/workflow/issues/198
> fix: fix nested buttons

- apps/ui/src/components/FormSpaceAdvanced.vue
- apps/ui/src/components/FormSpaceProposal.vue
- apps/ui/src/components/FormSpaceVoting.vue
- apps/ui/src/composables/useSpaceSettings.ts
- apps/ui/src/views/Space/Settings.vue
This PR adds proposal settings (excluding validation as this will be similar to proposal validation so it will be done in single PR).
1. Go to your offchain space settings.
2. You can modify proposal settings.
> feat: add Proposal settings (excl. validation)

- apps/ui/src/components/FormSpaceProposal.vue
- apps/ui/src/components/FormSpaceStrategies.vue
- apps/ui/src/components/FormSpaceVoting.vue
- apps/ui/src/components/Modal/SelectValidation.vue
- apps/ui/src/components/Ui/SelectMultiple.vue
- apps/ui/src/components/Ui/StrategiesConfiguratorOffchain.vue
- apps/ui/src/components/Ui/Switch.vue
- apps/ui/src/composables/useSpaceSettings.ts
- apps/ui/src/helpers/constants.ts
- apps/ui/src/helpers/validation.ts
- apps/ui/src/networks/offchain/api/index.ts
- apps/ui/src/networks/offchain/api/types.ts
- apps/ui/src/types.ts
- apps/ui/src/views/Space/Settings.vue
This PR adds last missing functionality for Offchain space settings - voting and proposal validation.
Designs didn't include designs for basic voting validation so I improvised.
Closes: https://github.com/snapshot-labs/workflow/issues/152
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/836
1. Go to offchain space settings.
2. You can modify voting and proposal validation, using different strategies.
> feat: add support for voting and proposal validation

- .changeset/twenty-cups-hope.md
- apps/mana/src/stark/rpc.ts
- apps/ui/src/networks/common/graphqlApi/index.ts
- apps/ui/src/networks/common/graphqlApi/types.ts
- apps/ui/src/stores/votingPowers.ts
- apps/ui/src/views/Proposal/Overview.vue
- packages/sx.js/src/authenticators/starknet/ethSig.ts
Closes: https://github.com/snapshot-labs/workflow/issues/247
Fixes following bugs:
- Empty body (or other fields) won't cause editor to crash when triggering update proposal).
- Using correct method on mana for updating proposal.
- EthSig on starknet uses correct call format.
- VP is not refreshed for editor when coming from pending proposal.
1. Create proposal on Starknet space (make sure to have delay to allow updating).
2. Try updating it.
3. It works.
> fix: make update proposal for onchain spaces functional agian

- apps/subgraph-api/package.json
- apps/subgraph-api/src/helpers.ts
- apps/subgraph-api/src/mapping.ts
- apps/subgraph-api/tests/helpers.test.ts
Because it was mutating some value after regression it could end up mapping it to wrong value.
> fix: do not remap choice twice

- apps/api/src/schema.gql
- apps/api/src/writer.ts
- apps/subgraph-api/package.json
- apps/subgraph-api/schema.graphql
- apps/subgraph-api/src/mapping.ts
Extracted API changes only from https://github.com/snapshot-labs/sx-monorepo/pull/862 adding compatibility so both names will work for time being.
> chore: rename indicies to indices on API

- apps/ui/src/components/App/Topnav.vue
Fixes space between buttons in nav
Closes: https://github.com/snapshot-labs/workflow/issues/269
1. Go to home page and notice space between buttons in nav
> fix: Space between buttons in nav

- apps/api/src/ipfs.ts
- apps/api/src/schema.gql
- apps/api/src/writer.ts
- apps/subgraph-api/package.json
- apps/subgraph-api/schema.graphql
- apps/subgraph-api/src/ipfs.ts
- apps/subgraph-api/src/mapping.ts
Towards https://github.com/snapshot-labs/workflow/issues/89
> feat: store choices on the API

- apps/api/src/index.ts
So staging instance can resync on new changes.
> chore: bring back reset for Checkpoint

- apps/ui/src/components/Modal/Vote.vue
It has been already increased on APIs:
- https://github.com/snapshot-labs/snapshot.js/pull/1079
- https://github.com/snapshot-labs/sx-monorepo/pull/905
Closes: https://github.com/snapshot-labs/workflow/issues/260
1. Add long reason on offchain space vote.
2. Add long reason on onchain space vote.
> feat: increase reason length limit

- .vscode/extensions.json
This will add suggestions to install few useful VSCode extensions:
- Vue
- Tailwind CSS IntelliSense
- ESLint
- GitLens
- EditorConfig
- Prettier
> chore: add extension suggestions

- apps/mana/src/eth/rpc.ts
- apps/subgraph-api/networks.json
- apps/subgraph-api/package.json
- apps/subgraph-api/src/mapping.ts
- apps/ui/src/helpers/constants.ts
- apps/ui/src/helpers/etherscan.ts
- apps/ui/src/helpers/networks.json
- apps/ui/src/helpers/utils.ts
- apps/ui/src/networks/evm/actions.ts
- apps/ui/src/networks/evm/index.ts
- apps/ui/src/networks/index.ts
- apps/ui/src/types.ts
- packages/sx.js/src/evmNetworks.ts
Closes: #942
Discussion https://discord.com/channels/955773041898573854/1030773022048657449/1299184136551923742
We dropped support for linea. 
Furthermore, we were using goerli linea testnet, which don't work anymore since replaced by sepolia
This PR removes all references to linea network
1. Everything should work as before
> fix: remove linea network

- apps/ui/src/components/Modal/SelectPrivacy.vue
- apps/ui/src/helpers/constants.ts
Closes: https://github.com/snapshot-labs/workflow/issues/280
> fix: update and fix wrong text in privacy modal

- apps/ui/src/components/Layout/App.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/948
This PR fix the missing account modal on editor page
1. Go to the Editor page as guest
2. Fill a title
3. Click on the publish button
4. It should open the login modal
> fix: fix missing account modal on editor page

- README.md
Adding more info on how to run local services as currently we don't have this documented enough.
> docs: add yarn dev:full docks

- apps/api/package.json
- yarn.lock
Fixes issue with proposals page.
> chore: bump @checkpoint-labs/checkpoint to 0.1.0-beta.42

- .changeset/great-nails-wink.md
- packages/sx.js/src/strategies/starknet/evmSlotValue.ts
- packages/sx.js/src/utils/strategies.ts
Removes a needless log. Needed to enhance the message shown in the [hash verifier](https://github.com/snapshot-labs/hash-verifier)
> chore: remove needless log

- apps/api/src/index.ts
This way we can make api-2 new main instance.
> chore: remove reset for sx-api

- apps/ui/src/components/ProposalResults.vue
- apps/ui/src/components/ProposalsListItemHeading.vue
- apps/ui/src/helpers/quorum.test.ts
- apps/ui/src/helpers/quorum.ts
Depends on https://github.com/snapshot-labs/sx-monorepo/pull/993
Closes: https://github.com/snapshot-labs/workflow/issues/303
1. Go to http://localhost:8080/#/s:apecoin.eth/proposal/0xd9d7e89ce47e99f5ee7556c092d4f67e388926470fedfc7c848e893b0486fe86
> feat: format quorum using compact format

- apps/ui/src/helpers/efp.ts
- apps/ui/src/views/User.vue
Show followings and followers count on user main profile using EFP.
For EVM user: http://localhost:8080/#/profile/0x2332a02fea96b42fc3095ae7c73963980db9331b
For Starknet user (incompatible): http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/profile/0x04ea765e7bfb966f8420fb21b649cddae0641345138590564bb449e36b32c527
> feat: add follows count from EFP

- apps/ui/src/main.ts
- White list apechain safe
1. Create a safe on https://safe.apechain.com/
2. Should open snapshot as an app
> fix: whitelist apechain safe

- apps/ui/src/components/ProposalResults.vue
- apps/ui/src/views/Proposal.vue
Closes: https://github.com/snapshot-labs/workflow/issues/326
This PR will show the results on pending proposals
1. Go to an onchain/offchain pending proposals
2. You should see the results in the sidebar
> fix: show results on pending proposals

- apps/ui/src/components/App/Sidebar.vue
- apps/ui/src/components/SpaceAvatar.vue
- apps/ui/src/components/SpacesListItem.vue
- apps/ui/src/components/Ui/BadgeNetwork.vue
- apps/ui/src/networks/common/graphqlApi/index.ts
- apps/ui/src/networks/offchain/api/index.ts
- apps/ui/src/networks/offchain/api/queries.ts
- apps/ui/src/networks/offchain/api/types.ts
- apps/ui/src/types.ts
This will display active proposals indicator on onchain spaces in sidebar.
Closes: https://github.com/snapshot-labs/workflow/issues/328
1. Check sidebar.
2. Other avatars are not broken.
> feat: add active proposals indicator

- apps/ui/src/composables/useActions.ts
- apps/ui/src/networks/evm/actions.ts
- apps/ui/src/networks/starknet/actions.ts
- apps/ui/src/networks/types.ts
Removing actions that are no longer used (were replaced by updateSettings):
- setMetadata
- setVotingDelay
- setMinVotingDuration
- setMaxVotingDuration
This will reduce number of changes needed as we change behaviour of calling actions as Safe.
We leave actions in sx.js in clients as-is.
> refactor: remove unused actions

- apps/mana/src/eth/rpc.ts
- apps/subgraph-api/networks.json
- apps/subgraph-api/package.json
- apps/subgraph-api/src/mapping.ts
- apps/subgraph-api/subgraph.yaml
- apps/ui/src/helpers/connectors.ts
- apps/ui/src/helpers/constants.ts
- apps/ui/src/helpers/etherscan.ts
- apps/ui/src/networks/evm/actions.ts
- apps/ui/src/networks/evm/index.ts
- apps/ui/src/networks/index.ts
- apps/ui/src/types.ts
- packages/sx.js/src/evmNetworks.ts
This PR adds support for Base on SnapshotX.
Closes: https://github.com/snapshot-labs/workflow/issues/287
**Note: For some reason subgraph for Base has few minutes of delay.**
0. Run local mana.
1. [x] Creating space.
2. [x] Proposing and voting with EthTx.
3. [x] Proposing and voting with EthSig.
> feat: add Base to SnapshotX

- .changeset/lucky-kangaroos-approve.md
- apps/ui/src/composables/useActions.ts
- apps/ui/src/networks/evm/actions.ts
- apps/ui/src/networks/offchain/actions.ts
- apps/ui/src/networks/starknet/actions.ts
- apps/ui/src/networks/types.ts
- apps/ui/src/views/Proposal/Overview.vue
- packages/sx.js/src/clients/offchain/ethereum-sig/index.ts
- packages/sx.js/src/clients/offchain/ethereum-sig/types.ts
- packages/sx.js/src/clients/offchain/types.ts
Now you can flag offchain proposals if you are an admin or moderator.
Closes: https://github.com/snapshot-labs/workflow/issues/339
1. Go to space you are admin or moderator off.
2. Go to some proposal.
3. You can flag it.
> feat: add option to flag offchain proposals

- apps/ui/src/composables/useEditor.ts
- apps/ui/src/composables/useSpaceSettings.ts
- apps/ui/src/networks/common/graphqlApi/index.ts
- apps/ui/src/networks/offchain/api/index.ts
- apps/ui/src/types.ts
- apps/ui/src/views/Space/Editor.vue
With this change guidelines and template will be used in Editor page.
Closes: https://github.com/snapshot-labs/workflow/issues/364
1. Go to http://localhost:8080/#/s:popartcats.eth/create
2. Guidelines and template are displayed.
> feat: display Space guidelines and template

- .changeset/spotty-peas-fold.md
- apps/ui/src/components/Modal/Votes.vue
- apps/ui/src/networks/offchain/actions.ts
- packages/sx.js/src/clients/offchain/ethereum-sig/index.ts
- packages/sx.js/src/clients/offchain/types.ts
- packages/sx.js/test/unit/clients/offchain/ethereum-sig/__snapshots__/index.test.ts.snap
- packages/sx.js/test/unit/clients/offchain/ethereum-sig/index.test.ts
Context: https://discord.com/channels/955773041898573854/1182427601046884352/1326951643258032260
1. Go to any proposal without shutter
2. Try to vote
3. It should not return any error
> fix: voting on proposals with privacy none

- apps/ui/src/networks/evm/actions.ts
When using different network we should still resolve ENS domains on mainnet.
Closes: https://github.com/snapshot-labs/workflow/issues/402
1. Go to space http://localhost:8080/#/s:odos.eth/delegates (this space is using base network)
2. Try delegating to ENS name.
3. It resolves to correct address.
> fix: resolve ENS domains on mainnet

- apps/ui/src/helpers/constants.ts
Closes: https://github.com/snapshot-labs/workflow/issues/406
1. Go explore page or space settings
2. You should see new categories
> chore: add new space categories

- apps/ui/src/components/Affix.vue
This PR fix the affix component, which was not sticking anymore
1. Go to http://localhost:8080/#/s:arbitrumfoundation.eth/proposal/0xbd77b4faf99e06c7b4117e5dafaf5bb8f873bcffbb5c9d414a7ff745b6849f3a
2. The sidebar should always be visibile, and scroll independently from the main content
> fix: fix broken Affix component

- package.json
- turbo.json
- yarn.lock
Nothing should change, just no more prompt to upgrade.
> chore: bump turbo to v2

- apps/ui/package.json
- apps/ui/src/composables/useConnectors.ts
- yarn.lock
- Update coinbase wallet to latest version
Closes: https://github.com/snapshot-labs/workflow/issues/430
1. Try to connect and vote with:
- Coinbase smart wallet ✅ 
- Web extension ✅ 
- Mobile wallet ✅
> chore: update coinbase wallet version

- apps/ui/src/components/Breadcrumb.vue
- apps/ui/src/components/FormSpaceWhitelabel.vue
- apps/ui/src/components/Ui/InputStamp.vue
- apps/ui/src/components/Ui/Select.vue
- apps/ui/src/components/Ui/Stamp.vue
- apps/ui/src/composables/useSpaceSettings.ts
- apps/ui/src/helpers/utils.ts
- apps/ui/src/networks/offchain/api/index.ts
- apps/ui/src/networks/offchain/api/queries.ts
- apps/ui/src/networks/offchain/api/types.ts
- apps/ui/src/types.ts
- apps/ui/src/views/Space/Settings.vue
This reverts commit 91f9cecc3751ea812969acd10395725dbf41f4ad.
Reverting the skin PR , causing non-turbo space settings from being saved
> Revert "feat: add form to update skin settings (#1148)"

- README.md
- docs/vue-query.md
Starting off documenting usage and conventions of vue-query in our app.
This will be evolving as we grow our usage and we learn and build our own conventions.
> docs: add initial vue-query docs

- apps/ui/src/components/FormSpaceLabels.vue
Closes: https://github.com/snapshot-labs/workflow/issues/463
1. Go to http://localhost:8080/#/s:test.wa0x6e.eth/settings/labels
2. On a small screen, label description should be on a second line
> fix: fix overflowing label description

- apps/ui/src/helpers/connectors/walletconnect.ts
Closes: https://github.com/snapshot-labs/workflow/issues/467
1. On mobile, Select wallet connect
| --- | --- | 
| ![image](https://github.com/user-attachments/assets/23d7dd1c-6a02-41eb-8a15-3b4401d6d27d) | ![image](https://github.com/user-attachments/assets/61f5ee85-8e36-4183-9121-21c6c588328f) |
> fix: wallectconnect show all wallets on mobile

- apps/ui/src/composables/useConnectors.ts
- apps/ui/src/helpers/connectors/walletconnect.ts
- Add description to make it work with trust wallet/leap wallet
- Update disconnect method according to [docs](https://docs.reown.com/appkit/javascript/core/actions#disconnect) to avoid notice 
Closes: https://github.com/snapshot-labs/workflow/issues/472
1. Select wallet connect in connector list
2. Scan with trust wallet/leap wallet
3. You should be able to connect and vote
4. You should not see a notice related to walletconnect disconnect in console
> fix: add description to connector details and update disconnect method

- apps/ui/src/main.ts
Closes: https://github.com/snapshot-labs/workflow/issues/479
1. Add app as a Safe App
2. App should open
> fix: host issue with snapshot on Safe

- apps/ui/src/views/Space/Editor.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1248
- Fix missing right border in the editor top nav in wide screen
- Decrease buttons spacing in the editor top nav
> fix: fix missing border and spacing in editor top nav

- apps/ui/src/components/Modal/Votes.vue
- apps/ui/src/components/SpaceDelegates.vue
- apps/ui/src/queries/votes.ts
- apps/ui/src/views/Proposal/Votes.vue
This PR refactors proposal votes to be fetched with Vue Query.
Towards: https://github.com/snapshot-labs/workflow/issues/410
Use hide whitespace to make review easier:
1. Go to: http://localhost:8080/#/s:aave.eth/proposal/0xe88851746761eee3418eb49105349bd272917759c922133506e420fcf6c4d9eb
2. Click votes, they load as exepcted.
3. Go to Overview, click Votes at the bottom of proposal to open popup.
4. Votes are visible immediately.
5. Sorting & ordering on Votes tab works as exepcted.
> refactor: fetch votes via vue-query

- apps/api/src/evm/utils.ts
- apps/api/src/evm/writers.ts
- apps/api/src/starknet/utils.ts
- apps/api/src/starknet/writers.ts
- Updated all references to the renamed function across the codebase 🔄
> chore: fix spelling of updateProposalValidationStrategy function

- apps/ui/src/components/FormNetwork.vue
- apps/ui/src/components/FormSpaceProfile.vue
- apps/ui/src/components/FormSpaceProposal.vue
- apps/ui/src/components/FormSpaceStrategies.vue
- apps/ui/src/components/FormSpaceWhitelabel.vue
- apps/ui/src/components/FormVoting.vue
- apps/ui/src/components/Layout/App.vue
- apps/ui/src/components/Modal/SelectValidation.vue
- apps/ui/src/components/ProposalTimeline.vue
- apps/ui/src/components/Ui/ContainerSettings.vue
- apps/ui/src/components/Ui/Editable.vue
- apps/ui/src/components/Ui/Form.vue
- apps/ui/src/components/Ui/Stepper.vue
- apps/ui/src/style.scss
- apps/ui/src/views/CreateSpaceSnapshot.vue
- apps/ui/src/views/CreateSpaceSnapshotX.vue
- apps/ui/src/views/My/Explore.vue
- apps/ui/src/views/Proposal.vue
- apps/ui/src/views/Proposal/Votes.vue
- apps/ui/src/views/Settings/Spaces.vue
- apps/ui/src/views/Space/Editor.vue
- apps/ui/src/views/Space/Settings.vue
- apps/ui/src/views/SpaceUser/Statement.vue
- apps/ui/src/views/Topic.vue
To review enable this option:
Closes: https://github.com/snapshot-labs/workflow/issues/475
Closes: https://github.com/snapshot-labs/workflow/issues/478
Closes: https://github.com/snapshot-labs/workflow/issues/477
1. Test all steps in space settings for space inconsistencies 
2. Test all steps in space creation to create a snapshot space
3. Test all steps in space creation to create a snapshotX space
4. Test all pages to have consistent spacing
> fix: consistent spacing

- apps/ui/src/routes/index.ts
kind of revert backs changes from [here](https://github.com/snapshot-labs/sx-monorepo/pull/1277/files#r2008040547) but removes prefix using starts with
Closes: https://github.com/snapshot-labs/workflow/issues/511
These redictions should work
- http://localhost:8080/#/s:gal.eth → http://localhost:8080/#/s:g-dao.eth
- http://localhost:8080/#/gal.eth → http://localhost:8080/#/s:g-dao.eth
- http://localhost:8080/#/safe.eth → http://localhost:8080/#/s:safe.eth
- http://localhost:8080/#/s:safe.eth/about → http://localhost:8080/#/s:safe.eth
- http://localhost:8080/#/safe.eth/about → http://localhost:8080/#/s:safe.eth
- http://localhost:8080/#/arbitrumfoundation.eth/proposal/0x2bc8e69eb65f3b2127072242ca317f51578db014019e22e8b370254e0566a4cf → …
> fix: improve redirection

- apps/ui/src/composables/useActions.ts
Unable to understand user problems if there is a problem with wallet
Trying to understand the problem here https://app.intercom.com/a/inbox/n9dmxtcs/inbox/shared/all/conversation/1167?view=List
> chore: error logging for better debugging inside wrapWithErrors

- apps/ui/src/components/Landing/Users.vue
- apps/ui/src/helpers/aliases.json
- apps/ui/src/helpers/discourse.ts
Fixes https://github.com/snapshot-labs/workflow/issues/535
> chore: migrate aave.eth to aavedao.eth

- apps/ui/src/views/Space/Pro.vue
This PR fix some issues on small screen for the pro page, and also use more flex power for elements positioning and margin
> fix: fix responsiveness and improve stucture

- apps/ui/src/views/Space/Pro.vue
> chore: remove dead code

- apps/mana/src/eth/rpc.ts
To debug issue with invalid signature with Frame and Ledger.
> chore: log entire envelope

- apps/ui/src/components/Layout/App.vue
- apps/ui/src/helpers/townhall/api.ts
- apps/ui/src/routes/default.ts
- apps/ui/src/views/Townhall/Space.vue
Add space specific Townhall demo page.
> feat: add Townhall space page

- apps/api/package.json
- apps/highlight/package.json
- apps/highlight/src/agents/townhall.ts
- apps/highlight/src/api/config.json
- apps/highlight/src/api/schema.gql
- apps/highlight/src/api/writers.ts
- apps/ui/src/components/Modal/LabelConfig.vue
- apps/ui/src/composables/useTownhall.ts
- apps/ui/src/helpers/townhall/api.ts
- apps/ui/src/helpers/townhall/types.ts
- apps/ui/src/routes/default.ts
- apps/ui/src/views/Townhall/Settings.vue
- packages/sx.js/src/clients/highlight/ethereum-sig.ts
- packages/sx.js/src/clients/highlight/types.ts
- packages/sx.js/src/highlightConstants.ts
- yarn.lock
This PR adds ability to create, edit and delete space roles.
Towards: https://github.com/snapshot-labs/workflow/issues/549
1. Go to http://localhost:8080/#/townhall/ethereum/settings
2. You can add roles.
3. You can delete roles.
4. You can edit roles.
> feat(townhall): add roles

- apps/ui/src/components/Layout/App.vue
- apps/ui/src/components/Modal/Space.vue
- apps/ui/src/routes/default.ts
- apps/ui/src/views/Space/Pro.vue
This PR adds a global pro page under http://localhost:8080/#/pro
It's reusing the same space pro page, without the space specific section
1. Go to http://localhost:8080/#/pro
> feat: add new global pro page

- apps/ui/src/helpers/constants.ts
- apps/ui/src/helpers/ens.ts
- apps/ui/src/helpers/utils.ts
- apps/ui/src/networks/common/graphqlApi/index.ts
- apps/ui/src/views/Proposal/Overview.vue
Starknet empty address is different than EVM one so we need to compare it to different value.
Closes: https://github.com/snapshot-labs/workflow/issues/576
1. Go to http://localhost:8080/#/sn:0x009fedaf0d7a480d21a27683b0965c0f8ded35b3f1cac39827a25a06a8a682a4/proposal/8
2. No warning about invalid proposal.
> fix: use different empty address for Starknet in execution check

- apps/mana/src/stark/herodotus.ts
- apps/ui/src/components/ButtonFollow.vue
- apps/ui/src/components/CreateDeploymentProgress.vue
- apps/ui/src/composables/useActions.ts
- apps/ui/src/helpers/utils.test.ts
- apps/ui/src/helpers/utils.ts
- apps/ui/src/views/Proposal/Overview.vue
- apps/ui/tsconfig.json
This is default option, which we disabled which gave us extra any in code.
With this we are probably typing our catch blocks.
Also to simplify showing errors to users in type-safe manner I added getUserFacingErrorMessage which can be used to format existing error with common fallback.
1. CI passes.
> chore: enable useUnknownInCatchVariables

- apps/ui/src/components/ProposalsListItemHeading.vue
- apps/ui/src/components/Site/Footer.vue
- apps/ui/src/views/Space/Overview.vue
- apps/ui/src/views/SpaceUser.vue
- apps/ui/src/views/User.vue
This pull request introduces two main types of changes: enhancements to the voting indicator logic in the `ProposalsListItemHeading` component and updates to the styling of social link elements across multiple components. Below are the key changes grouped by theme:
* Added a new `hasVoted` computed property in `ProposalsListItemHeading.vue` to centralize the logic for determining if a user has voted on a proposal. This replaces inline logic and improves maintainability.
* Removed the inline `v-if` logic for the voting indicator and replaced it with the newly introduced `hasVoted` property. This simplifies the template code.
* Updated the template to display a "voted" label along with an `IH-check` icon when `hasVoted` is true, improving the user interface for proposals.
* Updated the …
> ux: various ux improvement

- apps/api/package.json
- apps/api/src/evm/writers.ts
- apps/api/src/starknet/writers.ts
- yarn.lock
This releases brings some performance changes and optimizations that will reduce number of RPC requests.
This will also solve issue of Starknet sepolia indexer getting stuck on empty blocks.
1. Run `sep`/`sn-sep` indexers.
2. After some time it syncs up.
> chore: update to @snapshot-labs/checkpoint@0.1.0-beta.63

- packages/sx.js/src/strategies/offchain/remote-validate.ts
- packages/sx.js/src/strategies/offchain/remote-vp.ts
deprecated param
1. go to any proposal and try to vote
2. check newtwork tab
> chore: removed delegation parameter

- apps/ui/.storybook/preview.ts
- apps/ui/src/components/Ui/Alert.stories.ts
- apps/ui/src/components/Ui/BadgeVerified.stories.ts
- apps/ui/src/components/Ui/Calendar.stories.ts
- apps/ui/src/components/Ui/Markdown.stories.ts
- apps/ui/src/components/Ui/Markdown.vue
- apps/ui/src/components/Ui/Switch.stories.ts
Adding more stories as starting point.
Includes:
- Alert
- BadgeVerified
- Calendar
- Markdown (includes fix that prevented syntax highlighting from working).
- Switch
Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/1484
1. Run `yarn --cwd apps/ui storybook`.
> chore: add initial component stories

- apps/ui/src/views/Proposal/Overview.vue
- apps/ui/src/views/Space/Editor.vue
- apps/ui/src/views/Space/Settings.vue
Closes: https://github.com/snapshot-labs/workflow/issues/563
1. Save offchain space, you see alert.
2. Create proposal, you see alert.
3. Update proposal, you see alert.
> feat: add alerts on success space save & proposal created

- apps/ui/.storybook/preview.ts
- apps/ui/src/components/Ui/Carousel.stories.ts
- apps/ui/src/components/Ui/Link.stories.ts
- apps/ui/src/components/Ui/Loading.stories.ts
- apps/ui/src/components/Ui/Message.stories.ts
- apps/ui/src/components/Ui/ProposalLabel.stories.ts
- apps/ui/src/components/Ui/ProposalLabel.vue
- apps/ui/src/components/Ui/SelectorNetwork.stories.ts
Included are:
- `Carousel`
- `Link`
- `Loading`
- `Message`
- `ProposalLabel`
- `SelectorNetwork`
1. Open ui-storybook preview.
2. Check mentioned components.
> feat: add more component stories

- apps/mana/logger.ts
- apps/mana/package.json
- apps/mana/src/eth/logger.ts
- apps/mana/src/eth/registered.ts
- apps/mana/src/eth/rpc.ts
- apps/mana/src/index.ts
- apps/mana/src/stark/herodotus.ts
- apps/mana/src/stark/logger.ts
- apps/mana/src/stark/nonce-manager.ts
- apps/mana/src/stark/registered.ts
- apps/mana/src/stark/rpc.ts
- yarn.lock
To make working with logs easier we should use structured logs.
We are grouping logs now by level and use more structured format so we can easily filter same errors.
Logs were grouped by following convention (from BetterStack article):
- INFO: Significant and noteworthy business events.
- WARN: Abnormal situations that may indicate future problems.
- ERROR: Unrecoverable errors that affect a specific operation.
- FATAL: Unrecoverable errors that affect the entire program.
With those in place we will be able to set up useful alerts.
1. Run mana, it still works, you get structured logs.
- removed old `console.time` as it was unreliable - doesn't work well with async code (Warning: Label 'Send' already exists for console.time()).
- Unified error variable to `err` so error always ends up as …
> feat: add structured logs to mana with pino

- apps/api/src/indexer.ts
If database doesn't exists (it was newely deployed) we always want to call resets.
> fix: only check version tag if database already exists

- apps/ui/src/components/Modal/EditStrategy.vue
Previously we used clone which is done using JSON.parse/JSON.stringify so all functions were removed. Because of this strategies lost their functions (like one that turns params into protocol-level params).
Because of this it actually ended up writing broken state to chain.
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1543
1. Go to offchain space with proposal validation using ERC-20 votes comp strategy.
2. Refresh the page.
3. Try updating the proposal threshold and saving.
4. Use API (for example https://testnet-api.snapshot.box/) to check your space `voting_power_validation_strategy_strategies_params`.
5. It's not broken anymore
```gql
{
space(id: "0xC4DCe983943Ad61109dcbc1cfcEf8f867a8a0895") {
voting_power_validation_strategy_strategies_params
}
}
```
> fix: clone substrategies retaining functions

- apps/ui/src/views/Proposal/Execution.vue
- apps/ui/src/views/Proposal/Overview.vue
- apps/ui/src/views/Space/Editor.vue
- apps/ui/src/views/Topic.vue
Increase width size for proposal, editor and topic views by 20px. Also increase the proposal title a bit
> ux: increase max-width for various proposal, editor and topic views

- apps/ui/src/components/SpaceDelegates.vue
- apps/ui/src/views/Space/Leaderboard.vue
Closes: https://github.com/snapshot-labs/sx-monorepo/issues/1615
This PR add an horizontal margin around the delegates and leaderboard list, for consistency with other list
> fix: add margin around delegates and leaderboard list
